import D0.Claims.InvariantGenerationBridge
import D0.Foundation.InvariantAlgebraDegree
import D0.Synthesis.IntrinsicQuotientReconstruction
import D0.Synthesis.PhasonActiveSceneConjugacy
import D0.Synthesis.TopHodgeNormalizedQuotientSpectrum
import Mathlib.Tactic

/-!
# D0-AUTOMORPHISM-HODGE-SDE-DECOMPOSITION-001

This file closes a cross-owner gap between four already actual constructions:

1. the Reynolds projector built from the literal within-zone permutation
   generators;
2. the literal `33 × 33` normalized scene Laplacian;
3. the canonical stationary/active split of the normalized `3 × 3` quotient;
4. the top-Hodge reconstruction of the active `S_DE` characteristic factor.

The zone-average map below is a canonical left inverse to the indicator lift:
it averages over an entire orbit instead of choosing one representative
vertex.  Its other composite is exactly the independently constructed
Reynolds projector.  Consequently the full normalized Laplacian admits the
exact three-block decomposition

```
Q^33 = archive_30 ⊕ stationary_1 ⊕ active_2,

L_full | archive    = I,
L_full | stationary = 0,
L_full | active     ≃ S_DE.
```

The projector traces are `(30,1,2)`.  The active matrix and its coordinates
come from the independently proved literal-scene conjugacy; the actual
top-Hodge coordinates do not construct that conjugacy, but independently
force its characteristic constant coefficient `359/160`.

Honest scope:

* this is exact finite rational operator algebra for the frozen
  `K(9,11,13)` scene;
* `archive` here names the 30-dimensional complement of the Reynolds image;
  it is not identified with the separately typed integer archive Laplacian;
* the top-Hodge operator acts on top chains, not on this vertex space; the
  bridge here is equality of the reconstructed active characteristic
  polynomial, not an intertwiner between those two carriers;
* the chosen `2 × 2` active coordinates remain noncanonical, although the
  active projector and similarity class are canonical;
* the literal generator list has the proved orbit closure used by the
  Reynolds projector; the stronger statement that this list presents the
  entire abstract automorphism group remains cited rather than formalized;
* no physical generation-name assignment, continuum limit, equation of
  state, redshift law, or empirical claim is promoted.
-/

namespace D0.Synthesis.AutomorphismHodgeSDEDecomposition

open scoped BigOperators
open D0.Synthesis.IntrinsicQuotientReconstruction
open D0.Synthesis.PhasonActiveSceneConjugacy
open D0.Synthesis.TopHodgeNormalizedQuotientSpectrum

abbrev Vertex33 := Fin 33
abbrev Zone3 := Fin 3
abbrev Mode2 := Fin 2

private abbrev C : Matrix Vertex33 Zone3 ℚ :=
  intrinsicIndicator

private abbrev reynolds : Matrix Vertex33 Vertex33 ℚ :=
  D0.Claims.InvariantGenerationBridge.P

private abbrev Lfull : Matrix Vertex33 Vertex33 ℚ :=
  D0.Synthesis.SceneNormalizedQuotientDescent.fullNormalizedLaplacian

private abbrev Lzone : Matrix Zone3 Zone3 ℚ :=
  normalizedSceneLaplacian

private abbrev T₂ : Matrix Mode2 Mode2 ℚ :=
  sdeTransfer

/-! ## Orbit averaging without representative choices -/

/-- Average a full vertex function over each degree-spectral orbit.  Both the
indicator and the masses used here were reconstructed from the literal degree
operator in `IntrinsicQuotientReconstruction`. -/
abbrev zoneAverage : Matrix Zone3 Vertex33 ℚ :=
  intrinsicRestriction

/-- Averaging after the zone-indicator lift is the identity. -/
theorem zoneAverage_indicator :
    zoneAverage * C = (1 : Matrix Zone3 Zone3 ℚ) := by
  exact intrinsicRestriction_indicator

/-- The other composite is the zone-average projector. -/
theorem indicator_zoneAverage_eq_zoneProjector :
    C * zoneAverage = D0.Claims.InvariantGenerationBridge.Q := by
  exact intrinsicQuotientProjector_eq_zoneProjector

/-- **Independent-construction bridge.**  Indicator lift followed by orbit
averaging is exactly the Reynolds projector built from the literal
permutation generators. -/
theorem indicator_zoneAverage_eq_reynolds :
    C * zoneAverage = reynolds := by
  rw [indicator_zoneAverage_eq_zoneProjector]
  exact D0.Claims.InvariantGenerationBridge.bridge_projector_eq.symm

/-- The Reynolds image is exactly the image of the zone-indicator lift. -/
theorem reynolds_image_factorization :
    reynolds = C * zoneAverage ∧ zoneAverage * C = 1 :=
  ⟨indicator_zoneAverage_eq_reynolds.symm, zoneAverage_indicator⟩

/-- The separately proved full-automorphism invariant algebra is generated by
the same degree observable whose three fibres define the Reynolds image. -/
theorem full_graph_fixed_algebra_is_degree_generated
    (f : Vertex33 → ℚ) :
    D0.Foundation.InvariantAlgebraDegree.GraphAutInvariant f ↔
      ∃! q : D0.Foundation.InvariantAlgebraDegree.QuadraticCoefficients,
        ∀ i, f i =
          D0.Foundation.InvariantAlgebraDegree.QuadraticCoefficients.eval q i :=
  D0.Foundation.InvariantAlgebraDegree.degree_generates_full_invariant_algebra f

/-! ## Three canonical full-scene projectors -/

/-- Within-zone/archive projector, complementary to the Reynolds image. -/
def archiveProjector : Matrix Vertex33 Vertex33 ℚ :=
  1 - reynolds

theorem archiveProjector_eq_intrinsic :
    archiveProjector =
      intrinsicArchiveProjector := by
  unfold archiveProjector reynolds intrinsicArchiveProjector
  rw [← intrinsicQuotientProjector_eq_reynolds]

/-- Stationary projector on the quotient. -/
def quotientStationaryProjector : Matrix Zone3 Zone3 ℚ :=
  1 - D0.Synthesis.PhasonActiveSceneConjugacy.activeProjector

/-- Lift a quotient operator to the canonical Reynolds image. -/
def liftQuotient (J : Matrix Zone3 Zone3 ℚ) :
    Matrix Vertex33 Vertex33 ℚ :=
  C * J * zoneAverage

/-- Lifted one-dimensional stationary projector. -/
def fullStationaryProjector : Matrix Vertex33 Vertex33 ℚ :=
  liftQuotient quotientStationaryProjector

/-- Lifted two-dimensional active projector. -/
def fullActiveProjector : Matrix Vertex33 Vertex33 ℚ :=
  liftQuotient D0.Synthesis.PhasonActiveSceneConjugacy.activeProjector

theorem quotientStationaryProjector_idempotent :
    quotientStationaryProjector * quotientStationaryProjector =
      quotientStationaryProjector := by
  unfold quotientStationaryProjector
  noncomm_ring
    [D0.Synthesis.PhasonActiveSceneConjugacy.activeProjector_idempotent]

theorem quotient_stationary_active_split :
    quotientStationaryProjector +
        D0.Synthesis.PhasonActiveSceneConjugacy.activeProjector = 1 := by
  unfold quotientStationaryProjector
  noncomm_ring

theorem quotient_stationary_active_orthogonal :
    quotientStationaryProjector *
        D0.Synthesis.PhasonActiveSceneConjugacy.activeProjector = 0 ∧
      D0.Synthesis.PhasonActiveSceneConjugacy.activeProjector *
        quotientStationaryProjector = 0 := by
  unfold quotientStationaryProjector
  constructor <;>
    noncomm_ring
      [D0.Synthesis.PhasonActiveSceneConjugacy.activeProjector_idempotent]

theorem liftQuotient_mul (J K : Matrix Zone3 Zone3 ℚ) :
    liftQuotient J * liftQuotient K = liftQuotient (J * K) := by
  unfold liftQuotient
  calc
    (C * J * zoneAverage) * (C * K * zoneAverage) =
        C * J * (zoneAverage * C) * K * zoneAverage := by
      simp only [Matrix.mul_assoc]
    _ = C * J * K * zoneAverage := by
      rw [zoneAverage_indicator]
      simp only [Matrix.mul_one]
    _ = C * (J * K) * zoneAverage := by
      simp only [Matrix.mul_assoc]

theorem liftQuotient_add (J K : Matrix Zone3 Zone3 ℚ) :
    liftQuotient (J + K) = liftQuotient J + liftQuotient K := by
  simp [liftQuotient, Matrix.mul_add, Matrix.add_mul]

theorem liftQuotient_one :
    liftQuotient (1 : Matrix Zone3 Zone3 ℚ) = reynolds := by
  unfold liftQuotient
  rw [Matrix.mul_one, indicator_zoneAverage_eq_reynolds]

theorem liftQuotient_zero :
    liftQuotient (0 : Matrix Zone3 Zone3 ℚ) = 0 := by
  simp [liftQuotient]

theorem trace_liftQuotient (J : Matrix Zone3 Zone3 ℚ) :
    Matrix.trace (liftQuotient J) = Matrix.trace J := by
  unfold liftQuotient
  rw [Matrix.trace_mul_cycle, zoneAverage_indicator, Matrix.one_mul]

theorem reynolds_idempotent :
    reynolds * reynolds = reynolds := by
  rw [← liftQuotient_one, liftQuotient_mul, Matrix.one_mul]

theorem reynolds_mul_liftQuotient (J : Matrix Zone3 Zone3 ℚ) :
    reynolds * liftQuotient J = liftQuotient J := by
  rw [← liftQuotient_one, liftQuotient_mul, Matrix.one_mul]

theorem liftQuotient_mul_reynolds (J : Matrix Zone3 Zone3 ℚ) :
    liftQuotient J * reynolds = liftQuotient J := by
  rw [← liftQuotient_one, liftQuotient_mul, Matrix.mul_one]

/-- The stationary and active projectors split the Reynolds image. -/
theorem reynolds_stationary_active_split :
    fullStationaryProjector + fullActiveProjector = reynolds := by
  unfold fullStationaryProjector fullActiveProjector
  rw [← liftQuotient_add, quotient_stationary_active_split,
    liftQuotient_one]

/-- The archive, stationary and active projectors form a complete,
pairwise-annihilating idempotent decomposition. -/
theorem full_three_projectors :
    archiveProjector * archiveProjector = archiveProjector ∧
      fullStationaryProjector * fullStationaryProjector =
        fullStationaryProjector ∧
      fullActiveProjector * fullActiveProjector = fullActiveProjector ∧
      archiveProjector + fullStationaryProjector + fullActiveProjector = 1 ∧
      archiveProjector * fullStationaryProjector = 0 ∧
      archiveProjector * fullActiveProjector = 0 ∧
      fullStationaryProjector * archiveProjector = 0 ∧
      fullActiveProjector * archiveProjector = 0 ∧
      fullStationaryProjector * fullActiveProjector = 0 ∧
      fullActiveProjector * fullStationaryProjector = 0 := by
  have hArchive :
      archiveProjector * archiveProjector = archiveProjector := by
    unfold archiveProjector
    noncomm_ring [reynolds_idempotent]
  have hStationary :
      fullStationaryProjector * fullStationaryProjector =
        fullStationaryProjector := by
    unfold fullStationaryProjector
    rw [liftQuotient_mul, quotientStationaryProjector_idempotent]
  have hActive :
      fullActiveProjector * fullActiveProjector =
        fullActiveProjector := by
    unfold fullActiveProjector
    rw [liftQuotient_mul,
      D0.Synthesis.PhasonActiveSceneConjugacy.activeProjector_idempotent]
  have hComplete :
      archiveProjector + fullStationaryProjector + fullActiveProjector = 1 := by
    rw [add_assoc, reynolds_stationary_active_split]
    unfold archiveProjector
    noncomm_ring
  have hArchiveStationary :
      archiveProjector * fullStationaryProjector = 0 := by
    unfold archiveProjector fullStationaryProjector
    rw [Matrix.sub_mul, Matrix.one_mul,
      reynolds_mul_liftQuotient]
    simp
  have hArchiveActive :
      archiveProjector * fullActiveProjector = 0 := by
    unfold archiveProjector fullActiveProjector
    rw [Matrix.sub_mul, Matrix.one_mul,
      reynolds_mul_liftQuotient]
    simp
  have hStationaryArchive :
      fullStationaryProjector * archiveProjector = 0 := by
    unfold archiveProjector fullStationaryProjector
    rw [Matrix.mul_sub, Matrix.mul_one,
      liftQuotient_mul_reynolds]
    simp
  have hActiveArchive :
      fullActiveProjector * archiveProjector = 0 := by
    unfold archiveProjector fullActiveProjector
    rw [Matrix.mul_sub, Matrix.mul_one,
      liftQuotient_mul_reynolds]
    simp
  have hStationaryActive :
      fullStationaryProjector * fullActiveProjector = 0 := by
    unfold fullStationaryProjector fullActiveProjector
    rw [liftQuotient_mul,
      quotient_stationary_active_orthogonal.1, liftQuotient_zero]
  have hActiveStationary :
      fullActiveProjector * fullStationaryProjector = 0 := by
    unfold fullStationaryProjector fullActiveProjector
    rw [liftQuotient_mul,
      quotient_stationary_active_orthogonal.2, liftQuotient_zero]
  exact
    ⟨hArchive, hStationary, hActive, hComplete,
      hArchiveStationary, hArchiveActive, hStationaryArchive,
      hActiveArchive, hStationaryActive, hActiveStationary⟩

/-- Exact projector traces `(30,1,2)`. -/
theorem full_projector_traces :
    Matrix.trace archiveProjector = 30 ∧
      Matrix.trace fullStationaryProjector = 1 ∧
      Matrix.trace fullActiveProjector = 2 := by
  have hI33 :
      Matrix.trace (1 : Matrix Vertex33 Vertex33 ℚ) = 33 := by
    simp [Matrix.trace]
  have hReynolds : Matrix.trace reynolds = 3 := by
    change
      Matrix.trace D0.Claims.InvariantGenerationBridge.P = 3
    rw [D0.Claims.InvariantGenerationBridge.bridge_projector_eq]
    exact D0.Claims.InvariantGenerationBridge.q_trace_three
  have hActive :
      Matrix.trace
          D0.Synthesis.PhasonActiveSceneConjugacy.activeProjector = 2 := by
    rw [D0.Synthesis.PhasonActiveSceneConjugacy.activeProjector_closed_form]
    norm_num [Matrix.trace, Fin.sum_univ_succ]
  have hStationary :
      Matrix.trace quotientStationaryProjector = 1 := by
    unfold quotientStationaryProjector
    rw [Matrix.trace_sub, hActive]
    norm_num [Matrix.trace, Fin.sum_univ_succ]
  constructor
  · unfold archiveProjector
    rw [Matrix.trace_sub, hI33, hReynolds]
    norm_num
  constructor
  · unfold fullStationaryProjector
    rw [trace_liftQuotient, hStationary]
  · unfold fullActiveProjector
    rw [trace_liftQuotient, hActive]

/-! ## Exact active and stationary coordinates on the full scene -/

/-- Lift the owned active two-mode embedding to the literal 33-vertex scene. -/
def fullActiveEmbedding : Matrix Vertex33 Mode2 ℚ :=
  C * D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding

/-- Average to the quotient and apply the owned active retraction. -/
def fullActiveRetraction : Matrix Mode2 Vertex33 ℚ :=
  D0.Synthesis.PhasonActiveSceneConjugacy.activeRetraction * zoneAverage

/-- The full active embedding has an explicit left inverse. -/
theorem fullActiveRetraction_embedding :
    fullActiveRetraction * fullActiveEmbedding =
      (1 : Matrix Mode2 Mode2 ℚ) := by
  unfold fullActiveRetraction fullActiveEmbedding
  calc
    (D0.Synthesis.PhasonActiveSceneConjugacy.activeRetraction * zoneAverage) *
        (C * D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding) =
      D0.Synthesis.PhasonActiveSceneConjugacy.activeRetraction *
        (zoneAverage * C) *
          D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding := by
      simp only [Matrix.mul_assoc]
    _ = D0.Synthesis.PhasonActiveSceneConjugacy.activeRetraction *
        D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding := by
      rw [zoneAverage_indicator]
      simp only [Matrix.mul_one]
    _ = 1 := activeRetraction_mul_activeEmbedding

/-- The reverse composite is the canonical lifted active projector. -/
theorem fullActiveEmbedding_retraction :
    fullActiveEmbedding * fullActiveRetraction = fullActiveProjector := by
  unfold fullActiveEmbedding fullActiveRetraction fullActiveProjector
  calc
    (C * D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding) *
        (D0.Synthesis.PhasonActiveSceneConjugacy.activeRetraction * zoneAverage) =
      C *
        (D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding *
          D0.Synthesis.PhasonActiveSceneConjugacy.activeRetraction) *
            zoneAverage := by
      simp only [Matrix.mul_assoc]
    _ = liftQuotient
        D0.Synthesis.PhasonActiveSceneConjugacy.activeProjector := by
      rw [activeEmbedding_mul_activeRetraction]
      rfl

/-! ## Full literal dynamics -/

/-- The full random walk factors through orbit averaging and the normalized
zone transport.  No representative vertex is selected. -/
theorem fullTransport_reynolds_factorization :
    D0.Synthesis.SceneNormalizedQuotientDescent.fullTransport =
      C * D0.Spectral.zoneTransport * zoneAverage := by
  exact fullTransport_zoneTransport_factorization

/-- The full normalized Laplacian is identity on the archive plus the lifted
quotient Laplacian on the Reynolds image. -/
theorem fullNormalizedLaplacian_reynolds_decomposition :
    Lfull = archiveProjector + C * Lzone * zoneAverage := by
  rw [archiveProjector_eq_intrinsic]
  simpa [Lfull, C, Lzone, zoneAverage, intrinsicArchiveProjector,
    reconstructedNormalizedLaplacian_eq_one_sub_transport,
    reconstructedTransport_eq_zoneTransport,
    normalizedSceneLaplacian]
    using fullNormalizedLaplacian_intrinsic_decomposition

/-- The archive is the exact eigenvalue-one block, on both sides. -/
theorem archive_eigenvalue_one :
    Lfull * archiveProjector = archiveProjector ∧
      archiveProjector * Lfull = archiveProjector := by
  rw [archiveProjector_eq_intrinsic]
  exact intrinsicArchive_eigenvalue_one

theorem full_laplacian_intrinsic_intertwining :
    Lfull * C = C * Lzone := by
  change
    D0.Synthesis.SceneNormalizedQuotientDescent.fullNormalizedLaplacian *
        intrinsicIndicator =
      intrinsicIndicator * normalizedSceneLaplacian
  rw [intrinsicIndicator_eq_Cind31]
  simpa [normalizedSceneLaplacian,
    D0.Synthesis.SceneNormalizedQuotientDescent.quotientNormalizedLaplacian]
    using
      D0.Synthesis.SceneNormalizedQuotientDescent.full_laplacian_indicator_intertwining

theorem quotient_stationary_eigenvalue_zero :
    Lzone * quotientStationaryProjector = 0 ∧
      quotientStationaryProjector * Lzone = 0 := by
  unfold quotientStationaryProjector
  have h := normalizedSceneLaplacian_projector_support
  constructor
  · rw [Matrix.mul_sub, Matrix.mul_one, h.1, sub_self]
  · rw [Matrix.sub_mul, Matrix.one_mul, h.2, sub_self]

/-- The stationary line is the exact zero block, on both sides. -/
theorem stationary_eigenvalue_zero :
    Lfull * fullStationaryProjector = 0 ∧
      fullStationaryProjector * Lfull = 0 := by
  constructor
  · unfold fullStationaryProjector liftQuotient
    calc
      Lfull * (C * quotientStationaryProjector * zoneAverage) =
          (Lfull * C) * quotientStationaryProjector * zoneAverage := by
        simp only [Matrix.mul_assoc]
      _ = (C * Lzone) * quotientStationaryProjector * zoneAverage := by
        rw [full_laplacian_intrinsic_intertwining]
      _ = C * (Lzone * quotientStationaryProjector) * zoneAverage := by
        simp only [Matrix.mul_assoc]
      _ = 0 := by
        rw [quotient_stationary_eigenvalue_zero.1]
        simp
  · rw [fullNormalizedLaplacian_reynolds_decomposition]
    unfold fullStationaryProjector
    change
      liftQuotient quotientStationaryProjector *
        (archiveProjector + liftQuotient Lzone) = 0
    have hArchive :
        liftQuotient quotientStationaryProjector * archiveProjector = 0 := by
      unfold archiveProjector
      rw [Matrix.mul_sub, Matrix.mul_one, liftQuotient_mul_reynolds,
        sub_self]
    rw [Matrix.mul_add, hArchive,
      liftQuotient_mul, quotient_stationary_eigenvalue_zero.2,
      liftQuotient_zero, add_zero]

/-- The lifted active embedding intertwines the literal full Laplacian with
the owned two-mode `S_DE` transfer. -/
theorem full_active_sde_intertwining :
    Lfull * fullActiveEmbedding = fullActiveEmbedding * T₂ := by
  unfold fullActiveEmbedding
  calc
    Lfull *
        (C * D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding) =
      (Lfull * C) *
        D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding := by
          rw [Matrix.mul_assoc]
    _ = (C * Lzone) *
        D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding := by
          rw [full_laplacian_intrinsic_intertwining]
    _ = C *
        (Lzone *
          D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding) := by
          rw [Matrix.mul_assoc]
    _ = C *
        (D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding * T₂) := by
          rw [normalized_scene_sde_intertwining]
    _ = (C *
        D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding) * T₂ := by
          rw [Matrix.mul_assoc]

/-- **Exact full-scene block factorization.** -/
theorem fullNormalizedLaplacian_archive_sde_factorization :
    Lfull =
      archiveProjector +
        fullActiveEmbedding * T₂ * fullActiveRetraction := by
  rw [fullNormalizedLaplacian_reynolds_decomposition]
  congr 1
  unfold fullActiveEmbedding fullActiveRetraction
  calc
    C * Lzone * zoneAverage =
      C *
        (D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding *
          T₂ *
            D0.Synthesis.PhasonActiveSceneConjugacy.activeRetraction) *
              zoneAverage := by
        rw [normalizedSceneLaplacian_factorization]
    _ =
      (C * D0.Synthesis.PhasonActiveSceneConjugacy.activeEmbedding) *
        T₂ *
          (D0.Synthesis.PhasonActiveSceneConjugacy.activeRetraction *
            zoneAverage) := by
        simp only [Matrix.mul_assoc]

/-! ## Top-Hodge ownership of the active block -/

/-- The active coefficient in the full block is forced by the actual
top-Hodge spectral coordinates. -/
theorem topHodge_forces_full_active_coefficient :
    activeProductFromTopHodgeData 8 10 12 = 359 / 160 :=
  scene_activeProductFromTopHodgeData

/-- The active quadratic forced by top-Hodge data is exactly the
characteristic polynomial of the block used in the full factorization. -/
theorem topHodge_forces_full_active_characteristic (x : ℚ) :
    x ^ 2 - 3 * x +
        activeProductFromTopHodgeData 8 10 12 =
      D0.Cosmology.phasonFlipTransferCharacteristic x := by
  rw [topHodge_forces_full_active_coefficient]
  exact scene_activePolynomial_eq_ownedSDECharacteristic x

/-! ## Capstone -/

/-- **D0-AUTOMORPHISM-HODGE-SDE-DECOMPOSITION.**

One theorem packages the independent Reynolds construction, the exact
`30+1+2` projector split, the full literal dynamics, and the top-Hodge
ownership of the active coefficient.
-/
theorem automorphism_hodge_sde_decomposition :
    C * zoneAverage = reynolds ∧
      archiveProjector + fullStationaryProjector + fullActiveProjector = 1 ∧
      Matrix.trace archiveProjector = 30 ∧
      Matrix.trace fullStationaryProjector = 1 ∧
      Matrix.trace fullActiveProjector = 2 ∧
      Lfull * archiveProjector = archiveProjector ∧
      Lfull * fullStationaryProjector = 0 ∧
      Lfull * fullActiveEmbedding = fullActiveEmbedding * T₂ ∧
      Lfull =
        archiveProjector +
          fullActiveEmbedding * T₂ * fullActiveRetraction ∧
      activeProductFromTopHodgeData 8 10 12 = 359 / 160 :=
  ⟨indicator_zoneAverage_eq_reynolds,
    full_three_projectors.2.2.2.1,
    full_projector_traces.1,
    full_projector_traces.2.1,
    full_projector_traces.2.2,
    archive_eigenvalue_one.1,
    stationary_eigenvalue_zero.1,
    full_active_sde_intertwining,
    fullNormalizedLaplacian_archive_sde_factorization,
    topHodge_forces_full_active_coefficient⟩

end D0.Synthesis.AutomorphismHodgeSDEDecomposition
