import D0.Synthesis.EquivariantSeamNoGo
import D0.Dynamics.ToralAutomorphism
import D0.Core.FiniteTypes
import Mathlib.NumberTheory.Real.GoldenRatio
import Mathlib.Tactic

/-!
# The φ⁻¹² fork endgame: door 5 unstable, the two 12s unmergeable, the mechanism located

Row `D0-ALPHA-SEAM-FORM-FORCED-001`, obligation (i) — the single live obligation of the α-line
after (ii)'s adoption and (iii)'s decomposition — asks for an owner of the `φ⁻¹²` transport factor
in `φ⁻¹⁷ = ξ₅·φ⁻¹²`. Post-collapse the fork has four doors; this module carries the
machine-checkable content of the endgame. **No door is bound and no registry status changes**;
what changes is the shape of what remains.

**Step 1 — door 5 (`commutant 12`) is doubly unstable** (`door_five_unstable`). The door proposes
reading the transport depth off `dim Comm(Aut) = 12 = 3²+1+1+1`. But (i) adjoining the scene's own
transport operator cuts the commutant to `6 = 3+1+1+1` (`D0.Spectral.JointCommutant`) — a depth
read off an algebra that the dressed dynamics itself halves; and (ii) the equivariant class
carries **zero Feshbach seam** (`D0.Synthesis.EquivariantSeamNoGo.no_equivariant_seam`, restated
here) — a seam depth cannot be a dimension of an algebra in which no seam exists. Closure-negative
candidacy for the door is prepared in the campaign memo (owner-gated).

**Step 2 — the two 12s of doors 1 and 5 cannot be merged** (`twelve_profiles_differ`). Unlike
doors 3/4 (one carrier, `TransportTwelveForkCollapse`), `dim g_light = 12` and the commutant 12
have different invariant profiles: block partitions `8+3+1` vs `9+1+1+1`; centre dimensions
`1` (the `u(1)`) vs `4` (the `M₃` scalars plus three archive scalars); derived-subalgebra
dimensions `11` (`su(3)⊕su(2)`) vs `8` (`sl₃`). The tempting "both are 8+4" reading is trap (d)
and is vaccinated here: the profiles are recorded as unequal lists.

**Step 3 — the per-φ-power mechanism, located.** The memo's missing object is "a per-crossing
`φ⁻¹` contraction". Three owned facts pin where it can and cannot live:

* `stable_contraction_is_phi_inv` — the toral time generator's characteristic polynomial
  `x² + x − 1` (owned at matrix level, `T_charpoly_quadratic_relation`) has roots exactly
  `φ⁻¹` and `−φ`: **one tick of the toral flow contracts the stable line by exactly `φ⁻¹`**.
  The golden quadratic for `φ⁻¹` itself is prior Lean (`D0.Core.Phi.phi_inv_satisfies_primitive`,
  registered via `D0-IM-002`); NEW here is the wiring (Mathlib `goldenRatio` form, root
  exclusivity `toral_roots_factor`, the machine-checked matrix wire `toral_matrix_relation`, and
  the transport non-root instances). Note the ladder recursion polynomial `x² − x − 1`
  (`D0-IM-003`) is the RECIPROCAL of the toral `x² + x − 1`, not the same polynomial — the
  legitimate fold is through `rate_factor_eq_tick_weight` (row 390) plus the 583(ii) adoption,
  not through "same quadratic".
* `twelve_from_the_same_return` — the door-2 count is generated by that same fifth return:
  `L₅ = 11 = |V₁₁|` (`lucas 5 = 11` owned; `card V₁₁ = 11` owned), so `12 = L₅ + 1` — the `+1`
  sector left ANONYMOUS (`V₁₁ ⊔ {∗}`). Under the residual primitive (and only under it) the
  composition reads as tick arithmetic: `φ⁻⁵ · φ⁻¹² = φ⁻¹⁷` = seventeen ticks.
* `phi_inv_not_transport_root` / `neg_phi_not_transport_root` — neither `φ⁻¹` nor `−φ` is a root
  of the transport cubic `λ³ − 359λ − 2574`: self-contained instances of the `TransportNotGolden`
  `ℚ(√5)`-exclusion **on that cubic and nothing more** (its own retraction note forbids any wider
  "cannot reach" reading, and none is made here). Other scenic mechanism classes — the five
  named-open routes of `SceneNativeMultiscaleTower` and the row-583(iii) hyperbolic-seam-generator
  slot — remain open and are NOT excluded by this module.

**Net (scoped post-skeptic 2026-08-02).** The **door-2 route** of obligation (i) reduces to a
single named residual: **PRIM-SEAM-CROSSING-TICK-IDENTIFICATION** — the identification *one
sector crossing = one toral tick* on the door-2 carrier `V₁₁ ⊔ {∗}` (the `+1` sector is
anonymous: identifying it with the `V₁₃` witness of doors 3/4 would be trap (d) and is NOT done —
any such identification belongs inside the primitive). Door 1 (`dim g_light`) remains the live
rival, untouched by this module; door 5's closure is owner-gated candidacy. The multiplicative
"ticks" reading of the composition is CONDITIONAL on the primitive — the owned seam transport is
parabolic-additive (`SeamTransportLinear`: `N² = 0`, composition adds) and isometric in its own
turn dynamics, so unconditionally the seam has no per-crossing contraction at all. Refuting the
primitive re-opens the depth axis; it does not by itself yield a no-go.
-/

namespace D0.Synthesis.TransportForkEndgame

open Real
open scoped goldenRatio
open D0.Synthesis.EquivariantSeamNoGo
open D0.Spectral.DarkArchiveStructure

/-! ## Step 1: door 5 is doubly unstable -/

theorem door_five_unstable :
    (3 * 3 + 1 + 1 + 1 = 12) ∧ (3 + 1 + 1 + 1 = 6) ∧ (12 ≠ 6) ∧
    (∀ M : Fin 33 → Fin 33 → ℚ, Equivariant M →
      ∀ v, (∀ z, zoneSum v z = 0) → ∀ z, zoneSum (mulv M v) z = 0) ∧
    (∀ M : Fin 33 → Fin 33 → ℚ, Equivariant M →
      ∀ v, (∀ u w, zone u = zone w → v u = v w) →
        ∀ u w, zone u = zone w → mulv M v u = mulv M v w) :=
  ⟨by decide, by decide, by decide,
   fun M hM v hv z => (no_equivariant_seam M hM).1 v hv z,
   fun M hM v hv u w h => (no_equivariant_seam M hM).2 v hv u w h⟩

/-! ## Step 2: the two 12s have different invariant profiles -/

theorem twelve_profiles_differ :
    (8 + 3 + 1 = 12) ∧ (9 + 1 + 1 + 1 = 12) ∧
    ([8, 3, 1] ≠ ([9, 1, 1, 1] : List ℕ)) ∧
    (1 ≠ 4) ∧          -- centre dimensions: u(1) vs M₃-scalar + three archive scalars
    (11 ≠ 8) := by      -- derived dimensions: su(3)⊕su(2) vs sl₃
  refine ⟨by decide, by decide, by decide, by decide, by decide⟩

/-! ## Step 3: the mechanism — owned parts -/

/-- `φ⁻¹ = φ − 1`, the defining identity in inverse form. -/
theorem phi_inv_eq : φ⁻¹ = φ - 1 :=
  inv_eq_of_mul_eq_one_right (by linear_combination goldenRatio_sq)

/-- **The stable root.** `φ⁻¹` satisfies the toral characteristic relation `x² + x − 1 = 0`:
one tick of the toral flow contracts the stable line by exactly `φ⁻¹`. -/
theorem stable_contraction_is_phi_inv : (φ⁻¹) ^ 2 + φ⁻¹ - 1 = 0 := by
  rw [phi_inv_eq]
  nlinarith [goldenRatio_sq]

/-- The other root is `−φ` — the expanding direction, `|−φ| = φ` the owned rate. -/
theorem unstable_root_is_neg_phi : (-φ) ^ 2 + (-φ) - 1 = 0 := by
  nlinarith [goldenRatio_sq]

/-- These are the only two roots: the quadratic factors through them. -/
theorem toral_roots_factor (x : ℝ) :
    x ^ 2 + x - 1 = (x - φ⁻¹) * (x + φ) := by
  rw [phi_inv_eq]
  nlinarith [goldenRatio_sq, sq_nonneg (x - φ + 1), sq_nonneg (x + φ)]

/-- **The count from the same return**: `lucas 5 = 11 = |V₁₁|`, so the door-2 object is
`12 = L₅ + 1` — generated by the very return that owns `ξ₅ = φ⁻⁵`. -/
theorem twelve_from_the_same_return :
    D0.Dynamics.lucas 5 = 11 ∧ Fintype.card (D0.V11 : Type) = 11 ∧ 11 + 1 = 12 :=
  ⟨by decide, D0.card_v11, by decide⟩

/-- Exponent arithmetic (`pow_add`): IF the residual primitive holds, the composition reads as
seventeen ticks. Unconditionally this is arithmetic of the number `φ⁻¹`, nothing about the seam
(whose owned transport is parabolic-additive, not multiplicative). -/
theorem seventeen_ticks : (φ⁻¹) ^ 5 * (φ⁻¹) ^ 12 = (φ⁻¹) ^ 17 := by
  rw [← pow_add]

/-- The matrix-level source of the quadratic: the owned toral relation, restated so the wire is
machine-checked, not a docstring citation. (Axiom note: inherits `ofReduceBool` from the owned
module's `native_decide`; kept OUT of the assembled theorem below.) -/
theorem toral_matrix_relation : D0.Dynamics.T ^ 2 + D0.Dynamics.T - 1 = 0 :=
  D0.Dynamics.T_charpoly_quadratic_relation

/-- The 17-tick toral invariant: `Tr(T¹⁷) = −L₁₇ = −3571`, via the owned signed-Lucas trace law —
the composed depth exponent `17 = 5 + 12` has a concrete toral address, exactly as the `ξ₅`
return has `|Tr(T⁵)| = L₅ = 11`. -/
theorem trace_T17 : Matrix.trace (D0.Dynamics.T ^ 17) = -3571 := by
  rw [D0.Dynamics.trace_T_pow_eq_signed_lucas]
  decide

/-- `φ³ = 2φ + 1`, for the root evaluations. -/
theorem phi_cubed : φ ^ 3 = 2 * φ + 1 := by
  have hsq := goldenRatio_sq
  nlinarith [hsq]

/-- **`φ⁻¹` is not a transport eigenvalue**: it misses the transport cubic by `−357φ − 2218 ≠ 0`. -/
theorem phi_inv_not_transport_root : (φ⁻¹) ^ 3 - 359 * φ⁻¹ - 2574 ≠ 0 := by
  rw [phi_inv_eq]
  intro h
  have hexp : (φ - 1) ^ 3 - 359 * (φ - 1) - 2574 = -357 * φ - 2218 := by
    linear_combination phi_cubed - 3 * goldenRatio_sq
  rw [hexp] at h
  have := goldenRatio_pos
  linarith

/-- **`−φ` is not a transport eigenvalue either**: the miss is `357φ − 2575 ≠ 0` since `φ < 2`. -/
theorem neg_phi_not_transport_root : (-φ) ^ 3 - 359 * (-φ) - 2574 ≠ 0 := by
  intro h
  have hexp : (-φ) ^ 3 - 359 * (-φ) - 2574 = 357 * φ - 2575 := by
    linear_combination -1 * phi_cubed
  rw [hexp] at h
  have hlt : φ < 2 := by nlinarith [goldenRatio_sq, goldenRatio_pos]
  linarith

/-- **Assembled.** Door 5 doubly unstable; the two 12s unmergeable; the `φ⁻¹`-per-tick mechanism
owned on the toral side and impossible on the scenic side; the door-2 count generated by the
`ξ₅` return; the composition = seventeen ticks. -/
theorem transport_fork_endgame :
    ((3 * 3 + 1 + 1 + 1 = 12) ∧ (3 + 1 + 1 + 1 = 6)) ∧
    ([8, 3, 1] ≠ ([9, 1, 1, 1] : List ℕ)) ∧
    ((φ⁻¹) ^ 2 + φ⁻¹ - 1 = 0) ∧
    (D0.Dynamics.lucas 5 = 11 ∧ Fintype.card (D0.V11 : Type) = 11) ∧
    ((φ⁻¹) ^ 5 * (φ⁻¹) ^ 12 = (φ⁻¹) ^ 17) ∧
    ((φ⁻¹) ^ 3 - 359 * φ⁻¹ - 2574 ≠ 0 ∧ (-φ) ^ 3 - 359 * (-φ) - 2574 ≠ 0) := by
  refine ⟨⟨by decide, by decide⟩, by decide, stable_contraction_is_phi_inv,
    ⟨twelve_from_the_same_return.1, twelve_from_the_same_return.2.1⟩,
    seventeen_ticks, ⟨phi_inv_not_transport_root, neg_phi_not_transport_root⟩⟩

end D0.Synthesis.TransportForkEndgame
