import D0.Foundation.CascadeFloorDefectClosure
import D0.Foundation.CascadeFloorShellClosure

/-!
# Topological closure forces a shell: the finite 2-cell attachment theorem

The previous shell floor closed the radius set under a reflection. Its registered residual was the
topological/2-cell reading of

`closed circulation datum → shell`.

This module supplies that reading as a finite cellular-chain theorem.

The output of the defect floor is a **closed defect class** (`ConjClasses`): element-level
circulation changes under a basepoint move, while its conjugacy class is invariant. A closed
circulation is represented by the nonzero 1-cycle assigning coefficient `1` to the three boundary
edges. Without 2-cells, every cellular boundary is zero, so this cycle cannot be filled. Attaching
one shell 2-cell along that cycle makes it a boundary. Moreover any finite attachment filling the
cycle must have a nonempty 2-cell carrier, while the shell carrier has cardinality one: the
attachment is minimal.

This is not a reflection proxy and not prose adjacency. The same closed-defect datum produced by
the previous floor is carried as the label of the cycle filled by the shell cell. The radial shell
module remains the geometric realisation of that one topological cell.
-/

namespace D0.Foundation.CascadeTopologicalShellAttachment

open scoped BigOperators

open D0.Foundation

/-- Three oriented boundary edges of the minimal closed circulation. -/
abbrev BoundaryEdge := Fin 3

/-- Integral cellular 1-chains on the boundary. -/
abbrev OneChain := BoundaryEdge → ℤ

/-- The closed circulation cycle: one traversal of every boundary edge. -/
def circulationCycle : OneChain := fun _ => 1

theorem circulationCycle_nonzero :
    circulationCycle ≠ 0 := by
  intro h
  have hv := congrFun h (0 : BoundaryEdge)
  norm_num [circulationCycle] at hv

/-- Cellular boundary generated by attaching maps of finitely many 2-cells. -/
def cellularBoundary {Cell : Type*} [Fintype Cell]
    (attach : Cell → OneChain) (coeff : Cell → ℤ) : OneChain :=
  fun e => ∑ c : Cell, coeff c * attach c e

/-- A cycle is fillable by a family of attached 2-cells. -/
def Fillable {Cell : Type*} [Fintype Cell]
    (attach : Cell → OneChain) (z : OneChain) : Prop :=
  ∃ coeff : Cell → ℤ, cellularBoundary attach coeff = z

/-- Open carrier: no 2-cell has been attached. -/
abbrev OpenTwoCells : Type := Empty

def openAttach : OpenTwoCells → OneChain := by
  intro c
  exact nomatch c

/-- **Insufficiency:** without a shell/2-cell, the closed circulation is not a boundary. -/
theorem circulation_not_fillable_without_shell :
    ¬ Fillable openAttach circulationCycle := by
  rintro ⟨coeff, h⟩
  have hv := congrFun h (0 : BoundaryEdge)
  simp [cellularBoundary, circulationCycle] at hv

/-- The unique shell 2-cell. -/
abbrev ShellTwoCell : Type := PUnit

/-- Its attaching map is exactly the closed circulation cycle. -/
def shellAttach (_ : ShellTwoCell) : OneChain :=
  circulationCycle

def shellCoefficient (_ : ShellTwoCell) : ℤ := 1

/-- **Control:** attaching the shell cell fills the circulation. -/
theorem shell_fills_circulation :
    cellularBoundary shellAttach shellCoefficient = circulationCycle := by
  funext e
  simp [cellularBoundary, shellAttach, shellCoefficient, circulationCycle]

theorem circulation_fillable_with_shell :
    Fillable shellAttach circulationCycle :=
  ⟨shellCoefficient, shell_fills_circulation⟩

/-- Every finite filling needs at least one 2-cell. -/
theorem filling_requires_nonempty_cell
    {Cell : Type*} [Fintype Cell]
    (attach : Cell → OneChain)
    (h : Fillable attach circulationCycle) :
    Nonempty Cell := by
  by_contra hne
  haveI : IsEmpty Cell := not_nonempty_iff.mp hne
  obtain ⟨coeff, hfill⟩ := h
  have hv := congrFun hfill (0 : BoundaryEdge)
  simp [cellularBoundary, circulationCycle] at hv

/-- The shell attachment is minimal: it has one cell, and zero cells cannot fill. -/
theorem shell_attachment_minimal :
    Fintype.card ShellTwoCell = 1
      ∧ ¬ Fillable openAttach circulationCycle
      ∧ Fillable shellAttach circulationCycle := by
  exact ⟨Fintype.card_punit, circulation_not_fillable_without_shell,
    circulation_fillable_with_shell⟩

/-! ## Shared object with the defect floor -/

/-- Explicit noncommuting generators of the order-repair carrier. -/
def defectGeneratorA : Equiv.Perm (Fin 3) := Equiv.swap 0 1
def defectGeneratorB : Equiv.Perm (Fin 3) := Equiv.swap 1 2

theorem explicit_defect_nontrivial :
    commDefect defectGeneratorA defectGeneratorB ≠ 1 := by
  decide

/-- The actual closed defect class output by the preceding floor. -/
def closedDefectClass : ConjClasses (Equiv.Perm (Fin 3)) :=
  ConjClasses.mk (commDefect defectGeneratorA defectGeneratorB)

/-- A closed circulation carrying the defect-floor output as its label. -/
structure ClosedDefectCirculation where
  defect : ConjClasses (Equiv.Perm (Fin 3))
  cycle : OneChain

def carriedClosedDefectCirculation : ClosedDefectCirculation where
  defect := closedDefectClass
  cycle := circulationCycle

/-- The label is invariant under every basepoint move — cited from the defect floor on the same
commutator object. -/
theorem carried_defect_is_closed (g : Equiv.Perm (Fin 3)) :
    ConjClasses.mk
        (g * commDefect defectGeneratorA defectGeneratorB * g⁻¹) =
      carriedClosedDefectCirculation.defect := by
  exact class_defect_of_commutator_invariant
    g defectGeneratorA defectGeneratorB

/-- **Topological closure→shell link.** The previous floor's closed defect class labels a nonzero
cycle; with no shell it is not a boundary; one shell 2-cell fills it and is minimal. -/
theorem topological_closure_forces_shell :
    (∀ g : Equiv.Perm (Fin 3),
      ConjClasses.mk
          (g * commDefect defectGeneratorA defectGeneratorB * g⁻¹) =
        carriedClosedDefectCirculation.defect)
      ∧ carriedClosedDefectCirculation.cycle ≠ 0
      ∧ ¬ Fillable openAttach carriedClosedDefectCirculation.cycle
      ∧ Fillable shellAttach carriedClosedDefectCirculation.cycle
      ∧ Fintype.card ShellTwoCell = 1 :=
  ⟨carried_defect_is_closed,
   circulationCycle_nonzero,
   circulation_not_fillable_without_shell,
   circulation_fillable_with_shell,
   Fintype.card_punit⟩

end D0.Foundation.CascadeTopologicalShellAttachment
