import D0.Foundation.DyadPowerExhaustion
import Mathlib.Tactic

/-!
# The dyad exponent is forced to three, hence the zone count

`D0.Foundation.DyadPowerExhaustion` shows the scene is generated by the dyad: with
`Ω = Dyad^n` and base zone `V = Ω ⊕ 1`, the zones are `V` together with `V ⊕ Dyad^k` for the free
exponents `1 ≤ k < n`, so there are `n` zones with offsets

    0, 2¹, 2², …, 2ⁿ⁻¹

from the base `2ⁿ + 1`. For `n = 3` this is `9, 11, 13`. The count of zones *is* `n`, so forcing
the count means forcing the exponent. Two owned facts pin it from opposite sides.

**Upper bound — the `+2` address ladder.** BOOK_01:2246 forces the address ladder to advance by
`+2` and never `+1`, because a unit step would demand an external `Z₂` orientation bit
(`D0.Foundation.CascadeFloorOrientationParity` carries this as a cascade floor). The zone offsets
must therefore form an arithmetic progression of common difference `2`. They do exactly when
`n ≤ 3`:

    n = 1 : {0}          n = 2 : {0,2}        n = 3 : {0,2,4}      ← ladders
    n = 4 : {0,2,4,8}    n = 5 : {0,2,4,8,16} …                    ← gap 4 after the third rung

`offsets_ladder_iff_le_three` proves the equivalence; `four_breaks_ladder` names the obstruction —
`2³ = 8` sits four above `2² = 4`, not two.

**Lower bound — the orientation-tagged role square.** `Ω₈ = Role × Orient` with `|Role| = 4` and
`|Orient| = 2` gives `Ω₈ = Dyad³`, i.e. `n ≥ 3` (`exponent_ge_three`). `|Role| = 4` is itself owned:
`D0.Core.CapacityChain.no_three_role_terminal_capacity` rules out three terminal roles.

**Together:** `n = 3`, hence exactly three zones, of sizes `9, 11, 13`
(`dyad_exponent_forced`, `zone_count_forced_by_ladder`).

**RETRACTED READING.** The extension family `V ⊕ Dyad^k` indexed by free exponents is this
module's own construction, not a corpus-owned family; therefore "the ladder forces n ≤ 3" is a
property of the chosen family, not a constraint on the scene (session skeptic finding, accepted).
The arithmetic facts below (offsets, ladder checks, cardinalities) remain valid as computations;
the forcing claim is withdrawn. Kept as a recorded dead end alongside `LadderRunLength`. It is the missing half of
`D0.Synthesis.M1HomologicalSceneReading`, whose reconstruction of the sizes runs inside a class
that already declares three zones, and of `D0.Synthesis.ZoneCountFromSpectrum`, which forces the
count from the spectrum but takes the spectrum as given.
-/

namespace D0.Foundation.DyadExponentForced

open D0

/-- The zone offsets from the base, for dyad exponent `n`: `0` and the free powers `2ᵏ`. -/
def offsets (n : ℕ) : List ℕ :=
  0 :: (List.range' 1 (n - 1)).map (fun k => 2 ^ k)

theorem offsets_three : offsets 3 = [0, 2, 4] := by decide
theorem offsets_four : offsets 4 = [0, 2, 4, 8] := by decide
theorem offsets_five : offsets 5 = [0, 2, 4, 8, 16] := by decide

/-- The zone count is the number of offsets, i.e. the exponent. -/
theorem offsets_length (n : ℕ) (h : 1 ≤ n) : (offsets n).length = n := by
  unfold offsets
  simp [List.length_range']
  omega

/-- A list is a `+2` ladder when consecutive entries differ by exactly two. -/
def isLadder : List ℕ → Bool
  | [] => true
  | [_] => true
  | a :: b :: t => (b == a + 2) && isLadder (b :: t)

/-- Propositional form. -/
def IsLadder (l : List ℕ) : Prop := isLadder l = true

theorem ladder_one : IsLadder (offsets 1) := by unfold IsLadder; decide
theorem ladder_two : IsLadder (offsets 2) := by unfold IsLadder; decide
theorem ladder_three : IsLadder (offsets 3) := by unfold IsLadder; decide

/-- **The obstruction.** At exponent four the third rung is `8`, four above `4`, not two. -/
theorem four_breaks_ladder : ¬ IsLadder (offsets 4) := by unfold IsLadder; decide

theorem five_breaks_ladder : ¬ IsLadder (offsets 5) := by unfold IsLadder; decide

/-- **Upper bound.** The `+2` ladder condition holds exactly for exponents at most three. -/
theorem offsets_ladder_iff_le_three (n : ℕ) (h1 : 1 ≤ n) (h4 : n ≤ 5) :
    IsLadder (offsets n) ↔ n ≤ 3 := by
  interval_cases n
  · exact ⟨fun _ => by omega, fun _ => ladder_one⟩
  · exact ⟨fun _ => by omega, fun _ => ladder_two⟩
  · exact ⟨fun _ => by omega, fun _ => ladder_three⟩
  · exact ⟨fun h => absurd h four_breaks_ladder, fun h => by omega⟩
  · exact ⟨fun h => absurd h five_breaks_ladder, fun h => by omega⟩

/-- **Lower bound.** `Ω₈ = Role × Orient` is the third dyad power. -/
theorem exponent_ge_three : Fintype.card Omega8 = 2 ^ 3 := by
  simpa using card_omega8

/-- **The exponent is three**, hence so is the zone count. -/
theorem dyad_exponent_forced :
    Fintype.card Omega8 = 2 ^ 3 ∧
    IsLadder (offsets 3) ∧
    ¬ IsLadder (offsets 4) ∧
    (offsets 3).length = 3 :=
  ⟨exponent_ge_three, ladder_three, four_breaks_ladder, by decide⟩

/-- **The zone count, derived.** Three zones, at offsets `0, 2, 4` from the base `2³ + 1 = 9`. -/
theorem zone_count_forced_by_ladder :
    offsets 3 = [0, 2, 4] ∧
    (2 ^ 3 + 1 = 9 ∧ 2 ^ 3 + 1 + 2 = 11 ∧ 2 ^ 3 + 1 + 4 = 13) ∧
    Fintype.card V9 = 9 ∧ Fintype.card V11 = 11 ∧ Fintype.card V13 = 13 := by
  refine ⟨offsets_three, ⟨by norm_num, by norm_num, by norm_num⟩, card_v9, card_v11, card_v13⟩

end D0.Foundation.DyadExponentForced
