import Mathlib.Tactic
import D0.Core.BornFiniteEffects

namespace D0

/--
A finite two-component amplitude atom.  The two coordinates are the real and
phase-quadrature components of the same detector channel.  D0 does not attach a
probability to the amplitude directly; it first extracts a phase-blind positive
quadratic response.
-/
structure PhaseAmplitude where
  re : ℚ
  im : ℚ

/-- The quarter-turn phase action `(re, im) ↦ (-im, re)`. -/
def phaseQuarterTurn (z : PhaseAmplitude) : PhaseAmplitude where
  re := -z.im
  im := z.re

/-- Squared detector norm of a finite amplitude atom. -/
def amplitudeNormSq (z : PhaseAmplitude) : ℚ :=
  z.re * z.re + z.im * z.im

/-- A general finite quadratic response on one two-component amplitude channel. -/
structure PhaseQuadraticResponse where
  xx : ℚ
  xy : ℚ
  yy : ℚ

/-- Evaluation of a general quadratic response. -/
def phaseQuadraticEval (Q : PhaseQuadraticResponse) (z : PhaseAmplitude) : ℚ :=
  Q.xx * z.re * z.re + Q.xy * z.re * z.im + Q.yy * z.im * z.im

/-- Phase blindness at the finite detector level: a quarter-turn of the internal
phase quadrature cannot change the raw response. -/
def QuarterTurnInvariant (Q : PhaseQuadraticResponse) : Prop :=
  ∀ z, phaseQuadraticEval Q z = phaseQuadraticEval Q (phaseQuarterTurn z)

/-- The mixed term of a phase-blind quadratic response vanishes. -/
theorem quarter_turn_invariant_forces_no_mixed_term
    (Q : PhaseQuadraticResponse) (hQ : QuarterTurnInvariant Q) : Q.xy = 0 := by
  let z : PhaseAmplitude := { re := 1, im := 1 }
  have h := hQ z
  change Q.xx * (1:ℚ) * (1:ℚ) + Q.xy * (1:ℚ) * (1:ℚ) + Q.yy * (1:ℚ) * (1:ℚ) =
      Q.xx * (-(1:ℚ)) * (-(1:ℚ)) + Q.xy * (-(1:ℚ)) * (1:ℚ) + Q.yy * (1:ℚ) * (1:ℚ) at h
  ring_nf at h ⊢
  linarith

/-- The two diagonal coefficients of a phase-blind quadratic response coincide. -/
theorem quarter_turn_invariant_forces_equal_diagonal
    (Q : PhaseQuadraticResponse) (hQ : QuarterTurnInvariant Q) : Q.xx = Q.yy := by
  let z : PhaseAmplitude := { re := 1, im := 0 }
  have h := hQ z
  change Q.xx * (1:ℚ) * (1:ℚ) + Q.xy * (1:ℚ) * (0:ℚ) + Q.yy * (0:ℚ) * (0:ℚ) =
      Q.xx * (-(0:ℚ)) * (-(0:ℚ)) + Q.xy * (-(0:ℚ)) * (1:ℚ) + Q.yy * (1:ℚ) * (1:ℚ) at h
  simpa using h

/--
Finite phase-blind quadratic response theorem.
A quadratic detector response on one finite two-component amplitude channel that
is blind to the internal quarter-turn phase is not a free quadratic form: it is a
single scalar multiple of the squared norm.  With unit detector calibration this
is exactly `D†D` on the finite channel.
-/
theorem phase_blind_quadratic_response_is_norm_sq_scaled
    (Q : PhaseQuadraticResponse) (hQ : QuarterTurnInvariant Q) :
    ∀ z, phaseQuadraticEval Q z = Q.xx * amplitudeNormSq z := by
  intro z
  have hxy : Q.xy = 0 := quarter_turn_invariant_forces_no_mixed_term Q hQ
  have hdiag : Q.yy = Q.xx := (quarter_turn_invariant_forces_equal_diagonal Q hQ).symm
  unfold phaseQuadraticEval amplitudeNormSq
  rw [hxy, hdiag]
  ring

/-- Unit-calibrated finite phase-blind quadratic response. -/
structure UnitPhaseQuadraticResponse where
  response : PhaseQuadraticResponse
  quarter_turn_invariant : QuarterTurnInvariant response
  unit_calibrated : response.xx = 1

/--
Born quadratic-response closure: after unit calibration, a finite phase-blind
quadratic response is exactly the squared detector norm.  This is the finite D0
content of the usual `D†D` response before probability normalization.
-/
theorem unit_phase_blind_quadratic_response_is_norm_sq
    (Q : UnitPhaseQuadraticResponse) :
    ∀ z, phaseQuadraticEval Q.response z = amplitudeNormSq z := by
  intro z
  have h := phase_blind_quadratic_response_is_norm_sq_scaled Q.response Q.quarter_turn_invariant z
  rw [Q.unit_calibrated] at h
  simpa using h

/-- A finite family of amplitude channels over an outcome/state grid. -/
structure FiniteAmplitudeEffectFrame (ι σ : Type) [Fintype ι] [Fintype σ] where
  amp : ι → σ → PhaseAmplitude
  total_norm_positive : 0 < ∑ i, ∑ s, amplitudeNormSq (amp i s)

/-- The finite quadratic response generated by amplitudes is the sum of squared norms. -/
def finiteAmplitudeResponse {ι σ : Type} [Fintype ι] [Fintype σ]
    (A : FiniteAmplitudeEffectFrame ι σ) (i : ι) : ℚ :=
  ∑ s, amplitudeNormSq (A.amp i s)

/-- Squared norms are nonnegative over rationals. -/
theorem amplitude_norm_sq_nonnegative (z : PhaseAmplitude) : 0 ≤ amplitudeNormSq z := by
  unfold amplitudeNormSq
  nlinarith [sq_nonneg z.re, sq_nonneg z.im]

/-- Amplitude-generated responses are nonnegative. -/
theorem finite_amplitude_response_nonnegative {ι σ : Type} [Fintype ι] [Fintype σ]
    (A : FiniteAmplitudeEffectFrame ι σ) (i : ι) :
    0 ≤ finiteAmplitudeResponse A i := by
  unfold finiteAmplitudeResponse
  exact Finset.sum_nonneg (fun s _ => amplitude_norm_sq_nonnegative (A.amp i s))

/-- A finite amplitude frame induces the finite positive response used by Born normalization. -/
def finiteAmplitudePositiveResponse {ι σ : Type} [Fintype ι] [Fintype σ]
    (A : FiniteAmplitudeEffectFrame ι σ) : FinitePositiveResponse ι where
  response := finiteAmplitudeResponse A
  nonnegative := finite_amplitude_response_nonnegative A
  total_positive := by
    simpa [finiteResponseTotal, finiteAmplitudeResponse] using A.total_norm_positive

/-- Born weight of a finite amplitude-generated response. -/
def finiteAmplitudeBornWeight {ι σ : Type} [Fintype ι] [Fintype σ]
    (A : FiniteAmplitudeEffectFrame ι σ) (i : ι) : ℚ :=
  finiteResponseBornWeight (finiteAmplitudePositiveResponse A) i

/-- Candidate readout for a finite amplitude frame. -/
abbrev FiniteAmplitudeBornReadout {ι σ : Type} [Fintype ι] [Fintype σ]
    (A : FiniteAmplitudeEffectFrame ι σ) :=
  FiniteBornReadout (finiteAmplitudePositiveResponse A)

/--
Full finite Born closure for D0 amplitude frames: phase blindness forces the raw
quadratic response to be squared norm (`D†D`), and the finite Born theorem then
forces the probability readout to be normalized squared norm.  No additional
probability law remains at the same finite detector stage.
-/
theorem finite_amplitude_born_readout_unique {ι σ : Type} [Fintype ι] [Fintype σ]
    (A : FiniteAmplitudeEffectFrame ι σ) (q : FiniteAmplitudeBornReadout A) :
    ∀ i, q.probability i = finiteAmplitudeBornWeight A i := by
  intro i
  exact finite_born_readout_unique_on_finite_outcomes (finiteAmplitudePositiveResponse A) q i

/-- Any alleged non-Born readout on an amplitude-generated detector frame fails. -/
theorem finite_amplitude_born_no_alternative {ι σ : Type} [Fintype ι] [Fintype σ]
    (A : FiniteAmplitudeEffectFrame ι σ) (q : FiniteAmplitudeBornReadout A)
    (hneq : ∃ i, q.probability i ≠ finiteAmplitudeBornWeight A i) : False := by
  rcases hneq with ⟨i, hi⟩
  exact hi (finite_amplitude_born_readout_unique A q i)

end D0
