#!/usr/bin/env python3
"""attack_higgs_w1_check - FORGE can-fail check (memo-only, no registry, no 053040).

Tests the THESIS of ATTACK_HIGGS_W1_DEGREE2_MEMO.md by EXECUTION:

  W1  (the Higgs commutativity wall)  =  "OWNED idempotent on the T-carrier => commutes with T"
      is a COROLLARY of  P-DEGREE2-EXHAUSTION / P-ABELIAN, because the present-core is the
      degree-2 COMMUTATIVE algebra  ZMod44[T] = {a*1 + b*T}  (min-poly of T is quadratic
      T^2+T-1=0), in which every idempotent is a spectral projection = a polynomial in T,
      hence commutes with T.

Exact integer arithmetic mod 44 (no float on any load-bearing fact).  Base checks PASS (rc=0);
each mutant MUST kill (rc=1) when a load-bearing datum is broken.

Carrier facts, read off the OWNED Lean on disk:
  * T = !![0,1;1,-1] over ZMod 44   (HiggsReturnQuotientAction.lean:20), toral order 30.
  * min-poly of T is quadratic: T^2 + T - 1 = 0  =>  present-core has degree 2
        (matches D0-P-DEGREE2-EXHAUSTION-001 / the row-257 degree-2 exhaustion).
  * present-core class = {a*1 + b*T}  = ZMod44[T]  (tPoly_commutes,
        HiggsCondensationPresentCoreMaximalityNoGo.lean:27-29; def BOOK_04:1637), COMMUTATIVE.
  * owned frozen SU(2): FrozenSU2_X=!![0,1;1,0], FrozenSU2_Z=!![1,0;0,-1] over Q
        (HiggsScalarProjectorConstructive.lean:32,35) -- INVOLUTIONS, not idempotents.
  * mesonSupportProjector : owned diagonal idempotent, but on the OFF-carrier
        Matrix(MesonCarrier E Gen) Rat  (MesonDefectTransferAlgebra.lean:23-25) -- NOT 2x2/ZMod44,
        so "commutes with T" is untyped for it: it is off-carrier, out of W1's scope.
"""
import sys
import itertools
from fractions import Fraction

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

M = 44
FAILS = []


def check(name, cond):
    ok = bool(cond)
    print(("PASS " if ok else "FAIL ") + name)
    if not ok:
        FAILS.append(name)
    return ok


# ---- 2x2 integer-matrix helpers mod M ------------------------------------
def matmul(A, B):
    return tuple(
        sum(A[2 * r + k] * B[2 * k + c] for k in range(2)) % M
        for r in range(2) for c in range(2)
    )


def add(A, B):
    return tuple((A[k] + B[k]) % M for k in range(4))


def sub(A, B):
    return tuple((A[k] - B[k]) % M for k in range(4))


def smul(s, A):
    return tuple((s * A[k]) % M for k in range(4))


def commute(A, B):
    return matmul(A, B) == matmul(B, A)


def is_idem(A):
    return matmul(A, A) == A


def is_invol(A):
    return matmul(A, A) == I


I = (1, 0, 0, 1)
ZERO = (0, 0, 0, 0)


def make(mutate=None):
    """Owned named carrier objects.  `mutate` toggles a load-bearing datum."""
    T = (0, 1, 1, (-1) % M)
    X = (0, 1, 1, 0)          # FrozenSU2_X (Pauli-X)
    Z = (1, 0, 0, (-1) % M)   # FrozenSU2_Z (Pauli-Z)
    if mutate == "break_degree2":
        # T -> a scalar: present-core collapses to {a*1}, degree 1, NO nontrivial spectral
        # projection distinct from 0/I; the degree-2 mechanism (2 distinct eigen-branches,
        # 8 idempotents) is what makes W1 nontrivially T-specific -> this must break R2/R4.
        T = (3, 0, 0, 3)
    if mutate == "break_core_class":
        # present-core generated by a NON-polynomial-in-T object (X): the class is no longer
        # ZMod44[T]; commuting-idempotent<=>core equivalence (R5) must fail.
        pass  # handled in present_core() via `gen`
    if mutate == "break_frozen_x":
        # pretend FrozenSU2_X is the non-core idempotent diag(1,0): then an OWNED named object is
        # simultaneously idempotent AND non-commuting with T -> the three-property trap (R6) breaks
        # (all three legs realised by one owned object).  Verifies R6 is a real gate.
        X = (1, 0, 0, 0)
    if mutate == "break_owned_idem_offcarrier":
        # inject a hand-picked NON-CORE idempotent diag(1,0) into the OWNED on-carrier set as
        # if it were owned/frozen: the crux "owned on-carrier idempotents subset core" (R7)
        # must then fail -> the kill is genuinely gated on owned-on-carrier ⊆ core.
        pass  # handled in owned_oncarrier() via flag
    return T, X, Z


def present_core(T, gen=None):
    """All {a*1 + b*G} mod M, G=T by default (= ZMod44[T]).  gen overrides the generator."""
    G = T if gen is None else gen
    out = set()
    for a in range(M):
        for b in range(M):
            out.add(add(smul(a, I), smul(b, G)))
    return out


# =========================================================================
def run(mutate=None):
    global FAILS
    FAILS = []
    tag = mutate or "BASE"
    print(f"===== attack_higgs_w1_check  [{tag}] =====")
    T, X, Z = make(mutate)

    # ---- R1 : T has toral order 30 (return operator, not period-44). --------------
    if mutate != "break_degree2":
        P = I
        order = None
        for n in range(1, 100):
            P = matmul(P, T)
            if P == I:
                order = n
                break
        check("R1_T_order_is_30_return_operator", order == 30)

    # ---- R2 : min-poly of T is QUADRATIC:  T^2 + T - 1 = 0  (degree-2 carrier). -----
    #   This is the P-DEGREE2-EXHAUSTION root: the algebra ZMod44[T] closes at degree 2
    #   (T^2 = -T + 1), so higher powers reduce into span{1,T} -- exactly p^3 in span{1,p}.
    T2 = matmul(T, T)
    min_poly_quadratic = add(add(T2, T), smul((-1) % M, I)) == ZERO
    check("R2_min_poly_of_T_is_quadratic (T^2+T-1=0 => degree-2 present-core)",
          min_poly_quadratic)
    # and T^3 reduces into span{1,T}  (the p^3-in-span{1,p} exhaustion, T-carrier form):
    #   T^3 = T*(1-T) = T - T^2 = T - (1-T) = 2T - 1.
    T3 = matmul(T2, T)
    t3_reduces = (T3 == sub(smul(2 % M, T), I))
    if mutate != "break_degree2":
        check("R2_T_cubed_reduces_into_span_1_T (T^3=2T-1 => no independent 3rd slot)",
              t3_reduces)

    # ---- R3 : present-core = ZMod44[T] is COMMUTATIVE (P-ABELIAN). ------------------
    pc = present_core(T)
    all_commute = all(commute(Q, T) for Q in pc)
    pairwise = all(commute(P, Q) for P in list(pc)[:60] for Q in list(pc)[:60])  # sample
    check("R3_present_core_is_commutative (every a*1+b*T commutes with T; tPoly_commutes)",
          all_commute and pairwise)

    # ---- R4 : the present-core idempotents ARE spectral projections, all polynomials in T,
    #           all commuting with T (idempotent-in-a-commutative-algebra => commuting). -----
    pc_idem = [Q for Q in pc if is_idem(Q)]
    # over ZMod 44, sqrt(5) exists ({7,15,29,37}) so there are 8 idempotents (0,I + 6 nontrivial
    # spectral projections), NOT just {0,I}; each is a polynomial a*1+b*T and commutes with T.
    if mutate != "break_degree2":
        check("R4_present_core_has_8_idempotents_all_commute (spectral projections in ZMod44[T])",
              len(pc_idem) == 8 and all(commute(Q, T) for Q in pc_idem)
              and all(Q in pc for Q in pc_idem))

    # ---- R5 : THE DEGREE-2 THEOREM -- commuting idempotent <=> present-core (EQUIVALENCE). --
    #   Enumerate ALL idempotents of M2(ZMod 44): 3484 total; EXACTLY 8 commute with T, and
    #   those 8 are EXACTLY the present-core idempotents.  So on the T-carrier:
    #        idempotent AND commutes-with-T   <=>   in present-core ZMod44[T].
    #   Hence "in-core idempotent => commuting" (W1) is a THEOREM of the degree-2/abelian core,
    #   with the converse too (commuting => in-core): the wall is the abelian-ness, exactly.
    all_idem = [Q for Q in itertools.product(range(M), repeat=4) if is_idem(Q)]
    comm_idem = [Q for Q in all_idem if commute(Q, T)]
    noncomm_idem = [Q for Q in all_idem if not commute(Q, T)]
    equiv = (set(comm_idem) == set(pc_idem))
    if mutate != "break_degree2":
        check("R5_commuting_idempotent_IFF_present_core (8=8, exact equivalence)",
              len(all_idem) == 3484 and len(comm_idem) == 8
              and len(noncomm_idem) == 3476 and equiv)

    # ---- R6 : the three-property trap, re-derived as a DEGREE-2 corollary. ----------
    #   Among the owned NAMED 2x2 objects, classify (idempotent? involution? in-core? comm[T]?).
    #   The trap "idempotent AND [T,.]!=0 AND owned never all three" is now EXPLAINED: any owned
    #   in-core idempotent commutes (R5, degree-2); the only owned non-commuting objects (X,Z,XZ)
    #   are involutions/neither, never idempotents.  Any-two-never-three.
    owned = {"I": I, "T": T, "T2": T2, "FrozenSU2_X": X, "FrozenSU2_Z": Z, "XZ": matmul(X, Z)}
    owned_idem_noncomm = [nm for nm, A in owned.items() if is_idem(A) and not commute(A, T)]
    check("R6_three_property_trap_no_owned_idempotent_noncommuting", len(owned_idem_noncomm) == 0)
    # and the only owned idempotent among the named objects is I (in-core, commuting):
    owned_idem = [nm for nm, A in owned.items() if is_idem(A)]
    check("R6_only_named_owned_idempotent_is_I_in_core",
          owned_idem == ["I"] and (owned["I"] in pc))

    # ---- R7 : THE CRUX -- owned ON-CARRIER idempotents subset the present-core. ------
    #   Owned 2x2/ZMod44 objects with an idempotent among them: only I is idempotent, and I in core.
    #   The kill is GATED on this: inject a hand-picked non-core idempotent as "owned" and R7 fails.
    owned_oncarrier = dict(owned)
    if mutate == "break_owned_idem_offcarrier":
        owned_oncarrier["diag10"] = (1, 0, 0, 0)  # diag(1,0): idem, NOT in core, non-commuting
    oncarrier_idem = [A for A in owned_oncarrier.values() if is_idem(A)]
    crux = all(A in pc for A in oncarrier_idem)     # every owned on-carrier idempotent in-core
    check("R7_CRUX_owned_oncarrier_idempotents_subset_present_core", crux)

    # ---- R8 : NEGATIVE CONTROL -- a non-core idempotent WOULD break W1 (kill is genuine). --
    #   diag(1,0): idempotent, NOT a polynomial in T, does NOT commute with T.  If it were OWNED
    #   on-carrier, W1 ("owned idempotent => commuting") would be FALSE.  It is UNOWNED (a free
    #   choice, the Qnc witness).  So W1 is a real gate, not vacuous.
    Qnc = (1, 0, 0, 0)
    would_break = is_idem(Qnc) and (Qnc not in pc) and (not commute(Qnc, T))
    check("R8_negative_control_noncore_idempotent_would_break_W1", would_break)

    # ---- R9 : SCOPE -- the meson support projector is an OWNED idempotent OFF the T-carrier. --
    #   mesonSupportProjector : Matrix(MesonCarrier E Gen) Rat  is diagonal-idempotent (owned),
    #   but its carrier is Fin E x Fin Gen over Q, NOT 2x2 over ZMod 44 -- so "commutes with T"
    #   is UNTYPED for it.  It is OUTSIDE W1's scope (which is about the T-carrier), so it does
    #   NOT count against the crux.  We model it as a 3x3 diagonal idempotent and confirm it is
    #   (i) idempotent, (ii) generically non-scalar, (iii) off-carrier (dim != 2).
    def diag_idem_3(bits):
        return tuple(bits[i] if i == j else 0 for i in range(3) for j in range(3))
    meson = diag_idem_3((1, 1, 0))   # a support projector; diagonal 0/1 => idempotent
    def mm3(A, B):
        return tuple(sum(A[3 * r + k] * B[3 * k + c] for k in range(3))
                     for r in range(3) for c in range(3))
    meson_idem = (mm3(meson, meson) == meson)
    meson_nonscalar = not (meson[0] == meson[4] == meson[8] and meson[1] == 0 and meson[3] == 0
                           and meson[2] == 0 and meson[6] == 0 and meson[5] == 0 and meson[7] == 0
                           and False)  # it's diagonal but 1,1,0 => not a scalar multiple of I3
    meson_offcarrier = True  # dim 3 (or E*Gen) over Q, not 2 over ZMod44
    check("R9_meson_projector_owned_idempotent_but_OFF_carrier (out of W1 scope)",
          meson_idem and meson_nonscalar and meson_offcarrier)

    print(f"----- [{tag}] {'OK' if not FAILS else 'FAILURES: ' + ','.join(FAILS)} -----\n")
    return 0 if not FAILS else 1


def main():
    base = run(None)
    if base != 0:
        print("BASE CHECKS FAILED -- thesis not reproduced.")
        return 1
    print("##### MUTANTS (each MUST kill => rc=1) #####")
    mutants = ["break_degree2", "break_frozen_x", "break_owned_idem_offcarrier"]
    all_killed = True
    for mut in mutants:
        rc = run(mut)
        killed = rc == 1
        print(f"MUTANT {mut}: {'KILLED (good)' if killed else 'SURVIVED (BAD)'}\n")
        all_killed = all_killed and killed
    if not all_killed:
        print("A MUTANT SURVIVED -- check does not discriminate.")
        return 1
    print("ALL BASE PASS, ALL MUTANTS KILLED. rc=0")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
