#!/usr/bin/env python3
"""selector_basepoint_check — CAN-FAIL probe for BASEPOINT PROPAGATION.

QUESTION: does the OWNED distinguished vertex ω₀ (V₉ = Ω₈ ⊔ {ω₀}), plus the
owned inter-zone structure of K(9,11,13), CANONICALLY distinguish any vertex (or
induce a canonical ordering) in zones 11 and 13?

MECHANISM UNDER TEST: ω₀ is a marked vertex in zone 9. The scene is the COMPLETE
tripartite graph K(9,11,13). We compute, on the ACTUAL scene, the pointwise
stabilizer of ω₀ inside Aut(K) and ask whether it acts transitively on zone 11
and on zone 13. If it is transitive, NO zone-11/13 vertex is distinguished by ω₀
(propagation is dead / needs a catalog). If some orbit is a proper subset, that
orbit is a candidate owned distinction.

The probe is CAN-FAIL: it would PRINT A DISTINCTION if one existed. It does not
assume the no-go.

Owned facts consumed (all verified on disk this session):
  - V₉ = Ω₈ ⊔ {ω₀}, ω₀ a single marked vertex  (BOOK_01 §01.8:867, §01.20:1541)
  - scene = K(9,11,13), complete tripartite, all-to-all between zones
                                              (BOOK_01 §01.20:1584-1594; A matrix)
  - Aut(K(9,11,13)) = S₉ × S₁₁ × S₁₃ (distinct part sizes; componentwise)
                                              (BOOK_01:1518; cert vp_raw_self_reading_actual_aut_group.py)
  - C1 exchangeability: A invariant under S₉×S₁₁×S₁₃; a part-internal exception
    NAMES A PRIVILEGED VERTEX = exogenous parameter = ⊥M1   (BOOK_01:1570)
  - the ONLY Aut-invariant covectors are the 3 zone-indicators; a single-vertex
    reader is NOT Aut-invariant and NEEDS AN EXOGENOUS LABEL  (BOOK_04:1392)
"""
import itertools, sys

# ---- Scene model: vertices are (zone, index). Zones 9,11,13. -----------------
Z9  = [("9", i)  for i in range(9)]
Z11 = [("11", i) for i in range(11)]
Z13 = [("13", i) for i in range(13)]
OMEGA0 = ("9", 0)          # the owned marked witness ω₀ (any one zone-9 vertex; by
                           # S9-exchangeability the choice of index is itself a gauge)
V   = Z9 + Z11 + Z13

def adjacent(u, w):
    """K(9,11,13): edge iff different zones (complete between, empty within)."""
    return u[1] is not None and w != u and u[0] != w[0]

# Sanity: reproduce the owned scene invariants (|V|=33, |E|=359, tri=1287).
def scene_invariants():
    E = sum(1 for a, b in itertools.combinations(V, 2) if adjacent(a, b))
    # triangles: one vertex per zone, all-to-all => 9*11*13
    tri = 9 * 11 * 13
    return len(V), E, tri

fails = []
def check(name, cond, detail=""):
    status = "PASS" if cond else "FAIL"
    print(f"[{status}] {name}  {detail}")
    if not cond:
        fails.append(name)

nV, nE, tri = scene_invariants()
check("SCENE_INVARIANTS", (nV, nE, tri) == (33, 359, 1287),
      f"|V|={nV} |E|={nE} tri={tri} (owned: 33/359/1287)")

# ---- CORE COMPUTATION -------------------------------------------------------
# Aut(K(9,11,13)) = S9 x S11 x S13 acts componentwise (owned). A graph automorphism
# is any triple (σ9, σ11, σ13). We do NOT need to enumerate all 9!*11!*13! elements:
# the pointwise stabilizer of ω₀ = ("9",0) is  Stab(ω₀) = Stab_{S9}(0) x S11 x S13
#                                             = S8(on {1..8}) x S11 x S13.
# The zone-11 and zone-13 factors are UNTOUCHED by fixing a zone-9 vertex, because the
# action is a DIRECT PRODUCT and the graph is COMPLETE between zones (every zone-9
# vertex, ω₀ included, has IDENTICAL all-to-all connectivity to 11 and 13).
#
# We verify transitivity of Stab(ω₀) on zone 11 and zone 13 CONSTRUCTIVELY: for each
# pair of zone-11 vertices we exhibit an automorphism fixing ω₀ that maps one to the
# other (a transposition in S11, identity elsewhere) and CHECK it is a genuine graph
# automorphism AND fixes ω₀. Same for zone 13. This is the can-fail heart: if the
# all-to-all structure did NOT make these maps automorphisms, some pair would be
# unreachable and we would find a proper orbit = a distinction.

def apply_perm_on_zone(zone, i, j):
    """Return the automorphism = transposition (i j) within `zone`, id elsewhere."""
    def f(v):
        if v[0] != zone:
            return v
        if v[1] == i: return (zone, j)
        if v[1] == j: return (zone, i)
        return v
    return f

def is_automorphism(f):
    """f preserves adjacency and non-adjacency over all pairs (exact, on 33 vertices)."""
    for a, b in itertools.combinations(V, 2):
        if adjacent(a, b) != adjacent(f(a), f(b)):
            return False
    return True

def orbit_of_vertex_under_stab(zone, start):
    """Orbit of `start` (in `zone`) under the group generated by all within-`zone`
    transpositions that (a) are genuine automorphisms and (b) fix ω₀."""
    zone_verts = [v for v in V if v[0] == zone]
    gens = []
    for i in range(len(zone_verts)):
        for j in range(i + 1, len(zone_verts)):
            f = apply_perm_on_zone(zone, i, j)
            if f(OMEGA0) == OMEGA0 and is_automorphism(f):
                gens.append(f)
    # BFS closure of the orbit
    seen = {start}
    frontier = [start]
    while frontier:
        cur = frontier.pop()
        for g in gens:
            nxt = g(cur)
            if nxt not in seen:
                seen.add(nxt); frontier.append(nxt)
    return seen

orb11 = orbit_of_vertex_under_stab("11", ("11", 0))
orb13 = orbit_of_vertex_under_stab("13", ("13", 0))

# CAN-FAIL: if Stab(ω₀) is transitive on the zone, the orbit is the WHOLE zone =>
# ω₀ distinguishes NOTHING there. A distinction would show up as a PROPER orbit.
check("STAB_OMEGA0_TRANSITIVE_ON_Z11", len(orb11) == 11,
      f"|orbit of a zone-11 vertex under Stab(ω₀)| = {len(orb11)} / 11")
check("STAB_OMEGA0_TRANSITIVE_ON_Z13", len(orb13) == 13,
      f"|orbit of a zone-13 vertex under Stab(ω₀)| = {len(orb13)} / 13")

# ---- The propagation verdict (the thing the task asks) ----------------------
# ω₀ distinguishes a zone-11/13 vertex  <=>  some orbit is a PROPER subset.
omega0_distinguishes_11 = (len(orb11) < 11)
omega0_distinguishes_13 = (len(orb13) < 13)
print()
print("PROPAGATION VERDICT (can-fail — a TRUE below would be a live mechanism):")
print(f"  ω₀ distinguishes some zone-11 vertex : {omega0_distinguishes_11}")
print(f"  ω₀ distinguishes some zone-13 vertex : {omega0_distinguishes_13}")

# ---- NEGATIVE CONTROL: the mechanism is not vacuous -------------------------
# If we DELETE the all-to-all completeness (make ω₀'s edges to zone 11 special),
# a distinction WOULD appear. We rebuild adjacency where ω₀ connects to ONLY the
# first zone-11 vertex, and re-run: the orbit must then split (proving the probe
# CAN detect a distinction; it is not rigged to always print "no").
def adjacent_broken(u, w):
    if u == w: return False
    if u[0] == w[0]: return False
    # ω₀ is adjacent in zone 11 ONLY to ("11",0); a non-complete owned edge set
    if u == OMEGA0 and w[0] == "11": return w == ("11", 0)
    if w == OMEGA0 and u[0] == "11": return u == ("11", 0)
    return True

def is_automorphism_broken(f):
    for a, b in itertools.combinations(V, 2):
        if adjacent_broken(a, b) != adjacent_broken(f(a), f(b)):
            return False
    return True

def orbit_broken(zone, start):
    zone_verts = [v for v in V if v[0] == zone]
    gens = []
    for i in range(len(zone_verts)):
        for j in range(i + 1, len(zone_verts)):
            f = apply_perm_on_zone(zone, i, j)
            if f(OMEGA0) == OMEGA0 and is_automorphism_broken(f):
                gens.append(f)
    seen = {start}; frontier = [start]
    while frontier:
        cur = frontier.pop()
        for g in gens:
            nxt = g(cur)
            if nxt not in seen: seen.add(nxt); frontier.append(nxt)
    return seen

orb11_broken = orbit_broken("11", ("11", 0))
check("NEGCTRL_BROKEN_COMPLETENESS_SPLITS_Z11", len(orb11_broken) < 11,
      f"under a NON-complete owned edge, orbit = {len(orb11_broken)} < 11 "
      f"(probe CAN detect a distinction — not rigged)")

print()
if fails:
    print(f"SCRIPT RESULT: {len(fails)} FAIL(S): {fails}")
    sys.exit(1)
else:
    print("SCRIPT RESULT: all checks PASS. "
          "Under owned all-to-all completeness, Stab(ω₀) is transitive on zones "
          "11 and 13 => ω₀ distinguishes NO zone-11/13 vertex. Propagation DEAD. "
          "The negative control confirms the probe would have detected a distinction "
          "had the owned structure not been complete.")
    sys.exit(0)
