import D0.Claims.Signature31Split
import Mathlib.GroupTheory.Perm.Basic
import Mathlib.Tactic

/-!
# D0-INVARIANT-GENERATION-BRIDGE-001 — the generation space IS the minimal observable algebra

Lean lift of `_TASKS_CENTER_ATTACK/BRIDGE_INVARIANT_GENERATION_MEMO.md` (post-skeptic v2,
BRIDGE-SURVIVES; compute companion `bridge_invariant_generation_check.py`, ALL PASS + 5/5
mutations). Registry faces:

* **Face S (selector/extremality)**: `R^Aut = (ℂ^V)^Aut`, the extremal-minimal observable
  algebra — `D0-P-INVARIANT-MINIMAL-001` (RAISE_SELECTOR_MINIMAL_MEMO.md T1–T3).
* **Face G (matter/generation)**: the trivial-isotype multiplicity space
  `span{1₉, 1₁₁, 1₁₃}` the `M₃` commutant block acts on — `D0-MATTER-REP-001`,
  `D0-REPRESENTATION-RECONSTRUCTION-MAXIMALITY-NOGO-001` (W2_QUANTITY_IDENT_MEMO.md:126-128).

**The bridge (this module):** the two faces are ONE subspace of `ℚ³³` — same rank-3
projector. `P` (Face S) is the Reynolds/orbit-averaging projector computed from a
**LITERAL** list of 30 within-zone adjacent transpositions by finite orbit closure;
`Q` (Face G) is the zone-indicator projector `Σ_z (1/|z|)·1_z 1_zᵀ` written from the
in-tree zone map `D0.Claims.zone31` (`Signature31Split.lean`). `P = Q` by `native_decide`.

**Anti-circularity (pre-registered, memo §6 R3b/§9):** `gens` below is a literal
permutation list — `Equiv.swap 0 1, …` — NOT derived from `zone31`. The two sides of
`bridge_projector_eq` are built from genuinely different inputs (a generator list vs the
zone map); the equality is the computed content, not a definitional unfolding of one map.

**HONESTY CLAUSE (memo §0, load-bearing).** Fixed-space = trivial-isotype is a
definition-unfolding of the one Reynolds projector; the CONTENT is the identification of
two separately built and certified registry chains + the composite reading: *the
generation degrees of freedom are exactly the extremal minimal observables of the scene —
a ZONE-AXIS generation index is a class function* (physical e/μ/τ-role labeling stays
external, `PRIM-FINITE-SPECTRAL-TRIPLE-REP`). INHERITANCE (memo R2, RR-1/RR-2): owned
exactly as far as `D0-P-INVARIANT-MINIMAL-001` is owned — universal no-proper-refinement
outsourced to the LEAN_PROVED `canonical_within_zone_selector_nogo` chain
(`D0.Foundation.CanonicalSelectorNoGo`); class-function-universality EVIDENCE-grade
(row-549 scope). Does NOT re-derive the count 3 (owned by the frozen scene); does NOT
force Weyl-role assignment (`GL(3)` freedom intact).

**Scope of `gens`:** the 30 swaps generate `Aut(K(9,11,13)) = S₉ × S₁₁ × S₁₃` (adjacent
transpositions generate each `Sₙ` — standard, cited not formalized); what the theorem
USES is only the computable fact that their orbit closure has the zones as orbits, so the
orbit-averaging projector of the generated group equals `Q`. Nothing here evaluates
`Equiv.Perm (Fin n)` as a `Fintype` (17-module `native_decide` precedent respected).
-/

namespace D0.Claims.InvariantGenerationBridge

open Equiv

/-! ## Face S input: a LITERAL generator list (30 within-zone adjacent transpositions) -/

/-- The 30 within-zone adjacent transpositions of `Aut(K(9,11,13))`, as a **literal** list
(pre-registered constraint R3b: NOT derived from `zone31` — the boundary pairs `(8,9)` and
`(19,20)` are absent by inspection of the literal list, not by a zone test). -/
def gens : List (Equiv.Perm (Fin 33)) :=
  [ Equiv.swap 0 1, Equiv.swap 1 2, Equiv.swap 2 3, Equiv.swap 3 4,
    Equiv.swap 4 5, Equiv.swap 5 6, Equiv.swap 6 7, Equiv.swap 7 8,
    Equiv.swap 9 10, Equiv.swap 10 11, Equiv.swap 11 12, Equiv.swap 12 13,
    Equiv.swap 13 14, Equiv.swap 14 15, Equiv.swap 15 16, Equiv.swap 16 17,
    Equiv.swap 17 18, Equiv.swap 18 19,
    Equiv.swap 20 21, Equiv.swap 21 22, Equiv.swap 22 23, Equiv.swap 23 24,
    Equiv.swap 24 25, Equiv.swap 25 26, Equiv.swap 26 27, Equiv.swap 27 28,
    Equiv.swap 28 29, Equiv.swap 29 30, Equiv.swap 30 31, Equiv.swap 31 32 ]

/-- There are exactly `8 + 10 + 12 = 30` generators (sanity: within-zone adjacent pairs). -/
theorem gens_length : gens.length = 30 := by native_decide

/-- One-step orbit expansion under the literal generator list. -/
def step (s : Finset (Fin 33)) : Finset (Fin 33) :=
  s ∪ s.biUnion (fun x => (gens.map (fun g => g x)).toFinset)

/-- The orbit of `i` under the group generated by `gens`, by finite closure (33 expansion
steps saturate on a 33-point carrier; the generators are involutions, so word-reachability
under `gens` IS the group orbit). -/
def orbit (i : Fin 33) : Finset (Fin 33) := step^[33] {i}

/-- **Face S projector** `P`: the Reynolds/orbit-averaging projector of the generated
group — `P i j = 1/|orbit(i)|` if `j ∈ orbit(i)`, else `0`. For a permutation action the
group-averaged projector onto the fixed space has exactly this block form
(orbit-stabilizer; memo §0). Built from `gens` ONLY — never from `zone31`. -/
def P : Matrix (Fin 33) (Fin 33) ℚ :=
  Matrix.of fun i j => if j ∈ orbit i then ((orbit i).card : ℚ)⁻¹ else 0

/-! ## Face G input: the zone-indicator projector from the in-tree zone map -/

/-- Zone sizes of the frozen scene `K(9,11,13)`. -/
def zoneSize : Fin 3 → ℚ := ![9, 11, 13]

/-- **Face G projector** `Q = Σ_z (1/|z|) · 1_z 1_zᵀ`: the projector onto the OWNED
generation space `span{1₉, 1₁₁, 1₁₃}` (trivial-isotype multiplicity space,
W2_QUANTITY_IDENT_MEMO.md:126-128), written from the in-tree `D0.Claims.zone31`. -/
def Q : Matrix (Fin 33) (Fin 33) ℚ :=
  Matrix.of fun i j => if zone31 i = zone31 j then (zoneSize (zone31 i))⁻¹ else 0

/-! ## The bridge -/

/-- Entrywise form of the bridge (the `native_decide` payload). -/
theorem bridge_entrywise : ∀ i j : Fin 33, P i j = Q i j := by native_decide

/-- **THE BRIDGE (D0-INVARIANT-GENERATION-BRIDGE-001): one projector, two constructions.**
The Reynolds projector of the literal generator list (Face S, extremal-minimal observable
algebra `R^Aut`) IS the zone-indicator projector (Face G, the OWNED generation space):
`P = Q` on `Matrix (Fin 33) (Fin 33) ℚ`. -/
theorem bridge_projector_eq : P = Q := by
  ext i j; exact bridge_entrywise i j

/-- The common object is a projector: `Q² = Q` (hence `P² = P` by the bridge). -/
theorem q_idempotent : Q * Q = Q := by native_decide

/-- The common object is symmetric: `Qᵀ = Q` (an orthogonal projector). -/
theorem q_symmetric : Q.transpose = Q := by native_decide

/-- **Rank/dimension 3 as a trace:** `tr Q = 3` — the one 3-dimensional object read twice
("dim R^Aut = 3" = "3 generations" counts ONE object; the count 3 is owned by the frozen
scene, not re-derived here). -/
theorem q_trace_three : Matrix.trace Q = 3 := by native_decide

/-- **Orbit count 3 from the literal generators alone** (no zone map): the orbit closure
of `gens` partitions `Fin 33` into exactly 3 orbits. -/
theorem orbit_count_three : (Finset.univ.image orbit).card = 3 := by native_decide

/-- Package: the bridge + projector facts + the dimension, one capstone. -/
theorem invariant_generation_bridge :
    P = Q ∧ Q * Q = Q ∧ Matrix.trace Q = 3 ∧ (Finset.univ.image orbit).card = 3 :=
  ⟨bridge_projector_eq, q_idempotent, q_trace_three, orbit_count_three⟩

end D0.Claims.InvariantGenerationBridge
