import D0.Core.Phi
import D0.Dynamics.ToralAutomorphism
import Mathlib.Tactic

namespace D0.Geometry

/-!
# Fibonacci anyon uniqueness / Ising exclusion for the internal D0 CORE carrier

This module formalises a finite branch-count exclusion, NOT a full classification
of unitary modular tensor categories.

The D0 CORE time carrier is the degree-two object `Q(phi)/Q` (minimal polynomial
`x^2 - x - 1`, irreducible over `Q`) realised concretely by the toral
automorphism `T = !![0,1;1,-1]` whose characteristic polynomial `x^2 + x - 1`
has exactly two eigen-branches (the two roots `phi^{-1}` and `-phi`). The single
internal generating relation is the quadratic `p + p^2 = 1`
(equivalently `phi^2 = phi + 1`), which fixes exactly TWO independent branch
labels and no more.

* A Fibonacci-type fusion carrier `tau (x) tau = 1 (+) tau` has one nontrivial
  object `tau`; its branch data is governed by the SAME degree-two quadratic
  `d^2 = d + 1`, so its independent-branch count is `2`, matching the toral
  degree. => `D0-FIBONACCI-ANYON-UNIQUENESS-001` CERT-CLOSED (internal carrier).

* An Ising-type fusion carrier has three simple objects `{1, sigma, psi}`.
  `3 > 2`: Ising needs an extra independent branch label beyond the two fixed by
  `p + p^2 = 1`; that label is not generated by the internal quadratic relation,
  so it must come from an external catalog and Ising is EXCLUDED from the
  internal CORE carrier. => `D0-ISING-ANYON-EXCLUSION-001` NO-GO.

Honesty boundary: the genuine classification of unitary fusion / modular tensor
categories is a deep external theorem and is NOT claimed here. We only prove the
finite branch-count obstruction for the internal degree-two carrier.
-/

open Matrix

/-- The degree of the CORE time field `Q(phi)/Q`: the minimal polynomial of `phi`
is `x^2 - x - 1`, irreducible over `Q`, so the extension degree is two. -/
def coreFieldDegree : Nat := 2

/-- The toral automorphism `T = !![0,1;1,-1]` has characteristic polynomial
`x^2 + x - 1`, a degree-two polynomial with two distinct eigen-branches
(`phi^{-1}` and `-phi`). This is the number of independent eigen-branches. -/
def toralBranchCount : Nat := 2

/-- The number of simple objects in an Ising-type fusion carrier: `{1, sigma, psi}`. -/
def isingSimpleObjectCount : Nat := 3

/-- The number of independent branch labels of a Fibonacci-type fusion carrier:
the single nontrivial object `tau` plus the unit are governed by the degree-two
fusion quadratic `d^2 = d + 1`, fixing exactly two independent branch labels. -/
def fibonacciNontrivialBranchCount : Nat := 2

/-- Concrete finite model of the toral eigen-branches as the index set `Fin 2`
(one index per root of the degree-two characteristic polynomial). -/
def toralBranchIndex : Finset (Fin 2) := Finset.univ

/-- Concrete finite model of the Ising simple objects `{1, sigma, psi}` as `Fin 3`. -/
def isingObjectIndex : Finset (Fin 3) := Finset.univ

/-- The toral branch index set really has `toralBranchCount` elements. -/
theorem toralBranchIndex_card : toralBranchIndex.card = toralBranchCount := by
  decide

/-- The Ising object index set really has `isingSimpleObjectCount` elements. -/
theorem isingObjectIndex_card : isingObjectIndex.card = isingSimpleObjectCount := by
  decide

/-- The internal generating relation `phi^2 = phi + 1` is the degree-two relation
that fixes the branch count. This anchors `coreFieldDegree = 2` to the actual
field relation proved in `D0.Core.Phi`. -/
theorem core_degree_two_relation : D0.phi ^ 2 = D0.phi + 1 :=
  D0.phi_sq

/-- The toral carrier satisfies the SAME structural degree-two relation in matrix
form: `T^2 + T - 1 = 0` (characteristic polynomial `x^2 + x - 1`). This is the
matrix shadow of the single internal quadratic that fixes two branches. -/
theorem toral_degree_two_relation :
    D0.Dynamics.T ^ 2 + D0.Dynamics.T - 1 = 0 :=
  D0.Dynamics.T_charpoly_quadratic_relation

/-- The core field degree, the toral branch count, and the Fibonacci branch count
all coincide at two: a single degree-two relation governs them all. -/
theorem core_toral_fibonacci_degrees_agree :
    coreFieldDegree = toralBranchCount /\
      fibonacciNontrivialBranchCount = toralBranchCount /\
        coreFieldDegree = fibonacciNontrivialBranchCount := by
  decide

/-- Fibonacci matches the toral degree: its independent branch count equals the
two eigen-branches of the toral carrier. This is the CERT-CLOSED direction. -/
theorem fibonacci_matches_toral_degree :
    fibonacciNontrivialBranchCount = toralBranchCount := by
  decide

/-- Ising needs strictly more simple objects than the toral carrier supplies
eigen-branches: `3 > 2`. This is the NO-GO direction — the extra Ising label is
not generated by the internal degree-two quadratic. -/
theorem ising_requires_extra_branch :
    isingSimpleObjectCount > toralBranchCount := by
  decide

/-- Quantitatively, Ising requires exactly one independent branch label beyond
what the internal degree-two carrier fixes. -/
theorem ising_branch_excess :
    isingSimpleObjectCount - toralBranchCount = 1 := by
  decide

/-- Fibonacci does NOT exceed the toral branch budget: its excess is zero, so no
external label is needed. -/
theorem fibonacci_no_branch_excess :
    fibonacciNontrivialBranchCount - toralBranchCount = 0 := by
  decide

/-- The branch-count cardinalities of the concrete finite models obey the same
strict inequality, tying the abstract counts to real `Finset` cardinalities. -/
theorem ising_card_exceeds_toral_card :
    isingObjectIndex.card > toralBranchIndex.card := by
  decide

/-- Owner theorem.

Internal CORE carrier branch dichotomy:

* the core field degree, the toral eigen-branch count, and the Fibonacci
  independent-branch count all equal two (one degree-two relation governs them);
* the Fibonacci carrier matches the toral degree exactly (CERT-CLOSED);
* the Ising carrier has strictly more simple objects than the toral carrier has
  eigen-branches, with the concrete finite models exhibiting the same strict
  inequality (NO-GO: Ising needs an external branch label).
-/
theorem fibonacci_anyon_uniqueness_owner :
    (coreFieldDegree = toralBranchCount /\
        fibonacciNontrivialBranchCount = toralBranchCount) /\
      (isingSimpleObjectCount > toralBranchCount /\
        isingObjectIndex.card > toralBranchIndex.card) := by
  refine ⟨⟨?_, fibonacci_matches_toral_degree⟩,
    ⟨ising_requires_extra_branch, ising_card_exceeds_toral_card⟩⟩
  decide

end D0.Geometry
