-- AUTO-GENERATED from CLAIM_TO_LEAN_MAP.csv by tools/generate_lean_aggregates.py.
-- Do not edit by hand; run `python tools/generate_lean_aggregates.py`.


import D0.Active.NonzeroMatterSourceNeutrality
import D0.Active.ScalarPoissonReduction
import D0.Active.StressLocalityTradeoff
import D0.Algebra.ArchiveCommutatorOperators
import D0.Algebra.Clifford
import D0.Algebra.Clifford13
import D0.Algebra.CliffordExplicit
import D0.Algebra.D0InternalDimensionSelector
import D0.Algebra.GaloisPhiNontrivial
import D0.Algebra.GammaMatrices
import D0.Algebra.GaugeActionSignBridge
import D0.Algebra.GaugeKineticPositivity
import D0.Algebra.HurwitzLocalBoundary
import D0.Algebra.LieCarrierFinite
import D0.Algebra.LorentzNoGo
import D0.Algebra.RoleSignature
import D0.Born
import D0.Bridge.AdlerWeissBridge
import D0.Bridge.Assumptions.ExternalHST
import D0.Bridge.Assumptions.Frobenius
import D0.Bridge.Assumptions.HeatTraceWeyl
import D0.Bridge.Assumptions.Hurwitz
import D0.Bridge.Assumptions.JonesIndex
import D0.Bridge.Assumptions.LindemannLnPhi
import D0.Bridge.Assumptions.MordellE8
import D0.Bridge.Assumptions.SmoothInterpolation
import D0.Bridge.Assumptions.Wilson
import D0.Bridge.Assumptions.YangMillsKilling
import D0.Bridge.ComplexQMBridge
import D0.Bridge.ConnesReconstructionBridge
import D0.Bridge.ConstrainedHamiltonianEmbeddingPassport
import D0.Bridge.ConvexResponseBridge
import D0.Bridge.DixmierTraceBridge
import D0.Bridge.FinalBridgeIndex
import D0.Bridge.InternalConeSpeed
import D0.Bridge.InterpretationSpine
import D0.Bridge.LorentzBridge
import D0.Bridge.M1InfoReconstructionBridge
import D0.Bridge.OperatorOriginIndex
import D0.Bridge.PhiDiscreteRG
import D0.Bridge.RieffelGHPBridge
import D0.Bridge.SICalibrationBoundary
import D0.Bridge.SICalibrationClosure
import D0.Bridge.SmoothMetricBridge
import D0.Bridge.TickGaugeLorentz
import D0.Bridge.TomitaTakesakiBridge
import D0.Bridge.VerlindeEntropicBridge
import D0.Capacity
import D0.Claims.Book04Selectors
import D0.Claims.CarrierNotIcosahedral
import D0.Claims.CkmExactMatrix
import D0.Claims.Class5Aliasing
import D0.Claims.DimLadderCompact
import D0.Claims.EWWindowForcing
import D0.Claims.FibonacciFusionRing
import D0.Claims.FibonacciIfBridge
import D0.Claims.GluingAnomalyTime
import D0.Claims.HiggsYukawaBlock
import D0.Claims.IcosianE8GramFinite
import D0.Claims.JonesIndexPhi
import D0.Claims.KTheoryGapModule
import D0.Claims.KernelZoneSplit
import D0.Claims.MixingHierarchyInversion
import D0.Claims.NonabelianSeamGap
import D0.Claims.Q8DedekindMinimality
import D0.Claims.Signature31Split
import D0.Claims.Spin2TT
import D0.Claims.Time2DPisot
import D0.Claims.VietaGaloisAbcd
import D0.Claims.Window44GroupSpectrum
import D0.Claims.Xi5TorusDefect
import D0.Combinatorics.CliqueComplex
import D0.Combinatorics.CompleteTripartite
import D0.Combinatorics.EulerPhi
import D0.Combinatorics.ForcedReturnWindows
import D0.Combinatorics.HighGainCounts
import D0.Combinatorics.InfinitePhaseTower
import D0.Combinatorics.PhaseTower
import D0.Combinatorics.PhaseTowerControls
import D0.Combinatorics.PhaseTowerMinimality
import D0.Combinatorics.PhaseTowerRecursion
import D0.Combinatorics.PhaseUnfolding
import D0.Combinatorics.Tripartite
import D0.Complexity.HeatTraceLyapunov
import D0.Condensed.AdmissibleSubfunctor
import D0.Condensed.CondensedPhiVacuum
import D0.Condensed.OperatorNaturality
import D0.Condensed.ProfiniteSupport
import D0.Condensed.ProjectiveSystem
import D0.Core.BornFinite
import D0.Core.BornFiniteEffects
import D0.Core.BornQuadraticOrigin
import D0.Core.BornQuadraticResponse
import D0.Core.CapacityChain
import D0.Core.Delta
import D0.Core.DyadABCD
import D0.Core.FiniteTypes
import D0.Core.FixedDetectorTimeLadder
import D0.Core.MatrixResponse
import D0.Core.Phi
import D0.Core.PositiveResponse
import D0.Cosmology.ArchiveConvexity
import D0.Cosmology.ArchiveHomogeneousState
import D0.Cosmology.ArchiveVolumeBounds
import D0.Cosmology.CLightconePercolationOwner
import D0.Cosmology.CMBFiedlerFreezeout
import D0.Cosmology.CMBLaplacianIDS
import D0.Cosmology.CMBNsSmoothingUndeterminedNoGo
import D0.Cosmology.ConcreteEntropyArchiveFlow
import D0.Cosmology.CoreShapePassportBoundary
import D0.Cosmology.DarkArchiveTransfer
import D0.Cosmology.EntropyArchiveFlow
import D0.Cosmology.EntropyJacobianSign
import D0.Cosmology.FeedbackPartitionFunction
import D0.Cosmology.FiniteFeedbackEquationOfState
import D0.Cosmology.FloorMassProjection
import D0.Cosmology.HeatTraceEnergyFunctional
import D0.Cosmology.InflationlessThresholdEnergyOwner
import D0.Cosmology.InstabilitySaturation
import D0.Cosmology.LinearizedEntropyFlow
import D0.Cosmology.PhasonArchiveCapacityRedshift
import D0.Cosmology.PhasonFlipEntropy
import D0.Cosmology.PhasonInitialCovariance
import D0.Cosmology.PhasonWDESignNormalization
import D0.Cosmology.PhasonWZTransfer
import D0.Cosmology.ReheatingEnergyBudgetOwner
import D0.Cosmology.ReheatingHeatTraceJump
import D0.Cosmology.ReheatingPercolationOwner
import D0.Cosmology.ResearchPassCorollaries
import D0.Cosmology.SDEFeedbackReduction
import D0.Cosmology.SurveyReproducibilitySplit
import D0.Cosmology.TransientAcceleration
import D0.Cosmology.ZeroMeanModes
import D0.Defect.Basic
import D0.Defect.Pi0BranchDefect
import D0.Defect.ProjectiveGeneration
import D0.Delta
import D0.Detector.WeakCouplingClassicalization
import D0.Dynamics
import D0.Dynamics.DarkSectorCoarseGrain
import D0.Dynamics.GaloisConjugateBalance
import D0.Dynamics.InternalFeedbackResolvent
import D0.Dynamics.LatticeHydroNoBlowup
import D0.Dynamics.MasterEvolutionTheorem
import D0.Dynamics.PisotContraction
import D0.Dynamics.ToralAutomorphism
import D0.Dynamics.ToralShiftEquivalence
import D0.Dynamics.TraceHeatCapacityGravity
import D0.Dynamics.TraceHeatLucasCore
import D0.Edge.RamificationFromUeEffCompanion
import D0.Evolution.FeshbachSchurTimeDelayOwner
import D0.Evolution.JYNoncommutativeOrderObstruction
import D0.Evolution.PhiFractalTickDynamics
import D0.Evolution.StaticToDynamicsOwner
import D0.Foundation.ContinuumAsInverseLimit
import D0.Foundation.FrobeniusDivision3D
import D0.Foundation.M1Predicate
import D0.Foundation.Omega8Center
import D0.Frozen.ConservedStressProjection
import D0.Frozen.SeamCurvaturePoisson
import D0.Gauge.AnomalySums
import D0.Gauge.AnomalyTrace
import D0.Gauge.BianchiResidual
import D0.Gauge.BraidValence
import D0.Gauge.FlatTensorNoGo
import D0.Gauge.GradedBianchiIdentity
import D0.Gauge.MassGapCostQuantum
import D0.Gauge.MatrixRepGaugeTransform
import D0.Gauge.NonAbelianDiscreteCurvature
import D0.Gauge.NonAbelianSeamObstructionGap
import D0.Gauge.SMCharges
import D0.Gauge.SMGaugeDecomposition
import D0.Gauge.WardFinite
import D0.Gauge.WilsonLinkGaugeCovariance
import D0.Gauge.YangMillsKillingPositivity
import D0.Geometry.ArchiveActionFunctional
import D0.Geometry.ArchiveBianchiIdentity
import D0.Geometry.ArchiveCanonicalDirichlet
import D0.Geometry.ArchiveCanonicalLaplacian
import D0.Geometry.ArchiveCurvatureDensity
import D0.Geometry.ArchiveCurvatureObstruction
import D0.Geometry.ArchiveDirichletEnergy
import D0.Geometry.ArchiveFiberGraph
import D0.Geometry.ArchiveFieldEquation
import D0.Geometry.ArchiveHeatTrace
import D0.Geometry.ArchiveLaplacianNaturality
import D0.Geometry.ArchiveLaplacianPhaseNaturality
import D0.Geometry.ArchiveLaplacianProperties
import D0.Geometry.ArchiveLaplacianRG
import D0.Geometry.ArchiveLightProfinite
import D0.Geometry.ArchiveLocalQuadraticForm
import D0.Geometry.ArchiveLorentzCompatibility
import D0.Geometry.ArchiveModeExponent
import D0.Geometry.ArchivePhaseCurvatureObstruction
import D0.Geometry.ArchivePhaseDistance
import D0.Geometry.ArchivePhaseShift
import D0.Geometry.ArchivePoissonEquation
import D0.Geometry.ArchiveRefinementTower
import D0.Geometry.ArchiveResolventCompactness
import D0.Geometry.ArchiveSeamCurvature
import D0.Geometry.ArchiveSeamRank
import D0.Geometry.ArchiveSpectralCounting
import D0.Geometry.ArchiveStressRepresentative
import D0.Geometry.ArchiveTickGaugeFixing
import D0.Geometry.ArchiveVariation
import D0.Geometry.ArchiveVariationDual
import D0.Geometry.ArchiveVariationSpace
import D0.Geometry.ArchiveWeakField
import D0.Geometry.ArchiveWeakFieldReduction
import D0.Geometry.ArchiveWeightedGraph
import D0.Geometry.ConformalLaplacianTrace
import D0.Geometry.CovarianceTower
import D0.Geometry.EdgeMetricEquation
import D0.Geometry.EdgeStiffnessOrigin
import D0.Geometry.EinsteinReduction
import D0.Geometry.ExternalAnalyticTheoremInterface
import D0.Geometry.FibonacciAnyonUniqueness
import D0.Geometry.FiniteSpin2
import D0.Geometry.FiniteSpin2DOF
import D0.Geometry.FiniteSpin2Dynamics
import D0.Geometry.FiniteSpin2WaveOperator
import D0.Geometry.GHPGoldenCauchyBound
import D0.Geometry.HeatTraceA2Decomposition
import D0.Geometry.HeatTraceConditions
import D0.Geometry.HeatTraceEHProxy
import D0.Geometry.HigherCurvatureCutoff
import D0.Geometry.HigherCurvatureSuppression
import D0.Geometry.HurwitzRigidPhaseGenerator
import D0.Geometry.InfiniteSpectralTower
import D0.Geometry.LucasVoronoiMarkovPartition
import D0.Geometry.NonCommutativeSolenoid
import D0.Geometry.NonCommutativeSolenoidGravity
import D0.Geometry.PhaseReturnBranchCount
import D0.Geometry.PhaseUnfoldingQuasicrystal
import D0.Geometry.Pi0DiscreteAngle
import D0.Geometry.SceneActiveEigenvalues
import D0.Geometry.SpectralActionAdmissibility
import D0.Geometry.SpectralActionLadder
import D0.Geometry.SpectralActionSkeleton
import D0.Geometry.SpectralTower
import D0.Geometry.ToralCanonicalMarkovNoGo
import D0.Geometry.ToralIntegralConjugacy
import D0.Geometry.ToralLucasPeriodicSeed
import D0.Geometry.TorusCore13GeometryOrigin
import D0.Gravity
import D0.Gravity.BlackHoleCapacityA4
import D0.Gravity.BoundaryRelaxationSpectrum
import D0.Gravity.CompactnessLimit
import D0.Gravity.CriticalCollapseDSS
import D0.Gravity.EntropicArchiveInterface
import D0.Gravity.HorizonJetAndBaryonPole
import D0.Gravity.MacroEinsteinInterface
import D0.Gravity.MeasurementHorizonEquivalence
import D0.Gravity.OpticalJetBackreaction
import D0.Gravity.PageCurveFiniteRankOwner
import D0.Gravity.PageTurningPointRank
import D0.Gravity.PressureCapacityBalance
import D0.IM.ArchivePressureCoupling
import D0.IM.ContinuumFromFractalTick
import D0.IM.FractalContinuumAndWitnessHalting
import D0.IM.FractalContinuumPredictions
import D0.IM.FractalTick
import D0.IM.LogdetSecondResponse
import D0.IM.SelfSubstrateTrace
import D0.IM.StrongLogdetPressure
import D0.Interface.ArchiveLaplacian
import D0.Interface.Bianchi
import D0.Interface.MatterAnomaly
import D0.Interface.MatterLocalization
import D0.Interface.Poisson
import D0.Interface.ScalarPoissonReduction
import D0.Interface.VariationDual
import D0.Matter.ArchivePartialTrace
import D0.Matter.ArchiveStressCoupling
import D0.Matter.BaryonMultipletBoundary
import D0.Matter.BaryonS3Symmetrizer
import D0.Matter.BaryonSpinFlavourRanks
import D0.Matter.Book04CenteredSupportSelectors
import D0.Matter.Book04CoefficientOrigin
import D0.Matter.Book04CombinatorialSelectorOrigins
import D0.Matter.Book04ConcreteSelectors
import D0.Matter.Book04FullSupportSelectors
import D0.Matter.Book04OperatorBoundary
import D0.Matter.Book04Selectors
import D0.Matter.CKMBasisMismatch
import D0.Matter.CKMBasisOrigin
import D0.Matter.CKMClass5ParityExclusion
import D0.Matter.CKMClass5SelectorOwner
import D0.Matter.CKMExactMatrixCertificate
import D0.Matter.CKMExactTransfer
import D0.Matter.CKMNontrivialFlavourAlgebra
import D0.Matter.CKMPhasonHolonomy
import D0.Matter.ChargedLeptonMassTransfer
import D0.Matter.ChargedLeptonTransferCertificate
import D0.Matter.CouplingOrthogonalDecomposition
import D0.Matter.DSigmaRoleCycleCarrierNoGo
import D0.Matter.DSigmaRoleTransitionGraph
import D0.Matter.EdgeStressCoupling
import D0.Matter.FiniteSelector
import D0.Matter.GaugeCurvatureOrigin
import D0.Matter.GeneratedMatterSource
import D0.Matter.GenerationAnomalyPreservation
import D0.Matter.GenerationMultiplicity
import D0.Matter.GenerationOverlapResponseOrigin
import D0.Matter.GenerationSelectorOrigin
import D0.Matter.HiggsLogdetStationary
import D0.Matter.HiggsPhasonOrbitNoGo
import D0.Matter.HiggsReturnQuotientAction
import D0.Matter.HiggsScalarProjectorConstructive
import D0.Matter.HyperchargeAnomalyVariety
import D0.Matter.HyperchargeFlowLattice
import D0.Matter.HyperchargeGraphFlowOwner
import D0.Matter.HyperchargeMinimalDenominator
import D0.Matter.KTheoryGapLabeling
import D0.Matter.LeptonGreenPuiseuxOwner
import D0.Matter.LeptonPuiseuxUniquenessObstruction
import D0.Matter.LeptonRiemannHurwitzBranchIndex
import D0.Matter.LocalTraceSource
import D0.Matter.MesonDefectTransferAlgebra
import D0.Matter.MesonDefectTransferOrigin
import D0.Matter.MesonPhasonDomainWalls
import D0.Matter.NeutrinoPhasonWaves
import D0.Matter.NuclearShellContactSRC
import D0.Matter.PMNSSeamTopology
import D0.Matter.PhasonStrainGenerations
import D0.Matter.ProtonReadout306
import D0.Matter.RepresentationCarrier
import D0.Matter.SMHyperchargeRowOwner
import D0.Matter.TerminalFeedbackModes
import D0.Matter.TickS3BaryonAsymmetry
import D0.Matter.TraceDecompositionSigns
import D0.Matter.VectorCurrentCoupling
import D0.Matter.VectorFieldEquation
import D0.Matter.VectorOperatorOrigin
import D0.Matter.YukawaShellOverlapMatrix
import D0.Metrology.PSDPurification
import D0.Metrology.PhasonBragg
import D0.Metrology.Phi2Flux
import D0.Metrology.QuantumLimits
import D0.NoGo.StressTestSuite
import D0.NumberTheory.HurwitzMinimaxPhi
import D0.NumberTheory.HurwitzPhi
import D0.NumberTheory.PhiAdmissibility
import D0.NumberTheory.PhiContinuedFraction
import D0.Passport
import D0.Passport.IceCubePhasonDecoherence
import D0.Phase
import D0.Phi
import D0.Physics.ArchivePhasonDarkMatter
import D0.Physics.GaloisLorentzSignature
import D0.Physics.PhasonFlipInertia
import D0.Physics.QuasiGenerationsInflation
import D0.Physics.QuasicrystalPhenomenology
import D0.Physics.WindowFractionalCharge
import D0.Physics.WindowOffsetChirality
import D0.Probability.ArchiveClassicalGaussianChannel
import D0.Probability.ArchiveFloorWaterFilling
import D0.Probability.EntropyCouplingKernel
import D0.Probability.EntropyFlowJacobian
import D0.Probability.FiniteArchiveMeasure
import D0.Probability.ForgettingChannelCP
import D0.Probability.ForgettingChannelPTP
import D0.Probability.HSTExternalInterface
import D0.Probability.SubgaussianArchive
import D0.RG.OneLoopStructure
import D0.RG.PhiDifference
import D0.Response
import D0.Spectral.AlphaFeshbachDixmierOwner
import D0.Spectral.AlphaProfiniteSpectralTower
import D0.Spectral.AlphaProfiniteTowerNoGo
import D0.Spectral.CriticalAxisM1
import D0.Spectral.DeltaAlphaExact
import D0.Spectral.DeltaAlphaMoment
import D0.Spectral.DeltaAlphaNormalizationNoGo
import D0.Spectral.DeltaAlphaResidueBlocked
import D0.Spectral.DixmierFeshbachFiniteHeatTrace
import D0.Spectral.SeamHolonomy
import D0.Spectral.ZetaResidueAlpha
import D0.Spectral.ZoneMatrixSpectrum
import D0.Spectrum.BranchDefectProjectiveControls
import D0.Spectrum.BranchDefectProjectiveGeneration
import D0.Spectrum.GenerationRays
import D0.Spectrum.GenerationSpectralRays
import D0.Spectrum.GenerationTensorExactness
import D0.Spectrum.Pi0BranchDefectControls
import D0.Spectrum.Pi0BranchDefectGeneration
import D0.Synthesis.BSDRankNullityPassport
import D0.Synthesis.CarrierForcing
import D0.Synthesis.DimensionEightNetwork
import D0.Synthesis.RankCausalCone
import D0.Synthesis.RankCausalConeForcing
import D0.Synthesis.UnitySplitSpacetime
import D0.Synthesis.Z2SpinorCover
import D0.TheoremLedger.ActiveClosureIndex
import D0.TheoremLedger.ClaimMap
import D0.TheoremLedger.ClosedVacuumFeedbackIndex
import D0.TheoremLedger.HardClosureTheoremIndex
import D0.TheoremLedger.ReleaseStatus
import D0.Topology.ArchiveShiftTopology
import D0.Topology.BoundaryBoundary
import D0.Topology.DeloneInstance
import D0.Topology.FiniteCochainNoAxion
import D0.Topology.GradedIncidenceComplex
import D0.Topology.HodgeAlgebraicRealization
import D0.Topology.NoThreeSimplices
import D0.Topology.SimplicialIncidence
import D0.Topology.TilingHull
import D0.Topology.TripartiteComplex
import D0.Topology.WitnessHalting
import D0.Tower.DetectionQuadratic
import D0.Tower.NoExtension
import D0.Traceability.StatusTaxonomy
