#!/usr/bin/env python3
"""Exact analytic joint-vacuum curve for EXP-A4D-JOINT-PALATINI-LOCAL-UNIQUENESS.

This parent certificate exactifies the finite-order diagonal worker #235.

Family (standard solder, L divisible by 4):
    p(x) = sum_r x_r mod 4
    W = (U, I, U^{-1}, I)
    L_0(x) = W_{p(x)}
    L_s(x) = I, s=1,2,3

where U is the Cayley parameterization of the one-parameter Lorentz subgroup
generated by
    Y = J_12 - J_13 + J_23.

The certificate proves, over Q(z):

  * U is Lorentz and U(-z)=U(z)^{-1};
  * the odd plaquette curvature is nonzero for z != 0:
        R(U) = 4 z/(4+3 z^2) Y;
  * the metric Euler covector at standard solder vanishes identically;
  * every independent Role-0 and spatial-role Lorentz edge Euler component
    vanishes identically as a rational function of z;
  * the family is not a pure-gauge image of identity inside the declared
    side-link identity pattern.

Thus it is an exact curved joint vacuum of the unchanged naked star action:
    E_K(eta,K(z)) = 0,   E_Q(eta,K(z)) = 0.

No torsion constraint, new action term, selector, or continuum claim is used.
"""
from itertools import combinations
import sympy as sp

PAIRS = list(combinations(range(4), 2))
PINDEX = {p: i for i, p in enumerate(PAIRS)}
ETA = sp.diag(1, -1, -1, -1)


def check(name, cond):
    if not cond:
        raise AssertionError(name)
    print("PASS_" + name)


def rot(i, j):
    X = sp.zeros(4)
    X[i, j] = 1
    X[j, i] = -1
    return X


def boost(i):
    X = sp.zeros(4)
    X[0, i] = X[i, 0] = 1
    return X


GEN = [boost(1), boost(2), boost(3), rot(1, 2), rot(1, 3), rot(2, 3)]
for X in GEN:
    check("LORENTZ_TANGENT", X.T * ETA + ETA * X == sp.zeros(4))

Y = GEN[3] - GEN[4] + GEN[5]
B = GEN[0] + GEN[1] + GEN[2]
check("Y_CUBIC", sp.expand(Y**3 + 3 * Y) == sp.zeros(4))
check("B_COMMUTES_Y", sp.expand(B * Y - Y * B) == sp.zeros(4))

# ---------------------------------------------------------------------------
# Exact subgroup and curvature
# ---------------------------------------------------------------------------

z = sp.symbols("z", real=True)
I4 = sp.eye(4)
U = sp.simplify((I4 - z * Y / 2).inv() * (I4 + z * Y / 2))
Ui = sp.simplify(U.subs(z, -z))

check("U_INVERSE", (U * Ui - I4).applyfunc(sp.factor) == sp.zeros(4))
check("U_LORENTZ", (U.T * ETA * U - ETA).applyfunc(sp.factor) == sp.zeros(4))
check("U_COMMUTES_B", (U * B - B * U).applyfunc(sp.factor) == sp.zeros(4))

c = sp.simplify(4 * z / (4 + 3 * z**2))
R_U = sp.simplify((U - Ui) / 2)
check("ODD_CURVATURE_EXACT", (R_U - c * Y).applyfunc(sp.factor) == sp.zeros(4))
check("CURVATURE_COEFF_NONZERO_RATIONAL", sp.factor(c) != 0)

# Four-phase pattern. Each Role shift increments p by one.
W = [U, I4, Ui, I4]
Winv = [Ui, I4, U, I4]
SIGMA = [1, 0, -1, 0]

# Plaquettes (0,s) are U,U,U^-1,U^-1 by phase; spatial plaquettes are I.
Pphase = [sp.simplify(W[p] * Winv[(p + 1) % 4]) for p in range(4)]
check("PLAQUETTE_PHASE_0_U", (Pphase[0] - U).applyfunc(sp.factor) == sp.zeros(4))
check("PLAQUETTE_PHASE_1_U", (Pphase[1] - U).applyfunc(sp.factor) == sp.zeros(4))
check("PLAQUETTE_PHASE_2_UI", (Pphase[2] - Ui).applyfunc(sp.factor) == sp.zeros(4))
check("PLAQUETTE_PHASE_3_UI", (Pphase[3] - Ui).applyfunc(sp.factor) == sp.zeros(4))

# ---------------------------------------------------------------------------
# Star-density metric pairing at standard solder
# ---------------------------------------------------------------------------

G2 = sp.zeros(6)
for i, (a, b) in enumerate(PAIRS):
    G2[i, i] = ETA[a, a] * ETA[b, b]

STAR = sp.zeros(6)
for src, (dst, sign) in {
    (0, 1): ((2, 3), -1),
    (0, 2): ((1, 3), +1),
    (0, 3): ((1, 2), -1),
    (1, 2): ((0, 3), +1),
    (1, 3): ((0, 2), -1),
    (2, 3): ((0, 1), +1),
}.items():
    STAR[PINDEX[dst], PINDEX[src]] = sign
check("STAR_SQUARE_MINUS_ID", STAR * STAR == -sp.eye(6))

e = [I4[:, r] for r in range(4)]


def wedge(u, v):
    return sp.Matrix([u[a] * v[b] - u[b] * v[a] for a, b in PAIRS])


def bivector_of_tangent(X):
    M = X * ETA
    return sp.Matrix([M[a, b] for a, b in PAIRS])


def orientation(i, j):
    rest = [k for k in range(4) if k not in (i, j)]
    seq = [i, j] + rest
    inv = sum(seq[p] > seq[q] for p, q in combinations(range(4), 2))
    return -1 if inv % 2 else 1


def star_pair(Bv, Cv):
    return sp.expand((Bv.T * G2 * STAR * Cv)[0])


bY = bivector_of_tangent(Y)

# Every nontrivial cell density is zero because complementary spatial area
# pairs with star(bY) in a boost sector.
for s in (1, 2, 3):
    comp = [i for i in range(4) if i not in (0, s)]
    B0 = wedge(e[comp[0]], e[comp[1]])
    check("CELL_DENSITY_ZERO_%d" % s,
          orientation(0, s) * star_pair(B0, bY) == 0)

# Full 16-component solder/Gram partial: all three faces share one curvature
# scale, and their oriented complementary variations cancel identically.
for role in range(4):
    for comp_idx in range(4):
        total = sp.Integer(0)
        for s in (1, 2, 3):
            u, v = [i for i in range(4) if i not in (0, s)]
            Bvar = sp.zeros(6, 1)
            if role == u:
                Bvar += wedge(e[comp_idx], e[v])
            if role == v:
                Bvar += wedge(e[u], e[comp_idx])
            total += orientation(0, s) * star_pair(Bvar, bY)
        check("METRIC_EULER_ROLE%d_COMP%d" % (role, comp_idx),
              sp.expand(total) == 0)

# ---------------------------------------------------------------------------
# Exact independent-edge connection Euler
# ---------------------------------------------------------------------------

def DR(P, Pinv, dP):
    """D R_P[dP] for R(P)=(P-P^-1)/2."""
    return sp.simplify((dP + Pinv * dP * Pinv) / 2)


def ell_s(s, C):
    # At standard solder this is exactly the (0,s)-face star functional.
    return sp.factor(sp.trace(GEN[s - 1] * C) / 2)


def ell_B(C):
    return sp.factor(sp.trace(B * C) / 2)


# Cross-check the three face functionals on the Lorentz basis.
for s in (1, 2, 3):
    for j, G in enumerate(GEN):
        check("FACE_FUNCTIONAL_%d_%d" % (s, j),
              ell_s(s, G) == (1 if j == s - 1 else 0))

# Role-0 edge. It meets six nontrivial faces. Summing the three complementary
# face functionals gives ell_B. The four-phase pattern plus [B,U]=0 makes the
# two incident base-site contributions cancel exactly.
for p in range(4):
    A, Ai = W[p], Winv[p]
    C, Ci = W[(p + 1) % 4], Winv[(p + 1) % 4]
    D, Di = W[(p - 1) % 4], Winv[(p - 1) % 4]
    Pplus, Pplusi = sp.simplify(A * Ci), sp.simplify(C * Ai)
    Pminus, Pminusi = sp.simplify(D * Ai), sp.simplify(A * Di)
    for j, G in enumerate(GEN):
        dplus = sp.simplify(A * G * Ci)
        dminus = sp.simplify(-D * G * Ai)
        value = sp.cancel(ell_B(
            DR(Pplus, Pplusi, dplus) + DR(Pminus, Pminusi, dminus)
        ))
        check("ROLE0_EDGE_P%d_G%d" % (p, j), value == 0)

# Spatial Role-s edge. Its two nontrivial (0,s) faces cancel as a matrix
# identity for every phase; no commutation assumption is needed.
for p in range(4):
    A, Ai = W[p], Winv[p]
    C, Ci = W[(p + 1) % 4], Winv[(p + 1) % 4]
    D, Di = W[(p - 1) % 4], Winv[(p - 1) % 4]
    Py, Pyi = sp.simplify(D * Ai), sp.simplify(A * Di)
    Px, Pxi = sp.simplify(A * Ci), sp.simplify(C * Ai)
    for s in (1, 2, 3):
        for j, G in enumerate(GEN):
            dPy = sp.simplify(D * G * Ai)
            dPx = sp.simplify(-Px * G)
            value = sp.cancel(ell_s(
                s, DR(Py, Pyi, dPy) + DR(Px, Pxi, dPx)
            ))
            check("SPATIAL_EDGE_P%d_R%d_G%d" % (p, s, j), value == 0)

# Spatial-spatial identity faces contribute a flat forward curl. The two
# appearances of one edge have opposite tangent and D R_I = id.
for s in (1, 2, 3):
    for j, G in enumerate(GEN):
        check("FLAT_SPATIAL_TELESCOPE_R%d_G%d" % (s, j),
              DR(I4, I4, G) + DR(I4, I4, -G) == sp.zeros(4))

# ---------------------------------------------------------------------------
# Non-gauge / exact curved branch guards
# ---------------------------------------------------------------------------

# If all side links are identity on a pure gauge image of flat, the gauge
# function is constant along the three spatial directions. Then L_0 can depend
# only on x_0. Our p=sum x_r pattern violates that: same x_0, different
# spatial sum gives different W phase.
check("NOT_PURE_GAUGE_PHASE_WITNESS", SIGMA[0] != SIGMA[1])

# At z != 0 near identity, the odd curvature coefficient is nonzero.
check("CURVED_NEAR_IDENTITY", sp.limit(c / z, z, 0) == 1)

print("TERMINAL: NAKED-STAR-JOINT-PALATINI-EXACT-DIAGONAL-JOINT-VACUUM-CURVE")
print("RESULT: E_K(eta,K(z))=0 and E_Q(eta,K(z))=0 exactly over Q(z).")
print("RESULT: curvature is nonzero for z != 0 near identity; branch is not pure gauge.")
