import D0.Foundation.CurrentDataFactorization
import D0.Tower.PortPowerExhaustion

/-!
# Detection/scene equivalence: the zone-13 bound is exactly the two-capability bound

The port-power GAP-E route reads an extension alphabet as `D₂^k`, where `k` is the number of
independent primitive detector capabilities. This module proves the exact threshold theorem,
rather than assuming the desired cap:

`all admissible extensions satisfy 9 + 2^k ≤ 13  ↔  capability count ≤ 2`.

The general comparison grammar proves that `n` independent capabilities give exactly `n`
primitive comparisons. The concrete observation model then supplies a third operational history
capability unless detector comparisons factor through current membership/value data. At
capability count `3`, the alphabet `2³=8` is re-admitted and the rival zone is `9+8=17`.

Therefore the global scene-window problem is equivalent, in the port-power route, to one local
typed theorem:

> every primitive M1-admissible detector-layer comparison is history-invariant / factors through
> current data.

The quotient mathematics for that theorem is already closed by `CurrentDataFactorization`; its
M1/detector-layer premise remains the exact open joint.
-/

namespace D0.Synthesis.DetectionSceneBoundEquivalence

open D0.Foundation.GeneralComparisonGrammar
open D0.Foundation.DetectionCapabilityBoundary
open D0.Foundation.CurrentDataFactorization

/-- Port-power upper-bound statement generated by `n` independent detector capabilities. -/
def Zone13BoundAtCapabilityCount (n : ℕ) : Prop :=
  ∀ k : ℕ, 1 ≤ k → k ≤ n → 9 + 2 ^ k ≤ 13

/-- **Exact threshold.** The port-power zone bound holds exactly when the independent capability
count is at most two. -/
theorem zone13Bound_iff_capabilityCount_le_two (n : ℕ) :
    Zone13BoundAtCapabilityCount n ↔ n ≤ 2 := by
  constructor
  · intro h
    by_contra hn
    have h3 : 3 ≤ n := by omega
    have := h 3 (by omega) h3
    norm_num at this
  · intro hn k hk1 hkn
    have hk2 : k ≤ 2 := le_trans hkn hn
    interval_cases k <;> norm_num

/-- Rewriting the threshold through the general comparison grammar: primitive count is exactly
the capability count, so the same iff holds for the number of primitive comparisons. -/
theorem zone13Bound_iff_primitiveCount_le_two (n : ℕ) :
    Zone13BoundAtCapabilityCount
        (Nat.card {c : GenComparison n // Primitive c})
      ↔ Nat.card {c : GenComparison n // Primitive c} ≤ 2 := by
  exact zone13Bound_iff_capabilityCount_le_two _

/-- The intended current-data detector grammar (`n=2`) satisfies the zone-13 bound. -/
theorem two_capabilities_seal_zone13 :
    Zone13BoundAtCapabilityCount 2 :=
  (zone13Bound_iff_capabilityCount_le_two 2).2 (by omega)

/-- Three capabilities reopen the upper bound: the third port admits size `8` and zone `17`. -/
theorem three_capabilities_reopen_zone17 :
    ¬ Zone13BoundAtCapabilityCount 3 := by
  intro h
  have := h 3 (by omega) (by omega)
  norm_num at this

/-- Exact arithmetic witness of the reopened rival. -/
theorem third_port_alphabet_and_zone :
    2 ^ 3 = 8 ∧ 9 + 2 ^ 3 = 17 := by decide

/-- The general grammar has exactly three primitives at capability count three. -/
theorem three_capability_primitive_count :
    Nat.card {c : GenComparison 3 // Primitive c} = 3 :=
  three_capabilities_three_primitives

/-- The concrete history comparison realizes the third primitive atom. -/
theorem history_realizes_third_atom :
    capabilityVector historyComparison = atomicOf (2 : Fin 3)
      ∧ Primitive (capabilityVector historyComparison)
      ∧ OperationalComparison historyComparison :=
  ⟨history_capability_vector, history_is_third_primitive, history_operational⟩

/-- The history comparison is exactly outside the current-data detector quotient. -/
theorem history_outside_current_data_detector :
    ¬ FactorsThroughCurrentData historyComparison :=
  history_not_factor_through_current_data

/-- Positive typed boundary: every comparison explicitly factoring through current data is
history-blind. -/
theorem current_data_detector_excludes_history
    (cmp : Comparison) (h : FactorsThroughCurrentData cmp) :
    ¬ UsesHistory cmp :=
  current_data_factorization_excludes_history cmp h

/-- **Scene consequence of the history no-go.** If history/order remains an independent detector
capability, primitive count is three and the port-power route cannot prove the zone-13 bound;
the size-8/zone-17 rival is admitted. -/
theorem history_capability_reopens_gap_e :
    Nat.card {c : GenComparison 3 // Primitive c} = 3
      ∧ Primitive (capabilityVector historyComparison)
      ∧ ¬ FactorsThroughCurrentData historyComparison
      ∧ ¬ Zone13BoundAtCapabilityCount 3
      ∧ (2 ^ 3 = 8 ∧ 9 + 2 ^ 3 = 17) :=
  ⟨three_capability_primitive_count, history_is_third_primitive,
    history_not_factor_through_current_data, three_capabilities_reopen_zone17,
    third_port_alphabet_and_zone⟩

/-- Capstone: the intended zone bound is equivalent to the two-capability theorem, while the
currently admitted history comparison falsifies that theorem unless detector/memory
stratification is imposed and proved. -/
theorem detection_scene_bound_equivalence :
    (∀ n : ℕ, Zone13BoundAtCapabilityCount n ↔ n ≤ 2)
      ∧ Zone13BoundAtCapabilityCount 2
      ∧ ¬ Zone13BoundAtCapabilityCount 3
      ∧ Nat.card {c : GenComparison 3 // Primitive c} = 3
      ∧ Primitive (capabilityVector historyComparison)
      ∧ ¬ FactorsThroughCurrentData historyComparison
      ∧ (∀ cmp : Comparison,
          FactorsThroughCurrentData cmp → ¬ UsesHistory cmp) :=
  ⟨zone13Bound_iff_capabilityCount_le_two, two_capabilities_seal_zone13,
    three_capabilities_reopen_zone17, three_capability_primitive_count,
    history_is_third_primitive, history_not_factor_through_current_data,
    current_data_detector_excludes_history⟩

end D0.Synthesis.DetectionSceneBoundEquivalence
