import D0.SelfReading.TypedCapacityRawScene
import D0.SelfReading.TypedIncidenceCarriers
import D0.Synthesis.SceneAnisotropyCapacityWeld
import D0.VNext2.Rank3CubicSymmetricFunctions
import Mathlib.Tactic

/-!
# D0-TYPED-SCENE-SELF-RECONSTRUCTION-001

This module closes the first full finite self-reading loop of the scene:

```
capacity types
  -> typed zone carrier V9/V11/V13
  -> typed raw adjacency
  -> typed edge / directed-edge / triangle carriers
  -> rank-3 cubic coefficients
  -> reverse reconstruction of the same zone cardinalities.
```

The forward path contains actual finite types and support equivalences, not a
detached number table. The reverse path is the Diophantine reconstruction
theorem over finite carrier cardinalities.

This is a consistency/fixed-point theorem. It does not claim that the forward
and reverse routes are independent empirical evidence, and it does not promote
the finite rank-3 form to a dimensionful spacetime metric.
-/

namespace D0.Synthesis.TypedSceneSelfReconstruction

open D0.SelfReading.TypedCapacityRawScene
open D0.SelfReading.TypedIncidenceCarriers
open D0.Synthesis.SceneAnisotropyCapacityWeld

/-- Cubic linear coefficient generated by a typed undirected edge carrier. -/
def typedCubicLinearCoeff : ℤ := -(Fintype.card TypedEdge : ℤ)

/-- Cubic constant coefficient generated by a typed triangle carrier. -/
def typedCubicConstantCoeff : ℤ :=
  -(2 * (Fintype.card TypedTriangle : ℤ))

/-- Discriminant of `lambda^3 + p lambda + q` generated from the two typed
incidence carriers. -/
def typedCubicDiscriminant : ℤ :=
  (-4) * typedCubicLinearCoeff ^ 3 -
    27 * typedCubicConstantCoeff ^ 2

/-- **Typed incidence carriers generate the owned rank-3 cubic coefficients.**
No coefficient is inserted separately. -/
theorem typed_cubic_coefficients :
    typedCubicLinearCoeff = -359 ∧
      typedCubicConstantCoeff = -2574 := by
  constructor
  · unfold typedCubicLinearCoeff
    rw [typed_edge_cardinality]
    norm_num
  · unfold typedCubicConstantCoeff
    rw [typed_triangle_cardinality]
    norm_num

/-- The typed carrier coefficients agree with the canonical scene symmetric
function owner. -/
theorem typed_coefficients_align_canonical_owner :
    typedCubicLinearCoeff =
        -(D0.VNext2.Rank3CubicSymmetricFunctions.n₁ *
          D0.VNext2.Rank3CubicSymmetricFunctions.n₂ +
          D0.VNext2.Rank3CubicSymmetricFunctions.n₁ *
          D0.VNext2.Rank3CubicSymmetricFunctions.n₃ +
          D0.VNext2.Rank3CubicSymmetricFunctions.n₂ *
          D0.VNext2.Rank3CubicSymmetricFunctions.n₃) ∧
      -typedCubicConstantCoeff =
        2 * (D0.VNext2.Rank3CubicSymmetricFunctions.n₁ *
          D0.VNext2.Rank3CubicSymmetricFunctions.n₂ *
          D0.VNext2.Rank3CubicSymmetricFunctions.n₃) := by
  have h :=
    D0.VNext2.Rank3CubicSymmetricFunctions.cubic_coefficients
  norm_num [typedCubicLinearCoeff, typedCubicConstantCoeff,
    typed_edge_cardinality, typed_triangle_cardinality,
    D0.VNext2.Rank3CubicSymmetricFunctions.n₁,
    D0.VNext2.Rank3CubicSymmetricFunctions.n₂,
    D0.VNext2.Rank3CubicSymmetricFunctions.n₃] at h ⊢

/-- The discriminant is generated by the typed carriers and agrees with the
canonical rank-3 discriminant owner. -/
theorem typed_cubic_discriminant :
    typedCubicDiscriminant = 6185264 ∧
      (0 : ℤ) < typedCubicDiscriminant := by
  have h :=
    D0.VNext2.Rank3CubicSymmetricFunctions.discriminant_positive
  unfold typedCubicDiscriminant
  rw [show typedCubicLinearCoeff = -359 from typed_cubic_coefficients.1]
  rw [show typedCubicConstantCoeff = -2574 from typed_cubic_coefficients.2]
  exact h

/-- The two incidence cardinalities reconstruct the same zone capacities from
which the typed graph was built. -/
theorem incidence_reverse_returns_source :
    (Fintype.card V9T, Fintype.card V11T, Fintype.card V13T) =
      (9, 11, 13) :=
  typed_incidence_reconstructs_zone_capacities

/-- **The downstream typed passport is genuinely reverse-complete.**
This is the load-bearing universal statement: every ordered positive triple of
finite carrier types with the same edge and triangle carrier cardinalities is
forced back to `(9,11,13)`.  It prevents the master theorem from being only a
re-bundling of facts about the already-known source types. -/
theorem incidence_reverse_universal :
    ∀ (A B C : Type) [Fintype A] [Fintype B] [Fintype C],
      0 < Fintype.card A →
      Fintype.card A ≤ Fintype.card B →
      Fintype.card B ≤ Fintype.card C →
      Fintype.card (TripartiteEdge A B C) = Fintype.card TypedEdge →
      Fintype.card (TripartiteTriangle A B C) =
        Fintype.card TypedTriangle →
      (Fintype.card A, Fintype.card B, Fintype.card C) =
        (Fintype.card V9T, Fintype.card V11T, Fintype.card V13T) := by
  intro A B C _ _ _ hA hAB hBC hE hT
  rw [typed_edge_cardinality] at hE
  rw [typed_triangle_cardinality] at hT
  calc
    (Fintype.card A, Fintype.card B, Fintype.card C) =
        (9, 11, 13) :=
      reconstruct_type_cardinalities_from_incidence A B C hA hAB hBC hE hT
    _ =
        (Fintype.card V9T, Fintype.card V11T, Fintype.card V13T) := by
      symm
      exact incidence_reverse_returns_source

/-- Equivalent universal reverse statement with the canonical numeric target.
It exhibits the actual Diophantine content without routing through the source
instance. -/
theorem incidence_reverse_universal_numeric :
    ∀ (A B C : Type) [Fintype A] [Fintype B] [Fintype C],
      0 < Fintype.card A →
      Fintype.card A ≤ Fintype.card B →
      Fintype.card B ≤ Fintype.card C →
      Fintype.card (TripartiteEdge A B C) = Fintype.card TypedEdge →
      Fintype.card (TripartiteTriangle A B C) =
        Fintype.card TypedTriangle →
      (Fintype.card A, Fintype.card B, Fintype.card C) =
        (9, 11, 13) := by
  intro A B C _ _ _ hA hAB hBC hE hT
  have hSource :=
    incidence_reverse_universal A B C hA hAB hBC hE hT
  exact hSource.trans incidence_reverse_returns_source

/-- The upstream capacity-defect passport and the downstream incidence
passport return the same cardinality triple. -/
theorem capacity_and_incidence_routes_agree :
    ((Fintype.card V11T : ℤ) - (Fintype.card D0.Dyad : ℤ),
      (Fintype.card V11T : ℤ),
      (Fintype.card V11T : ℤ) + (Fintype.card D0.Dyad : ℤ)) =
        ((Fintype.card V9T : ℤ),
          (Fintype.card V11T : ℤ),
          (Fintype.card V13T : ℤ)) ∧
    (Fintype.card V9T, Fintype.card V11T, Fintype.card V13T) =
      (9, 11, 13) :=
  ⟨capacity_pair_recovers_typed_sizes,
    incidence_reverse_returns_source⟩

/-- Negative control: the typed edge carrier alone does not reconstruct the
source, even though the full edge+triangle pair does. -/
theorem self_reconstruction_requires_two_incidence_faces :
    Fintype.card (TripartiteEdge (Fin 7) (Fin 10) (Fin 17)) =
        Fintype.card TypedEdge ∧
      Fintype.card (TripartiteTriangle (Fin 1) (Fin 3) (Fin 429)) =
        Fintype.card TypedTriangle ∧
      ((7, 10, 17) : ℕ × ℕ × ℕ) ≠
        (Fintype.card V9T, Fintype.card V11T, Fintype.card V13T) ∧
      ((1, 3, 429) : ℕ × ℕ × ℕ) ≠
        (Fintype.card V9T, Fintype.card V11T, Fintype.card V13T) := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · rw [typed_edge_cardinality]
    exact edge_carrier_alone_not_enough.1
  · rw [typed_triangle_cardinality]
    exact triangle_carrier_alone_not_enough.1
  · rw [incidence_reverse_returns_source]
    decide
  · rw [incidence_reverse_returns_source]
    decide

/-- **Typed scene self-reconstruction loop (bundle).** -/
theorem typed_scene_self_reconstruction :
    Fintype.card TypedVertex = 33 ∧
    Fintype.card TypedEdge = 359 ∧
    Fintype.card TypedDirectedEdge = 718 ∧
    Fintype.card TypedTriangle = 1287 ∧
    typedCubicLinearCoeff = -359 ∧
    typedCubicConstantCoeff = -2574 ∧
    typedCubicDiscriminant = 6185264 ∧
    ((Fintype.card V11T : ℤ) - (Fintype.card D0.Dyad : ℤ),
      (Fintype.card V11T : ℤ),
      (Fintype.card V11T : ℤ) + (Fintype.card D0.Dyad : ℤ)) =
        ((Fintype.card V9T : ℤ),
          (Fintype.card V11T : ℤ),
          (Fintype.card V13T : ℤ)) ∧
    (Fintype.card V9T, Fintype.card V11T, Fintype.card V13T) =
      (9, 11, 13) ∧
    (∀ (A B C : Type) [Fintype A] [Fintype B] [Fintype C],
      0 < Fintype.card A →
      Fintype.card A ≤ Fintype.card B →
      Fintype.card B ≤ Fintype.card C →
      Fintype.card (TripartiteEdge A B C) = Fintype.card TypedEdge →
      Fintype.card (TripartiteTriangle A B C) =
        Fintype.card TypedTriangle →
      (Fintype.card A, Fintype.card B, Fintype.card C) =
        (Fintype.card V9T, Fintype.card V11T, Fintype.card V13T)) ∧
    (∀ i j : TypedVertex,
      D0.SelfReading.RawSceneGraph.Aadj
        (typedEquivRaw i) (typedEquivRaw j) = typedAdj i j) ∧
    (∀ (σ : TypedVertex ≃ TypedVertex),
      (∀ x, typedZone (σ x) = typedZone x) →
      ∀ i j, typedAdj (σ i) (σ j) = typedAdj i j) :=
  ⟨typed_cardinality,
    typed_edge_cardinality,
    typed_directed_edge_cardinality,
    typed_triangle_cardinality,
    typed_cubic_coefficients.1,
    typed_cubic_coefficients.2,
    typed_cubic_discriminant.1,
    capacity_pair_recovers_typed_sizes,
    incidence_reverse_returns_source,
    incidence_reverse_universal,
    adjacency_typedEquivRaw,
    adjacency_invariant_under_zone_preserving_equiv⟩

end D0.Synthesis.TypedSceneSelfReconstruction
