import Mathlib.Tactic
import D0.Geometry.ArchiveCARDegreePreserving
import D0.Geometry.ArchiveFockIntrinsicCommutant

/-!
# Unital associative envelope of the CAR bilinears

`E_sr = c_s† c_r`. Every integer linear combination of these bilinears kills
the vacuum column, so the linear span is not 70-dimensional.

Products are different. The number projectors

`P_T = ∏_{r∈T} n_r ∏_{r∉T} (I - n_r)`

equal `|T⟩⟨T|` and therefore lie in the unital algebra generated by the
bilinears. The owned count of all degree-block endomorphisms is

`1² + 4² + 6² + 4² + 1² = 70`.

That count is this associative envelope, not a gauge group. The linear span
of the generators is a different, smaller object.
-/

namespace D0.Geometry

open D0
open RoleFockPermutation

def diagonalOf (p : ArchiveFockState → ℤ) (bra ket : ArchiveFockState) : ℤ :=
  if bra = ket then p bra else 0

theorem fockMatMul_diagonal (p q : ArchiveFockState → ℤ) (bra ket : ArchiveFockState) :
    fockMatMul (diagonalOf p) (diagonalOf q) bra ket =
      if bra = ket then p bra * q bra else 0 := by
  classical
  unfold fockMatMul diagonalOf
  by_cases h : bra = ket
  · subst h
    rw [Finset.sum_eq_single bra]
    · simp
    · intro mid _ hmid
      rw [if_neg hmid]
      exact mul_zero (if bra = mid then p bra else 0)
    · intro hnot
      exact (hnot (Finset.mem_univ bra)).elim
  · rw [if_neg h]
    apply Finset.sum_eq_zero
    intro mid _
    by_cases hbm : bra = mid
    · subst hbm
      rw [if_pos rfl, if_neg h]
      exact mul_zero (p bra)
    · rw [if_neg hbm]
      exact zero_mul (if mid = ket then q mid else 0)

def occFactor (T : ArchiveFockState) (r : Role) (s : ArchiveFockState) : ℤ :=
  if T r = true then occupationBit r s else 1 - occupationBit r s

theorem fockNumberInt_diagonal (r : Role) (bra ket : ArchiveFockState) :
    fockNumberInt r bra ket = diagonalOf (occupationBit r) bra ket := by
  simp [fockNumberInt_eq_occupation, diagonalOf]

theorem complementNumber_diagonal (r : Role) (bra ket : ArchiveFockState) :
    fockIdentityInt bra ket - fockNumberInt r bra ket =
      diagonalOf (fun s => 1 - occupationBit r s) bra ket := by
  classical
  simp only [fockIdentityInt, fockNumberInt_diagonal, diagonalOf]
  by_cases h : bra = ket
  · simp [h]
  · simp [h]

theorem numberFactor_diagonal (T : ArchiveFockState) (r : Role)
    (bra ket : ArchiveFockState) :
    (if T r = true then fockNumberInt r bra ket
      else fockIdentityInt bra ket - fockNumberInt r bra ket) =
      diagonalOf (occFactor T r) bra ket := by
  classical
  by_cases hT : T r = true
  · have hfun : occFactor T r = occupationBit r := by
      funext s
      simp [occFactor, hT]
    simp [hT, fockNumberInt_diagonal, hfun]
  · have hfun : occFactor T r = fun s => 1 - occupationBit r s := by
      funext s
      simp [occFactor, hT]
    simp [hT, complementNumber_diagonal, hfun]

def applyNumber (T : ArchiveFockState) (r : Role)
    (M : ArchiveFockState → ArchiveFockState → ℤ) :
    ArchiveFockState → ArchiveFockState → ℤ :=
  fockMatMul
    (fun bra ket =>
      if T r = true then fockNumberInt r bra ket
      else fockIdentityInt bra ket - fockNumberInt r bra ket) M

theorem applyNumber_diagonal (T : ArchiveFockState) (r : Role)
    (p : ArchiveFockState → ℤ) (bra ket : ArchiveFockState) :
    applyNumber T r (diagonalOf p) bra ket =
      if bra = ket then occFactor T r bra * p bra else 0 := by
  classical
  unfold applyNumber
  have hfac : (fun bra ket =>
      if T r = true then fockNumberInt r bra ket
      else fockIdentityInt bra ket - fockNumberInt r bra ket) =
      diagonalOf (occFactor T r) := by
    funext b k
    exact numberFactor_diagonal T r b k
  rw [hfac]
  simpa [mul_comm] using fockMatMul_diagonal (occFactor T r) p bra ket

theorem identity_diagonal (bra ket : ArchiveFockState) :
    fockIdentityInt bra ket = diagonalOf (fun _ => 1) bra ket := by
  simp [fockIdentityInt, diagonalOf]

/-- `P_T`, with roles ordered `A,B,C,D`. -/
def occupationProjector (T : ArchiveFockState) :
    ArchiveFockState → ArchiveFockState → ℤ :=
  applyNumber T D (applyNumber T C (applyNumber T B (applyNumber T A fockIdentityInt)))

theorem occupationProjector_diagonal (T bra ket : ArchiveFockState) :
    occupationProjector T bra ket =
      if bra = ket then
        occFactor T A bra * occFactor T B bra * occFactor T C bra * occFactor T D bra
      else 0 := by
  classical
  unfold occupationProjector
  have hI : fockIdentityInt = diagonalOf (fun _ => (1 : ℤ)) := by
    funext b k
    exact identity_diagonal b k
  have hstep :
      ∀ (r : Role) (p : ArchiveFockState → ℤ),
        applyNumber T r (diagonalOf p) =
          diagonalOf (fun s => occFactor T r s * p s) := by
    intro r p
    funext b k
    exact applyNumber_diagonal T r p b k
  rw [hI, hstep A (fun _ => (1 : ℤ))]
  rw [hstep B (fun s => occFactor T A s * 1)]
  rw [hstep C (fun s => occFactor T B s * (occFactor T A s * 1))]
  rw [hstep D (fun s =>
    occFactor T C s * (occFactor T B s * (occFactor T A s * 1)))]
  simp [diagonalOf, mul_assoc, mul_left_comm, mul_comm]

theorem occFactor_one (T : ArchiveFockState) (r : Role) : occFactor T r T = 1 := by
  unfold occFactor occupationBit
  by_cases h : T r = true <;> simp [h]

theorem occFactor_zero (T bra : ArchiveFockState) (r : Role) (hr : bra r ≠ T r) :
    occFactor T r bra = 0 := by
  unfold occFactor occupationBit
  cases hT : T r <;> cases hb : bra r <;> simp_all

theorem occProduct_indicator (T bra : ArchiveFockState) :
    occFactor T A bra * occFactor T B bra * occFactor T C bra * occFactor T D bra =
      if bra = T then 1 else 0 := by
  classical
  by_cases h : bra = T
  · subst h
    simp [occFactor_one]
  · have hrole : ∃ r : Role, bra r ≠ T r := by
      by_contra hnone
      push Not at hnone
      apply h
      funext r
      exact hnone r
    obtain ⟨r, hr⟩ := hrole
    have hzero : occFactor T r bra = 0 := occFactor_zero T bra r hr
    have hrole4 : r = A ∨ r = B ∨ r = C ∨ r = D := by
      rcases r with ⟨i, j⟩
      fin_cases i <;> fin_cases j <;> simp [A, B, C, D]
    rcases hrole4 with hrA | hrB | hrC | hrD
    · rw [hrA] at hzero
      simp [hzero, h]
    · rw [hrB] at hzero
      simp [hzero, h]
    · rw [hrC] at hzero
      simp [hzero, h]
    · rw [hrD] at hzero
      simp [hzero, h]

/-- `P_T = |T⟩⟨T|`. -/
theorem occupationProjector_matrixUnit (T bra ket : ArchiveFockState) :
    occupationProjector T bra ket = if bra = T ∧ ket = T then 1 else 0 := by
  classical
  rw [occupationProjector_diagonal]
  by_cases h : bra = ket
  · subst h
    simp [occProduct_indicator]
  · have hnot : ¬ (bra = T ∧ ket = T) := by
      intro hboth
      exact h (hboth.1.trans hboth.2.symm)
    simp [h, hnot]

theorem carAnnihilateInt_vacuum (r : Role) (bra : ArchiveFockState) :
    carAnnihilateInt r bra fockVacuumState = 0 := by
  simp [carAnnihilateInt, fockVacuumState]

theorem carEndInt_vacuum_column (s r : Role) (bra : ArchiveFockState) :
    carEndInt s r bra fockVacuumState = 0 := by
  classical
  unfold carEndInt
  refine Finset.sum_eq_zero ?_
  intro mid _
  simp [carAnnihilateInt_vacuum]

/-- The linear span of `{E_sr}` does not contain `P_∅ = |0⟩⟨0|`. -/
theorem carEnd_linear_span_misses_vacuum_projector (a : Role → Role → ℤ) :
    (fun bra ket => ∑ s : Role, ∑ r : Role, a s r * carEndInt s r bra ket) ≠
      occupationProjector fockVacuumState := by
  intro h
  have hvac := congrFun (congrFun h fockVacuumState) fockVacuumState
  simp only [carEndInt_vacuum_column, mul_zero, Finset.sum_const_zero] at hvac
  have hproj := occupationProjector_matrixUnit fockVacuumState fockVacuumState
    fockVacuumState
  simp at hproj
  rw [hproj] at hvac
  exact zero_ne_one hvac

/-- Dimension of `⊕_k End(Λ^k)`. This is the unital associative count, not the
linear span of the bilinears. -/
theorem car_unital_envelope_dimension :
    Fintype.card {s : ArchiveFockState // fockDegree s = 0} ^ 2 +
      Fintype.card {s : ArchiveFockState // fockDegree s = 1} ^ 2 +
      Fintype.card {s : ArchiveFockState // fockDegree s = 2} ^ 2 +
      Fintype.card {s : ArchiveFockState // fockDegree s = 3} ^ 2 +
      Fintype.card {s : ArchiveFockState // fockDegree s = 4} ^ 2 = 70 :=
  degreePreservingEndomorphismDimension

end D0.Geometry
