import D0.Cosmology.ArchiveConvexity
import D0.Cosmology.DarkArchiveTransfer
import D0.Evolution.PhiFractalTickDynamics
import D0.Extensions.ArchiveCoordinateExtension
import D0.IM.FractalTick
import Mathlib.Tactic

/-!
# Self-unfolding observable relations

This module does not declare an internal coordinate to be astronomical redshift. It first asks the
strictly smaller and falsifiable question: if time, relative depth, scale growth, and relative
archive growth are read from one registered refinement index, which relations survive after that
index is eliminated?

The answer is exact. For an emission registered at depth `e` and an observation registered at
depth `o`, the internal comparison is `1 + zD0 = phi^(o-e)`. Repeating the observation one tick
later with the same emission record gives

`1 + zD0' = phi * (1 + zD0)` and `Delta zD0 = (phi-1) * (1 + zD0)`.

At the origin, the same quantity is the already-owned relative archive growth
`archiveGrowth n = phi^n - 1`; its increment, the internal redshift drift, and the metric-scale
increment are literally the same object. Meanwhile the active time ladder contracts by `phi^-1`,
so one refinement step expands the depth comparison by the inverse of the time-retention weight.

This removes an internal degree of freedom without crossing the external-observation firewall.
`ArchiveCoordinateExtension.coordinate_cocycle_divergent` remains load-bearing: the phi-depth
coordinate and an integer coordinate already disagree at one tick, so identifying `zD0` with
measured astronomical redshift still requires a preregistered physical comparison protocol.
-/

namespace D0.Cosmology.SelfUnfoldingObservableRelations

open D0
open D0.Cosmology
open D0.Cosmology.DarkArchiveTransfer
open D0.Evolution.PhiFractalTickDynamics
open D0.Extensions.ArchiveCoordinateExtension
open D0.IM

/-- Relative refinement depth between an emission record and a later observation record. -/
def depthGap (observerDepth emitterDepth : Nat) : Nat :=
  observerDepth - emitterDepth

/-- Internal metric-scale readout generated by refinement depth. -/
noncomputable def internalScale (n : Nat) : Real :=
  phi ^ n

/-- Positive multiplicative comparison attached to two registered depths. -/
noncomputable def onePlusInternalRedshift
    (observerDepth emitterDepth : Nat) : Real :=
  phi ^ depthGap observerDepth emitterDepth

/-- Additive internal redshift coordinate. This is not identified with an astronomical observable. -/
noncomputable def internalRedshift
    (observerDepth emitterDepth : Nat) : Real :=
  onePlusInternalRedshift observerDepth emitterDepth - 1

/-- Two independent registrations of the same emission record, separated by one observer tick. -/
structure RepeatedDepthDetection where
  emitterDepth : Nat
  firstObserverDepth : Nat
  emission_precedes_first : emitterDepth ≤ firstObserverDepth

/-- Redshift drift detected by comparing the two registered observations. -/
noncomputable def internalRedshiftDrift (d : RepeatedDepthDetection) : Real :=
  internalRedshift (d.firstObserverDepth + 1) d.emitterDepth -
    internalRedshift d.firstObserverDepth d.emitterDepth

/-- Metric-scale increment of one refinement step. -/
noncomputable def internalScaleIncrement (n : Nat) : Real :=
  internalScale (n + 1) - internalScale n

/-- Relative-archive increment of one refinement step. -/
noncomputable def archiveGrowthIncrement (n : Nat) : Real :=
  archiveGrowth (n + 1) - archiveGrowth n

/-- Dynamical visible measure inherited from the conserved tick, not from carrier dimension. -/
noncomputable def dynamicVisibleShare (n : Nat) : Real :=
  phi⁻¹ ^ n

/-- Dynamical archived measure accumulated after `n` ticks. -/
noncomputable def dynamicArchiveShare (n : Nat) : Real :=
  1 - dynamicVisibleShare n

theorem depthGap_composes {emitterDepth middleDepth observerDepth : Nat}
    (hem : emitterDepth ≤ middleDepth)
    (hmo : middleDepth ≤ observerDepth) :
    depthGap observerDepth emitterDepth =
      depthGap observerDepth middleDepth + depthGap middleDepth emitterDepth := by
  unfold depthGap
  omega

/-- Relative scale is functorial along composable registered depth comparisons. -/
theorem onePlusInternalRedshift_cocycle
    {emitterDepth middleDepth observerDepth : Nat}
    (hem : emitterDepth ≤ middleDepth)
    (hmo : middleDepth ≤ observerDepth) :
    onePlusInternalRedshift observerDepth emitterDepth =
      onePlusInternalRedshift observerDepth middleDepth *
        onePlusInternalRedshift middleDepth emitterDepth := by
  rw [onePlusInternalRedshift, onePlusInternalRedshift, onePlusInternalRedshift,
    depthGap_composes hem hmo, pow_add]

theorem onePlusInternalRedshift_pos (observerDepth emitterDepth : Nat) :
    0 < onePlusInternalRedshift observerDepth emitterDepth := by
  unfold onePlusInternalRedshift
  exact pow_pos (by linarith [phi_gt_one]) _

theorem onePlusInternalRedshift_eq_one_add
    (observerDepth emitterDepth : Nat) :
    onePlusInternalRedshift observerDepth emitterDepth =
      1 + internalRedshift observerDepth emitterDepth := by
  unfold internalRedshift
  ring

/-- Repeating the same emission comparison one tick later multiplies `1+zD0` by `phi`. -/
theorem repeated_detection_one_step
    (d : RepeatedDepthDetection) :
    onePlusInternalRedshift (d.firstObserverDepth + 1) d.emitterDepth =
      phi * onePlusInternalRedshift d.firstObserverDepth d.emitterDepth := by
  have hgap : depthGap (d.firstObserverDepth + 1) d.emitterDepth =
      depthGap d.firstObserverDepth d.emitterDepth + 1 := by
    have he := d.emission_precedes_first
    unfold depthGap
    omega
  rw [onePlusInternalRedshift, onePlusInternalRedshift, hgap, pow_succ]
  ring

/-- **Internal redshift-drift law after eliminating depth.** -/
theorem internal_redshift_drift_relation (d : RepeatedDepthDetection) :
    internalRedshiftDrift d =
      (phi - 1) * (1 + internalRedshift d.firstObserverDepth d.emitterDepth) := by
  unfold internalRedshiftDrift internalRedshift
  rw [repeated_detection_one_step]
  ring

/-- A free rival one-step multiplier is impossible once the same registered comparison protocol is
fixed: its value is already `phi` at the zeroth comparison. -/
theorem one_step_generator_unique (q : Real)
    (h : ∀ n : Nat,
      onePlusInternalRedshift (n + 1) 0 =
        q * onePlusInternalRedshift n 0) :
    q = phi := by
  have h0 := h 0
  norm_num [onePlusInternalRedshift, depthGap] at h0
  linarith

/-- From the origin, internal redshift and relative archive growth are the same function of the
shared refinement depth. -/
theorem origin_redshift_eq_archive_growth (n : Nat) :
    internalRedshift n 0 = archiveGrowth n := by
  simp [internalRedshift, onePlusInternalRedshift, depthGap, archiveGrowth]

/-- Metric-scale and relative-archive increments are one and the same refinement increment. -/
theorem scale_increment_eq_archive_growth_increment (n : Nat) :
    internalScaleIncrement n = archiveGrowthIncrement n := by
  unfold internalScaleIncrement archiveGrowthIncrement internalScale archiveGrowth
  ring

/-- For two origin-based observations, redshift drift is exactly the archive-growth increment. -/
theorem origin_redshift_drift_eq_archive_growth_increment (n : Nat) :
    internalRedshift (n + 1) 0 - internalRedshift n 0 =
      archiveGrowthIncrement n := by
  rw [origin_redshift_eq_archive_growth, origin_redshift_eq_archive_growth]
  rfl

/-- Therefore internal redshift drift, metric expansion increment, and archive-growth increment
obey one parameter-free equality. -/
theorem drift_scale_archive_same_increment (n : Nat) :
    internalRedshift (n + 1) 0 - internalRedshift n 0 =
      internalScaleIncrement n
      ∧ internalScaleIncrement n = archiveGrowthIncrement n := by
  refine ⟨?_, scale_increment_eq_archive_growth_increment n⟩
  rw [origin_redshift_drift_eq_archive_growth_increment,
    ← scale_increment_eq_archive_growth_increment]

/-- The dynamical tick shares partition unity at every depth. -/
theorem dynamic_shares_partition_unity (n : Nat) :
    dynamicVisibleShare n + dynamicArchiveShare n = 1 := by
  simp [dynamicArchiveShare, dynamicVisibleShare]

/-- Eliminating depth also fixes the dynamical archive measure as a function of the internal
redshift coordinate: `darkDynamic = zD0/(1+zD0)`. -/
theorem dynamic_archive_share_eq_redshift_fraction (n : Nat) :
    dynamicArchiveShare n =
      internalRedshift n 0 / (1 + internalRedshift n 0) := by
  rw [origin_redshift_eq_archive_growth]
  unfold dynamicArchiveShare dynamicVisibleShare archiveGrowth
  rw [inv_pow]
  have hp : phi ^ n ≠ 0 := pow_ne_zero n (ne_of_gt (by linarith [phi_gt_one]))
  field_simp [hp]
  ring

/-- The first dynamical archive share is the golden trace fraction `phi^-2 = 2-phi`. -/
theorem first_dynamic_archive_share_eq_golden_trace :
    dynamicArchiveShare 1 = 2 - phi := by
  calc
    dynamicArchiveShare 1 = 1 - phi⁻¹ := by
      simp [dynamicArchiveShare, dynamicVisibleShare]
    _ = phi⁻¹ ^ 2 := by
      linarith [tick_weight_satisfies_split]
    _ = primitiveRoot ^ 2 := by rw [phi_inv_eq_primitiveRoot]
    _ = 2 - phi := tick_trace_fraction

/-- The static `3/30` carrier-count share `10/11` is not the first-step dynamical archive measure.
This prevents a dimension count from being silently promoted to a physical/dynamical percentage. -/
theorem dynamic_measure_ne_static_dimension_share :
    dynamicArchiveShare 1 ≠ (darkShare : Real) := by
  rw [first_dynamic_archive_share_eq_golden_trace]
  norm_num [darkShare]
  intro h
  have hphi : phi = (12 : Real) / 11 := by linarith
  have hs := phi_sq
  rw [hphi] at hs
  norm_num at hs

/-- The time-retention step and the expansion step are reciprocal readings of the same generator. -/
theorem tick_expansion_reciprocity (n : Nat) :
    ladderAmount (n + 1) = ladderAmount n * phi⁻¹
      ∧ onePlusInternalRedshift (n + 1) 0 =
          phi * onePlusInternalRedshift n 0
      ∧ phi * phi⁻¹ = 1 := by
  refine ⟨archive_tick_multiplies_by_phi_inv n, ?_, ?_⟩
  · simpa using repeated_detection_one_step
      { emitterDepth := 0,
        firstObserverDepth := n,
        emission_precedes_first := Nat.zero_le n }
  · exact mul_inv_cancel₀ (ne_of_gt (by linarith [phi_gt_one]))

/-- The integer-tick rival already differs from the phi-depth comparison after one step. Hence the
internal elimination theorem does not, by itself, identify its coordinate with physical redshift. -/
theorem physical_redshift_identification_not_internal :
    internalRedshift 1 0 ≠ 1 := by
  simpa [internalRedshift, onePlusInternalRedshift, depthGap] using
    coordinate_cocycle_divergent

/-- Capstone: one self-unfolding step jointly fixes time contraction, depth expansion, redshift
drift, and relative archive growth, while the physical redshift identification remains open. -/
theorem self_unfolding_observable_relations :
    (∀ d : RepeatedDepthDetection,
      internalRedshiftDrift d =
        (phi - 1) * (1 + internalRedshift d.firstObserverDepth d.emitterDepth))
      ∧ (∀ n : Nat,
        internalRedshift n 0 = archiveGrowth n)
      ∧ (∀ n : Nat,
        internalRedshift (n + 1) 0 - internalRedshift n 0 =
          internalScaleIncrement n
          ∧ internalScaleIncrement n = archiveGrowthIncrement n)
      ∧ (∀ n : Nat,
        ladderAmount (n + 1) = ladderAmount n * phi⁻¹
          ∧ onePlusInternalRedshift (n + 1) 0 =
              phi * onePlusInternalRedshift n 0
          ∧ phi * phi⁻¹ = 1)
      ∧ (∀ n : Nat,
        dynamicArchiveShare n =
          internalRedshift n 0 / (1 + internalRedshift n 0))
      ∧ dynamicArchiveShare 1 ≠ (darkShare : Real)
      ∧ internalRedshift 1 0 ≠ 1 :=
  ⟨internal_redshift_drift_relation,
    origin_redshift_eq_archive_growth,
    drift_scale_archive_same_increment,
    tick_expansion_reciprocity,
    dynamic_archive_share_eq_redshift_fraction,
    dynamic_measure_ne_static_dimension_share,
    physical_redshift_identification_not_internal⟩

end D0.Cosmology.SelfUnfoldingObservableRelations
