import Mathlib.Tactic
import D0.Matter.HyperchargeFlowLattice
import D0.Matter.DSigmaRoleTransitionGraph
import D0.Matter.DSigmaRoleCycleCarrierNoGo

/-!
# Canonical zone-homogeneous circulation line on K(9,11,13)

The existing DΣ carrier no-go proves that five operational roles cannot be
canonically injected into five distinct primitive triangle-orbit classes:
the oriented triangles form a single Aut(K(9,11,13))-orbit.

That does NOT imply that the graph has no canonical circulation object.
If a directed current is required only to be invariant under within-zone
relabelings, then it is determined by three rational edge weights

  x : V9 -> V11,
  y : V11 -> V13,
  z : V13 -> V9.

Kirchhoff conservation at one vertex of each zone gives

  11 x = 13 z,
  13 y =  9 x,
   9 z = 11 y.

These equations have a one-dimensional solution space, generated by

  (x,y,z) = (13,9,11).

Thus the complete tripartite scene DOES own a canonical Aut-invariant
circulation line, unique up to overall scalar/sign.  This is compatible with
the old no-go: the line is one geometric carrier, not five distinct orbit
classes.

A later construction may tensor the canonical five-state DΣ role cycle with
this one-dimensional line.  This module proves only the geometric factor; it
does not yet construct a physical role->Weyl readout.
-/

namespace D0.Matter.CanonicalZoneCirculation

/-- Zone-homogeneous oriented current weights:
x on V9->V11, y on V11->V13, z on V13->V9. -/
structure ZoneFlow where
  x : ℚ
  y : ℚ
  z : ℚ

/-- Kirchhoff conservation for a zone-homogeneous current. -/
def DivergenceFree (J : ZoneFlow) : Prop :=
  11 * J.x = 13 * J.z ∧
  13 * J.y = 9 * J.x ∧
  9 * J.z = 11 * J.y

/-- The primitive positive generator. -/
def primitiveCirculation : ZoneFlow := ⟨13, 9, 11⟩

theorem primitiveCirculation_divergenceFree :
    DivergenceFree primitiveCirculation := by
  norm_num [DivergenceFree, primitiveCirculation]

/-- Every rational zone-homogeneous divergence-free current is a scalar
multiple of the primitive vector (13,9,11). -/
theorem divergenceFree_classification
    (J : ZoneFlow) (hJ : DivergenceFree J) :
    ∃ t : ℚ,
      J.x = 13 * t ∧
      J.y = 9 * t ∧
      J.z = 11 * t := by
  rcases hJ with ⟨hA, hB, hC⟩
  refine ⟨J.x / 13, ?_, ?_, ?_⟩
  · ring
  · linarith
  · linarith

/-- Conversely every scalar multiple of (13,9,11) is divergence-free. -/
theorem scalar_primitive_divergenceFree (t : ℚ) :
    DivergenceFree ⟨13 * t, 9 * t, 11 * t⟩ := by
  constructor <;> norm_num <;> ring

/-- Exact iff characterization of the invariant circulation line. -/
theorem divergenceFree_iff_primitive_line (J : ZoneFlow) :
    DivergenceFree J ↔
      ∃ t : ℚ,
        J.x = 13 * t ∧
        J.y = 9 * t ∧
        J.z = 11 * t := by
  constructor
  · exact divergenceFree_classification J
  · rintro ⟨t, rfl, rfl, rfl⟩
    exact scalar_primitive_divergenceFree t

/-- Nonzero divergence-free currents have no vanishing component; hence their
orientation is globally determined up to the single overall sign/scalar. -/
theorem nonzero_flow_all_components_nonzero
    (J : ZoneFlow) (hJ : DivergenceFree J)
    (hnz : J.x ≠ 0 ∨ J.y ≠ 0 ∨ J.z ≠ 0) :
    J.x ≠ 0 ∧ J.y ≠ 0 ∧ J.z ≠ 0 := by
  obtain ⟨t, hx, hy, hz⟩ := divergenceFree_classification J hJ
  have ht : t ≠ 0 := by
    intro ht0
    subst t
    simp at hx hy hz
    rcases hnz with h | h | h
    · exact h hx
    · exact h hy
    · exact h hz
  constructor
  · rw [hx]
    exact mul_ne_zero (by norm_num) ht
  constructor
  · rw [hy]
    exact mul_ne_zero (by norm_num) ht
  · rw [hz]
    exact mul_ne_zero (by norm_num) ht

/-- The geometric factor is one-dimensional while the DΣ role factor has five
states.  This avoids, rather than contradicts, the old Fin 5 -> Fin 1
injection no-go: geometry supplies one line and role space supplies the five
internal states. -/
theorem role_cycle_times_circulation_dimension_bookkeeping :
    Fintype.card D0.Matter.DSigmaRoleTransitionGraph.Role = 5 ∧
    D0.Matter.DSigmaRoleCycleCarrierNoGo.numCanonicalPrimitiveOrbits = 1 := by
  exact ⟨D0.Matter.DSigmaRoleTransitionGraph.dsigma_transition_graph_has_five_nodes,
    rfl⟩

/-- Capstone: K(9,11,13) owns a unique zone-homogeneous divergence-free
circulation line generated by (13,9,11), even though it does not own five
distinct primitive cycle-orbit classes. -/
theorem canonical_zone_circulation_line :
    DivergenceFree primitiveCirculation ∧
    (∀ J : ZoneFlow,
      DivergenceFree J ↔
        ∃ t : ℚ,
          J.x = 13 * t ∧
          J.y = 9 * t ∧
          J.z = 11 * t) ∧
    Fintype.card D0.Matter.DSigmaRoleTransitionGraph.Role = 5 ∧
    D0.Matter.DSigmaRoleCycleCarrierNoGo.numCanonicalPrimitiveOrbits = 1 := by
  exact ⟨primitiveCirculation_divergenceFree,
    divergenceFree_iff_primitive_line,
    D0.Matter.DSigmaRoleTransitionGraph.dsigma_transition_graph_has_five_nodes,
    rfl⟩

end D0.Matter.CanonicalZoneCirculation
