import Mathlib.GroupTheory.PresentedGroup
import Mathlib.GroupTheory.FreeGroup.Basic
import Mathlib.GroupTheory.FinitelyPresentedGroup
import Mathlib.Tactic

/-!
# D0-BRAID-VALENCE-U1-001 — the Artin braid group, and its 2-strand (U(1)) anchor

BOOK_04 §04.6 [THE 04.6.M1.gauge] reads braid valence on `k` strands as organizing the gauge
structure U(1)/SU(2)/SU(3). The pin has NO dedicated braid group (all "Braid" hits are braided
monoidal categories), but has the full `PresentedGroup` / `FreeGroup` presentation machinery. This
module DEFINES the Artin braid group `BraidGroup n` as a presented group on `Fin (n-1)` Artin
generators, and proves the genuine `k = 2` (abelian, U(1)-type) boundary case:

* `BraidGroup 2` has empty relation set (`braidRels_two`) and is isomorphic to `Multiplicative ℤ`
  (`braidGroupTwoEquiv`) — the infinite-cyclic / U(1)-character group — hence nontrivial and
  finitely presented;
* every `BraidGroup n` is generated by its `n−1` Artin generators (`braidGroup_generated`).

Honest scope: the SU(2)/SU(3) legs (Burau / Temperley–Lieb / Jones unitary representations and the
maps `B n → SU(2)`, `→ SU(3)`) are ABSENT from the pin and stay a BRIDGE-ASSUMPTIONS-EXPLICIT
owner-edge — this is the U(1)/abelian anchor only, not the full trichotomy.
-/

namespace D0.Gauge

/-- Artin relations for the braid group on `n` strands, over generators `σ_i`, `i : Fin (n-1)`:
far-commutation `σ_i σ_j = σ_j σ_i` for `|i−j| ≥ 2`, and the braid relation
`σ_i σ_{i+1} σ_i = σ_{i+1} σ_i σ_{i+1}`. -/
def braidRels (n : ℕ) : Set (FreeGroup (Fin (n - 1))) :=
  {r | (∃ i j : Fin (n - 1), (i : ℕ) + 2 ≤ (j : ℕ) ∧
          r = FreeGroup.of i * FreeGroup.of j * (FreeGroup.of j * FreeGroup.of i)⁻¹) ∨
       (∃ i j : Fin (n - 1), (j : ℕ) = (i : ℕ) + 1 ∧
          r = FreeGroup.of i * FreeGroup.of j * FreeGroup.of i *
                (FreeGroup.of j * FreeGroup.of i * FreeGroup.of j)⁻¹)}

/-- The Artin braid group on `n` strands, as a presented group. -/
def BraidGroup (n : ℕ) : Type := PresentedGroup (braidRels n)

noncomputable instance (n : ℕ) : Group (BraidGroup n) := by
  unfold BraidGroup; infer_instance

/-- For `n = 2` there is a single generator (`Fin 1`); no far pair and no `i, i+1` pair exist, so the
Artin relation set is empty — `B(2)` is free on one generator. -/
theorem braidRels_two : braidRels 2 = (∅ : Set (FreeGroup (Fin 1))) := by
  ext r
  simp only [braidRels, Set.mem_setOf_eq, Set.mem_empty_iff_false, iff_false]
  rintro (⟨i, j, hij, -⟩ | ⟨i, j, hij, -⟩)
  · have hi : (i : ℕ) = 0 := Nat.lt_one_iff.mp i.isLt
    have hj : (j : ℕ) = 0 := Nat.lt_one_iff.mp j.isLt
    omega
  · have hi : (i : ℕ) = 0 := Nat.lt_one_iff.mp i.isLt
    have hj : (j : ℕ) = 0 := Nat.lt_one_iff.mp j.isLt
    omega

/-- **The 2-strand braid group is `Multiplicative ℤ`** (infinite cyclic) — the U(1)-type
free-abelian-on-one-generator boundary case of the braid-valence trichotomy. -/
noncomputable def braidGroupTwoEquiv : BraidGroup 2 ≃* Multiplicative ℤ :=
  haveI : Unique (Fin (2 - 1)) := inferInstanceAs (Unique (Fin 1))
  (QuotientGroup.quotientMulEquivOfEq
      (by rw [braidRels_two]; exact Subgroup.normalClosure_empty)).trans
    (QuotientGroup.quotientBot.trans FreeGroup.mulEquivIntOfUnique)

/-- `B(2)` is nontrivial (the generator has infinite order). -/
theorem braidGroupTwo_nontrivial : Nontrivial (BraidGroup 2) :=
  braidGroupTwoEquiv.toEquiv.nontrivial

/-- Every braid group is generated by its `n−1` Artin generators. -/
theorem braidGroup_generated (n : ℕ) :
    Subgroup.closure (Set.range (PresentedGroup.of : Fin (n - 1) → BraidGroup n)) = ⊤ :=
  PresentedGroup.closure_range_of (braidRels n)

/-- `B(2)` is finitely presented (one generator, no relations). -/
theorem braidGroupTwo_finitelyPresented : Group.IsFinitelyPresented (BraidGroup 2) :=
  Group.IsFinitelyPresented.equiv braidGroupTwoEquiv.symm inferInstance

end D0.Gauge
