import D0.Foundation.M1CoreSaturation

/-!
# The trace-class wall: summability holds exactly on the subcritical region

`D0-P-SUBCRIT-001` owns the rate characterization `rate a < 1 ↔ a ≤ 2` with `rate 3 = 1` the
critical wall (`D0.Foundation.M1CoreSaturation.subcritical_iff`,
`D0.Spectral.AlphaPresentCoreMaximalityNoGo.rate_three_eq_one`). Its registry row names what is
missing, verbatim:

> "Trace-class (Summable) reading remains with NOGO row
> `D0-ALPHA-PRESENT-CORE-MAXIMALITY-NOGO-001`; **not-Summable at the wall not formalized**"

That is what this module supplies. The rate governs a geometric weight `n ↦ (rate a)^n`, and the
trace-class (summability) property of that weight is decided by the same threshold:

* `summable_at_subcritical` — for `a ≤ 2` the weight is summable;
* `not_summable_at_wall` — at `a = 3`, where `rate 3 = 1`, it is **not**;
* `not_summable_at_critical` — nor for any `a ≥ 3`;
* `summable_iff_subcritical` — the characterization `Summable ↔ a ≤ 2`, so the subcritical region
  is *exactly* the trace-class region, not merely contained in it.

This closes the named gap and makes "maximal trace-class region" a theorem rather than a reading:
the wall `a = 3` is where summability fails, and it fails there and everywhere past it.

**Scope.** This is the summability of the rate-weight `(rate a)^n`, which is the object the
subcritical claim is about; it is not a statement about any operator's singular values, and no
Dixmier/Wodzicki content is touched. The no-go row keeps its own boundary.
-/

namespace D0.Spectral.SubcriticalTraceClass

open D0.Foundation.M1CoreSaturation D0.Spectral.AlphaPresentCoreMaximalityNoGo

/-- The geometric weight generated by the present-core rate at level `a`. -/
noncomputable def rateWeight (a : ℕ) : ℕ → ℝ := fun n => (rate a) ^ n

/-- **Summable below the wall.** For `a ≤ 2` the rate is strictly subcritical, so the weight is
summable — the trace-class region contains the present core. -/
theorem summable_at_subcritical (a : ℕ) (ha : a ≤ 2) : Summable (rateWeight a) := by
  unfold rateWeight
  exact summable_geometric_of_lt_one (le_of_lt (rate_pos a)) (rate_lt_one a ha)

/-- **Not summable past the wall.** For every `a ≥ 3` the rate is at least critical, so the weight
never returns to the trace class. -/
theorem not_summable_at_critical (a : ℕ) (ha : 3 ≤ a) : ¬ Summable (rateWeight a) := by
  unfold rateWeight
  rw [summable_geometric_iff_norm_lt_one, Real.norm_eq_abs, abs_of_pos (rate_pos a)]
  exact not_lt.mpr (rate_ge_one_of_three_le a ha)

/-- **Not summable at the wall.** `rate 3 = 1`, so the series is the constant one and diverges.
This is the statement the registry row records as unformalized. -/
theorem not_summable_at_wall : ¬ Summable (rateWeight 3) :=
  not_summable_at_critical 3 le_rfl

/-- **The characterization.** The trace-class region is *exactly* the subcritical region: the
weight is summable iff `a ≤ 2`. The wall is sharp in both directions. -/
theorem summable_iff_subcritical (a : ℕ) : Summable (rateWeight a) ↔ a ≤ 2 := by
  constructor
  · intro h
    by_contra hgt
    exact not_summable_at_critical a (by omega) h
  · exact summable_at_subcritical a

/-- **Bundle.** Summability holds exactly below the wall, fails at it, and fails past it. -/
theorem subcritical_trace_class :
    (∀ a : ℕ, Summable (rateWeight a) ↔ a ≤ 2) ∧
    ¬ Summable (rateWeight 3) ∧
    (∀ a : ℕ, 3 ≤ a → ¬ Summable (rateWeight a)) :=
  ⟨summable_iff_subcritical, not_summable_at_wall, not_summable_at_critical⟩


/-! ## The present-core carrier object

The same registry row records a second gap: *"present-core carriers `a ∈ {0,1}` sit strictly inside
the region (no core-carrier object formalized)"*. The object is supplied here. -/

/-- The present-core carrier levels. -/
def coreCarriers : Finset ℕ := {0, 1}

/-- **Every core carrier is trace-class.** -/
theorem coreCarrier_summable (a : ℕ) (ha : a ∈ coreCarriers) : Summable (rateWeight a) := by
  fin_cases ha <;> exact summable_at_subcritical _ (by omega)

/-- **Strictly inside, not on the boundary.** A core carrier stays trace-class after a further
step, so it does not sit at the edge `a = 2` of the region; the wall is two steps away from the
whole core. -/
theorem coreCarrier_strictly_inside (a : ℕ) (ha : a ∈ coreCarriers) :
    Summable (rateWeight (a + 1)) ∧ a + 1 ≤ 2 := by
  fin_cases ha
  · exact ⟨summable_at_subcritical 1 (by omega), by omega⟩
  · exact ⟨summable_at_subcritical 2 (by omega), by omega⟩

/-- **The core is separated from the wall.** No core carrier reaches the critical level. -/
theorem coreCarrier_below_wall (a : ℕ) (ha : a ∈ coreCarriers) : a + 2 ≤ 3 := by
  fin_cases ha <;> omega

/-- **Core-carrier bundle.** The present core lies strictly inside the trace-class region, and the
region ends exactly at the wall. -/
theorem core_carrier_object :
    (∀ a ∈ coreCarriers, Summable (rateWeight a)) ∧
    (∀ a ∈ coreCarriers, Summable (rateWeight (a + 1)) ∧ a + 1 ≤ 2) ∧
    (∀ a ∈ coreCarriers, a + 2 ≤ 3) ∧
    ¬ Summable (rateWeight 3) :=
  ⟨coreCarrier_summable, coreCarrier_strictly_inside, coreCarrier_below_wall,
   not_summable_at_wall⟩

end D0.Spectral.SubcriticalTraceClass
