#!/usr/bin/env python3
import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "09_LEAN_FORMALIZATION" / "docs" / "HARD_CLOSURE_TARGETS.csv"
LEAN_PATH = ROOT / "09_LEAN_FORMALIZATION" / "D0" / "TheoremLedger" / "HardClosureTheoremIndex.lean"

def main():
    if not CSV_PATH.exists():
        print(f"Error: {CSV_PATH} does not exist.")
        return 1

    with CSV_PATH.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    # Gather modules and sorted theorem names
    modules = sorted(list(set(row["module"] for row in rows)))

    lines = []
    for module in modules:
        lines.append(f"import {module}")

    lines.append("")
    lines.append("namespace D0")
    lines.append("")
    lines.append("/-!")
    lines.append("Hard closure theorem index. Automatically generated by tools/generate_hard_closure_index.py.")
    lines.append("-/")
    lines.append("")

    for row in rows:
        lines.append(f"#check D0.{row['theorem_name']}")

    lines.append("")
    lines.append("end D0")
    lines.append("")

    LEAN_PATH.parent.mkdir(parents=True, exist_ok=True)
    LEAN_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {LEAN_PATH}")
    return 0

if __name__ == "__main__":
    import sys
    sys.exit(main())
