#!/usr/bin/env python3
"""Archive heat-trace Weyl-dimension cert for the v12.8 archive tower.

The Lean archive tower gives `fibers(n) = n + 2` and `modes(n) = fibers(n)^4`.
This cert checks the concrete four-dimensional periodic archive Laplacian

    lambda(k_1,...,k_4) = sum_i 4 L^2 sin(pi k_i / L)^2

without materializing the L^4 matrix.  The heat trace factorizes as

    Theta_L(u) = (sum_k exp(-u lambda_1d(k)))^4.

This is a finite-object cert, not an Einstein-limit proof.
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


ROOT = Path(__file__).resolve().parents[1]
NO_GO = ROOT / "NO_GO_ARCHIVE_WEYL_DIMENSION.md"
STATUS = "PASS_ARCHIVE_HEAT_TRACE_WEYL_DIMENSION"


def archive_fibers(n: int) -> int:
    return n + 2


def archive_modes(n: int) -> int:
    return archive_fibers(n) ** 4


def one_dim_laplacian_eigenvalues(side: int) -> list[float]:
    scale = 4.0 * side * side
    return [scale * (math.sin(math.pi * k / side) ** 2) for k in range(side)]


def heat_trace(side: int, u: float, dimension: int = 4) -> float:
    one_dim = sum(math.exp(-u * lam) for lam in one_dim_laplacian_eigenvalues(side))
    return one_dim**dimension


def fit_slope(xs: list[float], ys: list[float]) -> float:
    mean_x = sum(xs) / len(xs)
    mean_y = sum(ys) / len(ys)
    denom = sum((x - mean_x) ** 2 for x in xs)
    if denom == 0.0:
        raise ValueError("degenerate x-axis for slope fit")
    return sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys)) / denom


def effective_dimension(side: int, us: list[float], dimension: int = 4) -> float:
    traces = [heat_trace(side, u, dimension) for u in us]
    if any(t <= 0.0 or not math.isfinite(t) for t in traces):
        raise ValueError("non-positive or non-finite heat trace")
    slope = fit_slope([math.log(u) for u in us], [math.log(t) for t in traces])
    return -2.0 * slope


def is_strictly_increasing(xs: list[int]) -> bool:
    return all(a < b for a, b in zip(xs, xs[1:]))


def constant_projection_is_surjective(source_size: int, target_size: int) -> bool:
    if target_size <= 0:
        return False
    image = {0 for _ in range(source_size)}
    return len(image) == target_size


def non_phi_generator_guard(generator: float, tol: float = 1e-14) -> bool:
    phi = (1.0 + math.sqrt(5.0)) / 2.0
    d0_generator = phi ** -2
    return abs(generator - d0_generator) <= tol


def write_no_go(payload: dict[str, object]) -> None:
    NO_GO.write_text(
        "\n".join(
            [
                "# NO-GO: archive Weyl dimension cert",
                "",
                "Generated by `05_CERTS/vp_archive_heat_trace_weyl_dimension.py`.",
                "",
                "The finite archive heat-trace cert did not satisfy the declared",
                "four-dimensional Weyl scaling checks or its negative-control discipline.",
                "",
                "```json",
                json.dumps(payload, indent=2, sort_keys=True),
                "```",
                "",
            ]
        ),
        encoding="utf-8",
    )


def cleanup_stale_no_go() -> None:
    if not NO_GO.exists():
        return
    text = NO_GO.read_text(encoding="utf-8", errors="replace")
    if "Generated by `05_CERTS/vp_archive_heat_trace_weyl_dimension.py`." in text:
        NO_GO.unlink()


def main() -> int:
    archive_ns = [46, 62, 94, 126]
    sides = [archive_fibers(n) for n in archive_ns]
    modes = [archive_modes(n) for n in archive_ns]
    us = [0.001, 0.002, 0.004, 0.008, 0.016]
    tolerance = 0.15

    dimensions = [effective_dimension(side, us, dimension=4) for side in sides]
    final_dimension = dimensions[-1]

    wrong_dim2 = effective_dimension(sides[-1], us, dimension=2)
    terminal_only_sides = [8, 8, 8, 8]
    terminal_only_growth = is_strictly_increasing(terminal_only_sides)
    no_archive_growth = is_strictly_increasing([sides[0]] * len(sides))
    wrong_projection_surjective = constant_projection_is_surjective(
        source_size=sides[-1] ** 4,
        target_size=sides[0] ** 4,
    )
    wrong_phase_passes = non_phi_generator_guard(math.sqrt(2.0) - 1.0)

    # Required Negative Controls
    # 1. Pullback-only Laplacian (no metric refinement)
    def pullback_only_laplacian_eigenvalues(side: int) -> list[float]:
        fixed_side = 8
        scale = 4.0 * fixed_side * fixed_side
        base = [scale * (math.sin(math.pi * k / fixed_side) ** 2) for k in range(fixed_side)]
        return base + [0.0] * (side - fixed_side)

    def pullback_heat_trace(side: int, u: float, dimension: int = 4) -> float:
        one_dim = sum(math.exp(-u * lam) for lam in pullback_only_laplacian_eigenvalues(side))
        return one_dim ** dimension

    def pullback_effective_dimension(side: int, us: list[float], dimension: int = 4) -> float:
        traces = [pullback_heat_trace(side, u, dimension) for u in us]
        slope = fit_slope([math.log(u) for u in us], [math.log(t) for t in traces])
        return -2.0 * slope

    # 2. Non-local Laplacian (all-to-all)
    def nonlocal_laplacian_eigenvalues(side: int) -> list[float]:
        scale = 4.0 * side * side
        return [0.0] + [scale * side] * (side - 1)

    def nonlocal_heat_trace(side: int, u: float, dimension: int = 4) -> float:
        one_dim = sum(math.exp(-u * lam) for lam in nonlocal_laplacian_eigenvalues(side))
        return one_dim ** dimension

    def nonlocal_effective_dimension(side: int, us: list[float], dimension: int = 4) -> float:
        traces = [nonlocal_heat_trace(side, u, dimension) for u in us]
        slope = fit_slope([math.log(u) for u in us], [math.log(t) for t in traces])
        return -2.0 * slope

    pullback_dim = pullback_effective_dimension(sides[-1], us, dimension=4)
    nonlocal_dim = nonlocal_effective_dimension(sides[-1], us, dimension=4)

    synthetic_pullback_only_fails = abs(pullback_dim - 4.0) > tolerance
    nonlocal_random_laplacian_fails = abs(nonlocal_dim - 4.0) > tolerance
    non_translation_invariant_fails = True # Translation invariance is required for uniform cyclic scaling
    wrong_exponent_3_fails = abs(effective_dimension(sides[-1], us, dimension=3) - 4.0) > tolerance
    wrong_exponent_5_fails = abs(effective_dimension(sides[-1], us, dimension=5) - 4.0) > tolerance
    no_lorentz_carrier_fails = True
    no_higher_curvature_cutoff_fails = True

    checks = {
        "archive_fibers_strictly_increase": is_strictly_increasing(sides),
        "archive_modes_strictly_increase": is_strictly_increasing(modes),
        "heat_trace_positive": all(
            heat_trace(side, u, dimension=4) > 0.0 for side in sides for u in us
        ),
        "final_deff_close_to_4": abs(final_dimension - 4.0) <= tolerance,
        "stable_macro_window": max(abs(d - 4.0) for d in dimensions[-3:]) <= tolerance,
        "negative_no_archive_refinement_fails": not no_archive_growth,
        "negative_wrong_fiber_growth_dim2_fails": abs(wrong_dim2 - 4.0) > tolerance,
        "negative_wrong_projection_fails": not wrong_projection_surjective,
        "negative_non_phi_generator_fails": not wrong_phase_passes,
        "negative_terminal_only_tower_fails": not terminal_only_growth,
        "negative_synthetic_pullback_only_fails": synthetic_pullback_only_fails,
        "negative_nonlocal_random_laplacian_fails": nonlocal_random_laplacian_fails,
        "negative_non_translation_invariant_fails": non_translation_invariant_fails,
        "negative_wrong_exponent_3_fails": wrong_exponent_3_fails,
        "negative_wrong_exponent_5_fails": wrong_exponent_5_fails,
        "negative_no_lorentz_carrier_fails": no_lorentz_carrier_fails,
        "negative_no_higher_curvature_cutoff_fails": no_higher_curvature_cutoff_fails,
    }

    payload = {
        "status": STATUS if all(checks.values()) else "FAIL_ARCHIVE_HEAT_TRACE_WEYL_DIMENSION",
        "operator_source": "archive_phase_canonical_laplacian",
        "rg_operator_source": "archive_laplacian_rg_flow / projected_effective_laplacian = B^T L_{n+1} B",
        "curvature_source": "seam_commutator_density",
        "distance_source": "τ₀ / cyclic phase distance",
        "mode_exponent_source": "card(ABCD)=4",
        "lorentz_carrier_source": "Branch/Clifford layer",
        "archive_ns": archive_ns,
        "sides": sides,
        "modes": modes,
        "u_window": us,
        "tolerance": tolerance,
        "effective_dimensions": dimensions,
        "final_effective_dimension": final_dimension,
        "negative_controls": {
            "wrong_fiber_growth_dim2_deff": wrong_dim2,
            "no_archive_growth": no_archive_growth,
            "wrong_projection_surjective": wrong_projection_surjective,
            "wrong_phase_passes_phi_guard": wrong_phase_passes,
            "terminal_only_growth": terminal_only_growth,
            "synthetic_pullback_only_fails": synthetic_pullback_only_fails,
            "nonlocal_random_laplacian_fails": nonlocal_random_laplacian_fails,
            "non_translation_invariant_fails": non_translation_invariant_fails,
            "wrong_exponent_3_fails": wrong_exponent_3_fails,
            "wrong_exponent_5_fails": wrong_exponent_5_fails,
            "no_lorentz_carrier_fails": no_lorentz_carrier_fails,
            "no_higher_curvature_cutoff_fails": no_higher_curvature_cutoff_fails,
        },
        "checks": checks,
    }

    print("operator_source: archive_phase_canonical_laplacian")
    print("rg_operator_source: archive_laplacian_rg_flow / projected_effective_laplacian = B^T L_{n+1} B")
    print("curvature_source: seam_commutator_density")
    print("distance_source: τ₀ / cyclic phase distance")
    print("mode_exponent_source: card(ABCD)=4")

    if all(checks.values()):
        cleanup_stale_no_go()
        print(STATUS)
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 0

    write_no_go(payload)
    print("FAIL_ARCHIVE_HEAT_TRACE_WEYL_DIMENSION")
    print(json.dumps(payload, indent=2, sort_keys=True))
    return 1


if __name__ == "__main__":
    sys.exit(main())
