#!/usr/bin/env python3
"""D0-ISING-ANYON-EXCLUSION-001 - Ising is EXCLUDED from the internal degree-two CORE carrier.

NO-GO (finite branch-count obstruction), NOT a classification of unitary fusion categories.
We certify exactly, and able to FAIL, that the three Ising simple objects {1, sigma, psi}
exceed the two independent branch labels fixed by the internal degree-two quadratic p+p^2=1.

THE FIXED STRUCTURE (before any number):
  * the D0 CORE time field Q(phi)/Q has minimal polynomial x^2 - x - 1 (deg 2);
  * the toral operator T = [[0,1],[1,-1]] has charpoly x^2 + x - 1 with exactly TWO eigen-branches
    (phi^-1, -phi);
  * the single internal generating relation p + p^2 = 1 fixes exactly two independent branch labels.

WHAT IS PROVED (exact; able to FAIL):
  * the toral charpoly x^2 + x - 1 has exactly two distinct roots => 2 eigen-branches;
  * an Ising-type fusion carrier has three simple objects {1, sigma, psi}: psi (x) psi = 1,
    sigma (x) sigma = 1 (+) psi, sigma (x) psi = sigma (fusion rules), so |objects| = 3;
  * 3 > 2: Ising needs strictly more simple objects than the internal carrier supplies branches;
  * the EXTRA label (3 - 2 = 1) is NOT generated by the degree-two relation p+p^2=1 (the relation
    fixes 2 labels), so it must come from an external catalog => Ising is excluded.

NEGATIVE CONTROLS (planted wrong inputs, must be rejected):
  * Ising admitted with only TWO branch labels is rejected (Ising genuinely has 3 simple objects);
  * psi declared "hidden / unobservable" to fake a 2-object carrier is rejected (psi is a genuine
    simple object: psi (x) psi = 1, psi != 1, and it appears in sigma (x) sigma = 1 (+) psi);
  * the claim that this excludes Ising as a fusion category in GENERAL is rejected (we only exclude
    it from the internal degree-two CORE carrier; the external MTC classification is NOT done).

HONEST RESIDUAL (printed, not hidden):
  * the full unitary fusion / modular tensor category classification stays EXTERNAL and is NOT
    claimed. We prove only the finite branch-count obstruction 3 > 2 for the internal carrier.
"""
from __future__ import annotations

import sys
from fractions import Fraction as F

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


class Surd:
    """Exact a + b*sqrt5 over Q."""

    def __init__(self, a, b=0):
        self.a, self.b = F(a), F(b)

    def __add__(self, o):
        o = o if isinstance(o, Surd) else Surd(o)
        return Surd(self.a + o.a, self.b + o.b)

    def __sub__(self, o):
        o = o if isinstance(o, Surd) else Surd(o)
        return Surd(self.a - o.a, self.b - o.b)

    def __mul__(self, o):
        o = o if isinstance(o, Surd) else Surd(o)
        return Surd(self.a * o.a + 5 * self.b * o.b, self.a * o.b + self.b * o.a)

    def __eq__(self, o):
        o = o if isinstance(o, Surd) else Surd(o)
        return self.a == o.a and self.b == o.b

    def __hash__(self):
        return hash((self.a, self.b))


def trace(A):
    return A[0][0] + A[1][1]


def det(A):
    return A[0][0] * A[1][1] - A[0][1] * A[1][0]


def main() -> int:
    print("=== D0-ISING-ANYON-EXCLUSION-001  Ising excluded from internal degree-two CORE carrier (NO-GO) ===")
    print("STRUCTURE_FIXED_BEFORE_NUMBER: the toral charpoly x^2+x-1 (2 eigen-branches) and the single "
          "degree-two generating relation p+p^2=1 are FIXED before the Ising object count is computed")

    one = Surd(1)
    phi_inv = Surd(F(-1, 2), F(1, 2))   # phi^-1
    neg_phi = Surd(F(-1, 2), F(-1, 2))  # -phi

    # ---- (1) internal carrier supplies exactly TWO eigen-branches ----------------------
    T = [[0, 1], [1, -1]]
    assert trace(T) == -1 and det(T) == -1, "T trace -1, det -1 => charpoly x^2 + x - 1"

    def toral_charpoly(x: Surd) -> Surd:
        return x * x + x - one

    assert toral_charpoly(phi_inv) == Surd(0) and toral_charpoly(neg_phi) == Surd(0), \
        "phi^-1 and -phi are the toral eigen-branches"
    eigenbranches = {phi_inv, neg_phi}
    toral_branch_count = len(eigenbranches)
    assert toral_branch_count == 2, "internal carrier fixes exactly 2 independent branch labels"
    print(f"PASS_TORAL_BRANCH_COUNT_TWO  x^2+x-1 => {toral_branch_count} eigen-branches (internal label budget)")

    # ---- (2) Ising carrier has THREE simple objects {1, sigma, psi} --------------------
    ising_objects = {"1", "sigma", "psi"}
    # Ising fusion rules (exact, integer fusion multiplicities):
    #   psi (x) psi   = 1
    #   sigma (x) sigma = 1 (+) psi
    #   sigma (x) psi  = sigma
    fusion = {
        ("psi", "psi"): {"1": 1},
        ("sigma", "sigma"): {"1": 1, "psi": 1},
        ("sigma", "psi"): {"sigma": 1},
    }
    # consistency: every object appearing in any fusion outcome is one of the 3 simple objects
    for pair, out in fusion.items():
        for obj in list(pair) + list(out.keys()):
            assert obj in ising_objects, f"fusion stays within the 3 simple objects, saw {obj}"
    # psi is a genuine NON-trivial simple object (psi != 1) that squares to 1
    assert "psi" in ising_objects and fusion[("psi", "psi")] == {"1": 1}, "psi (x) psi = 1, psi is genuine"
    assert "psi" != "1", "psi is distinct from the unit"
    # psi is forced to exist: it appears in sigma (x) sigma = 1 (+) psi, so it cannot be dropped
    assert "psi" in fusion[("sigma", "sigma")], "psi appears in sigma(x)sigma = 1 (+) psi => cannot be hidden"
    ising_simple_object_count = len(ising_objects)
    assert ising_simple_object_count == 3, "Ising has exactly 3 simple objects {1, sigma, psi}"
    print(f"PASS_ISING_OBJECT_COUNT_THREE  {{1, sigma, psi}} with fusion rules => {ising_simple_object_count} simple objects")

    # ---- (3) the exclusion: 3 > 2, with a required extra label not generated internally
    assert ising_simple_object_count > toral_branch_count, "3 > 2: Ising exceeds the internal branch budget"
    extra = ising_simple_object_count - toral_branch_count
    assert extra == 1, "Ising needs exactly 1 extra independent branch label beyond p+p^2=1"
    print(f"PASS_ISING_EXCLUSION  3 > 2: Ising needs {extra} extra branch label not generated by p+p^2=1 => EXCLUDED")

    # ---- negative controls (planted wrong inputs, must be rejected) --------------------
    # (a) Ising admitted with only 2 branch labels: wrong, Ising genuinely has 3 objects
    ising_admitted_with_two_branches = (ising_simple_object_count == 2)
    assert not ising_admitted_with_two_branches, \
        "control: Ising does NOT have only 2 simple objects (it has 3) => 2-branch admission rejected"
    print("FAIL_ISING_ADMITTED_WITH_TWO_BRANCHES_REJECTED  Ising has 3 objects, not 2 (false admission caught)")

    # (b) psi hidden as unobservable to fake a 2-object carrier: rejected, psi is genuine
    fake_objects_psi_hidden = ising_objects - {"psi"}
    psi_is_genuinely_present = ("psi" in fusion[("sigma", "sigma")]) and (fusion[("psi", "psi")] == {"1": 1})
    assert psi_is_genuinely_present, "psi is a genuine simple object and cannot be declared unobservable"
    assert len(fake_objects_psi_hidden) != ising_simple_object_count, \
        "control: hiding psi changes the object count => the hidden-psi 2-object carrier is a fake"
    print("FAIL_PSI_HIDDEN_AS_UNOBSERVABLE_REJECTED  psi appears in sigma(x)sigma=1+psi (genuine object, not hideable)")

    # (c) claiming this excludes Ising as a fusion category in general: rejected
    excludes_ising_as_general_fusion_category = False  # only excluded from the internal carrier
    assert not excludes_ising_as_general_fusion_category, \
        "control: Ising is excluded ONLY from the internal degree-2 carrier, NOT as a general category"
    print("FAIL_ALL_FUSION_CATEGORIES_CLASSIFIED_REJECTED  exclusion is internal-carrier only (external NOT done)")

    print("PASS_ISING_NEGATIVE_CONTROLS")

    # ---- honest residual ---------------------------------------------------------------
    print("HONEST_RESIDUAL_FULL_UNITARY_FUSION_MODULAR_TENSOR_CATEGORY_CLASSIFICATION_STAYS_EXTERNAL_NOT_CLAIMED")
    print("HONEST_SCOPE_ONLY_FINITE_BRANCH_COUNT_OBSTRUCTION_3_GT_2_FOR_THE_INTERNAL_DEGREE_TWO_CARRIER")

    print("PASS_ISING_ANYON_EXCLUSION")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
