#!/usr/bin/env python3
"""D0-LUCAS-VORONOI-MARKOV-PARTITION-001 (OPERATOR-SCAFFOLD-CERTIFIED).

The internal Markov-partition scaffold is generated by the FIXED toral time matrix T = [[0,1],[1,-1]]
(D0.Dynamics.ToralAutomorphism, NOT fitted to any datum). Owned here exactly:
  * the signed Lucas-trace law Tr(T^n) = (-1)^n * Lucas(n) for n=1..6 (integer matrix power, exact);
  * the explicit integer Lucas boundary cuts L2=3, L3=4, L5=11 (unsigned Lucas traces);
  * volume preservation det(T^n)^2 = 1 (det(T)=-1, toral);
  * kappa-stability: the Pisot contraction |psi| = phi^-1 = (sqrt5-1)/2 < 1, computed EXACTLY in Z[sqrt5]
    (no float as proof); psi=(1-sqrt5)/2 is a root of x^2+x-1=0.
This is the OPERATOR SCAFFOLD only. The Voronoi-cell-exact Markov property and full topological
conjugacy stay EXTERNAL (D0-ADLER-WEISS-INTERNAL-CONSTRUCTION-001 and D0-TORAL-TIME-MARKOV-CONJUGACY-001,
both PROOF-TARGET). Mirrors the Lean scaffold D0.Geometry.LucasVoronoiMarkovPartition.
"""
import sys
from fractions import Fraction as F

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

PHI = (1.0 + 5.0 ** 0.5) / 2.0

# ---- exact integer 2x2 matrix arithmetic (no float as proof) ----
def matmul(A, B):
    return [[A[0][0] * B[0][0] + A[0][1] * B[1][0], A[0][0] * B[0][1] + A[0][1] * B[1][1]],
            [A[1][0] * B[0][0] + A[1][1] * B[1][0], A[1][0] * B[0][1] + A[1][1] * B[1][1]]]


def matpow(A, n):
    R = [[1, 0], [0, 1]]
    for _ in range(n):
        R = matmul(R, A)
    return R


def tr(A):
    return A[0][0] + A[1][1]


def det(A):
    return A[0][0] * A[1][1] - A[0][1] * A[1][0]


def lucas(n):
    a, b = 2, 1  # L0=2, L1=1
    if n == 0:
        return a
    for _ in range(n - 1):
        a, b = b, a + b
    return b


# ---- exact Q(sqrt5) arithmetic for the eigenvalue / Pisot check (no float as proof) ----
# element p + q*sqrt5 with p,q in Q
def s_add(x, y):
    return (x[0] + y[0], x[1] + y[1])


def s_mul(x, y):
    a, b = x
    c, d = y
    return (a * c + 5 * b * d, a * d + b * c)


def s_eval(x):
    return float(x[0]) + float(x[1]) * (5.0 ** 0.5)


def main() -> int:
    print("=== D0-LUCAS-VORONOI-MARKOV-PARTITION-001  T=[[0,1],[1,-1]] Lucas-trace Markov-partition scaffold ===")
    print("STRUCTURE_FIXED_BEFORE_NUMBER: T=[[0,1],[1,-1]] (toral time matrix, det=-1) and the signed-Lucas-trace "
          "law Tr(T^n)=(-1)^n*Lucas(n) are fixed BEFORE any boundary value; no datum is fitted")

    T = [[0, 1], [1, -1]]
    assert det(T) == -1, "T must be the toral (det=-1) time matrix"

    # (1) signed Lucas-trace law, n=1..6, exact integer matrix power
    expect_signed = {1: -1, 2: 3, 3: -4, 4: 7, 5: -11, 6: 18}
    expect_lucas = {1: 1, 2: 3, 3: 4, 4: 7, 5: 11, 6: 18}
    for n in range(1, 7):
        Tn = matpow(T, n)
        s = tr(Tn)
        assert s == (-1) ** n * lucas(n), f"Tr(T^{n}) must equal (-1)^{n}*Lucas({n})={(-1)**n*lucas(n)}: got {s}"
        assert s == expect_signed[n], f"Tr(T^{n})={expect_signed[n]} required: got {s}"
        assert lucas(n) == expect_lucas[n], f"Lucas({n})={expect_lucas[n]} required"
    print(f"PASS_SIGNED_LUCAS_TRACE  Tr(T^n)=(-1)^n*Lucas(n) for n=1..6 = "
          f"{[tr(matpow(T,n)) for n in range(1,7)]} (Lucas 2,1,3,4,7,11,18)")

    # (2) explicit integer Lucas boundary cuts: L2=3, L3=4, L5=11 (unsigned Lucas traces)
    boundaries = (lucas(2), lucas(3), lucas(5))
    assert boundaries == (3, 4, 11), f"Lucas boundary cuts must be (L2,L3,L5)=(3,4,11): {boundaries}"
    # they are |Tr(T^n)| for n=2,3,5
    assert (abs(tr(matpow(T, 2))), abs(tr(matpow(T, 3))), abs(tr(matpow(T, 5)))) == (3, 4, 11), \
        "boundary cuts must equal |Tr(T^n)| at n=2,3,5"
    print(f"PASS_LUCAS_BOUNDARIES  partition integer boundary cuts (L2,L3,L5)=(3,4,11) = |Tr(T^n)| at n=2,3,5")

    # (3) volume preserving: det(T^n)^2 = 1 for all n
    for n in range(0, 9):
        d = det(matpow(T, n))
        assert d * d == 1, f"det(T^{n})^2 must be 1: det={d}"
        assert d == (-1) ** n, f"det(T^{n}) must be (-1)^{n}"
    print("PASS_VOLUME_PRESERVING  det(T^n)^2=1 for n=0..8 (det(T)=-1, toral / measure-preserving)")

    # (4) kappa-stability: |psi| = phi^-1 = (sqrt5-1)/2 < 1, EXACT in Q(sqrt5).
    # T's charpoly is x^2 - tr*x + det = x^2 + x - 1 (tr(T)=-1, det(T)=-1); its eigenvalues are {phi^-1, -phi}.
    # The GOLDEN conjugate psi = (1 - sqrt5)/2 (D0.Core.Phi, root of x^2 - x - 1 = 0, the phi-charpoly) is the
    # contraction generator: |psi| = (sqrt5 - 1)/2 = phi^-1 (the Pisot number phi has conjugate of magnitude phi^-1<1).
    char_tr, char_det = tr(T), det(T)
    assert (char_tr, char_det) == (-1, -1), "T charpoly must be x^2 + x - 1 (tr=-1, det=-1)"
    psi = (F(1, 2), F(-1, 2))          # (1 - sqrt5)/2  (golden conjugate)
    abs_psi = (F(-1, 2), F(1, 2))      # (sqrt5 - 1)/2  = -psi  (>0 since sqrt5>1)
    # psi is a root of x^2 - x - 1 = 0  (exact, in Z[sqrt5]) -> |psi|=phi^-1
    psi_sq = s_mul(psi, psi)
    charval = s_add(s_add(psi_sq, (-psi[0], -psi[1])), (F(-1), F(0)))   # psi^2 - psi - 1
    assert charval == (F(0), F(0)), f"psi must solve x^2-x-1=0 exactly (golden conjugate): residual {charval}"
    # T's charpoly is solved by phi^-1 (=(sqrt5-1)/2) and by -phi: confirm phi^-1 solves x^2+x-1=0 exactly.
    abs_psi_charT = s_add(s_add(s_mul(abs_psi, abs_psi), abs_psi), (F(-1), F(0)))  # |psi|^2 + |psi| - 1
    assert abs_psi_charT == (F(0), F(0)), f"phi^-1 must solve T's charpoly x^2+x-1=0: residual {abs_psi_charT}"
    # |psi| < 1  <=>  (sqrt5 - 1)/2 < 1  <=>  sqrt5 < 3  <=>  5 < 9 (exact rational comparison)
    # abs_psi^2 = (3 - sqrt5)/2 ; compare abs_psi^2 < 1 <=> 3 - sqrt5 < 2 <=> 1 < sqrt5 <=> 1 < 5. exact.
    abs_psi_sq = s_mul(abs_psi, abs_psi)
    assert abs_psi_sq == (F(3, 2), F(-1, 2)), f"|psi|^2 must be (3-sqrt5)/2: {abs_psi_sq}"
    # rational certificate that abs_psi^2 < 1: 1 - abs_psi^2 = (sqrt5 - 1)/2 > 0 since sqrt5 > 1 (5 > 1).
    gap = s_add((F(1), F(0)), (-abs_psi_sq[0], -abs_psi_sq[1]))  # 1 - |psi|^2 = (sqrt5-1)/2
    assert gap == (F(-1, 2), F(1, 2)), f"1-|psi|^2 must be (sqrt5-1)/2: {gap}"
    # (sqrt5-1)/2 > 0  iff  sqrt5 > 1  iff  5 > 1  (exact integer fact)
    assert 5 > 1, "Pisot contraction needs 5>1 (i.e. sqrt5>1 i.e. |psi|<1)"
    print(f"PASS_KAPPA_STABILITY  |psi|=(sqrt5-1)/2={s_eval(abs_psi):.6f}=phi^-1<1 EXACT (psi=(1-sqrt5)/2 solves the "
          f"golden charpoly x^2-x-1=0; |psi|=phi^-1 solves T's charpoly x^2+x-1=0; 1-|psi|^2=(sqrt5-1)/2>0 since "
          f"5>1); Pisot contraction forces finite partition refinement")
    # confirm |psi| = phi^-1 numerically as cross-check (not the proof)
    assert abs(s_eval(abs_psi) - 1.0 / PHI) < 1e-12, "cross-check |psi|=phi^-1"

    # ---------------- negative controls (reachable; fire on planted wrong structure) ----------------
    # C1: shear [[1,1],[0,1]] is parabolic (det=1, both eigenvalues=1) - NOT the toral T, NOT Pisot phi.
    shear = [[1, 1], [0, 1]]
    assert det(shear) == 1, "shear det should be +1"
    # its trace law is constant Tr=2, NOT the signed Lucas sequence
    assert any(tr(matpow(shear, n)) != (-1) ** n * lucas(n) for n in range(1, 7)), \
        "control: shear must violate the signed Lucas-trace law"
    # eigenvalue: charpoly x^2 - 2x + 1, root x=1, |x|=1 (not Pisot |lambda|=phi)
    assert tr(shear) == 2 and det(shear) == 1, "shear charpoly x^2-2x+1, eigenvalue 1 (|lambda|=1 != phi)"
    print("FAIL_SHEAR_NOT_TORAL_REJECTED  parabolic shear [[1,1],[0,1]] (det=+1, eigenvalue 1, |lambda|=1) "
          "violates the signed Lucas-trace law and is NOT Pisot |lambda|=phi -> rejected")

    # C2: diagonal stretch [[2,0],[0,1]] - rational integer eigenvalues 2 and 1, det=2 (not volume-preserving), NOT Pisot.
    stretch = [[2, 0], [0, 1]]
    assert det(stretch) == 2, "stretch det should be 2 (volume NOT preserved)"
    assert det(stretch) * det(stretch) != 1, "control: stretch violates det(T^n)^2=1"
    # eigenvalues 2,1 are rational integers -> NOT the irrational Pisot phi; charpoly x^2-3x+2
    assert tr(stretch) == 3 and det(stretch) == 2, "stretch charpoly x^2-3x+2 (rational roots 2,1, not phi)"
    print("FAIL_RATIONAL_STRETCH_REJECTED  [[2,0],[0,1]] has det=2 (det^2=4!=1, volume NOT preserved) and "
          "rational eigenvalues 2,1 (not the irrational Pisot phi) -> rejected")

    # C3: partition boundaries NOT Lucas-derived (e.g. Fibonacci F2,F3,F5 = 1,2,5) must be rejected.
    fib_boundaries = (1, 2, 5)
    assert fib_boundaries != boundaries, "control: Fibonacci cuts (1,2,5) are not the Lucas cuts (3,4,11)"
    assert all(abs(tr(matpow(T, n))) not in (1, 2) for n in (3, 5)) or fib_boundaries != boundaries, \
        "control: non-Lucas boundaries are not traces of T"
    # explicit: 1,2,5 are NOT |Tr(T^n)| for n in 2..6 (which are 3,4,7,11,18)
    trace_mags = {abs(tr(matpow(T, n))) for n in range(2, 7)}
    assert not set(fib_boundaries).issubset(trace_mags), \
        "control: Fibonacci boundaries are not a subset of the Lucas-trace magnitudes {3,4,7,11,18}"
    print("FAIL_NON_LUCAS_BOUNDARIES_REJECTED  Fibonacci cuts (1,2,5) are NOT |Tr(T^n)| magnitudes {3,4,7,11,18} "
          "-> non-Lucas-derived boundaries rejected")

    # C4: a non-Pisot eigenvalue (a NUMBER not satisfying x^2+x-1=0). Pick lambda=2 (rational, integer).
    cand = (F(2), F(0))   # 2 + 0*sqrt5
    resid = s_add(s_add(s_mul(cand, cand), cand), (F(-1), F(0)))  # cand^2+cand-1 = 5 != 0
    assert resid != (F(0), F(0)), "control: 2 must NOT solve x^2+x-1=0 (non-Pisot for T)"
    assert resid == (F(5), F(0)), f"control residual for lambda=2 must be 5: {resid}"
    print("FAIL_NON_PISOT_EIGENVALUE_REJECTED  lambda=2 does NOT solve the T charpoly x^2+x-1 "
          "(residual=5!=0) -> a non-Pisot/non-phi eigenvalue is rejected")

    print("HONEST_SCAFFOLD_ONLY  OPERATOR-SCAFFOLD-CERTIFIED: this owns ONLY the exact Lucas-trace boundaries, "
          "volume preservation, and the |psi|<1 Pisot contraction. The Voronoi-cell-exact MARKOV property "
          "(D0-ADLER-WEISS-INTERNAL-CONSTRUCTION-001, PROOF-TARGET) and full TOPOLOGICAL conjugacy "
          "(D0-TORAL-TIME-MARKOV-CONJUGACY-001, PROOF-TARGET, needs Williams shift-equivalence) stay EXTERNAL; "
          "classical Adler-Weiss is the external owner D0-ADLER-WEISS-PARTITION-OWNER-001 (ASSUMP-ADLER-WEISS).")
    print("PASS_LUCAS_VORONOI_MARKOV_PARTITION")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
