#!/usr/bin/env python3
"""D0-PHI-CYLINDER-TRACE-UNIQUE-001 — the D0-admissible φ-cylinder trace is unique.

On the finite/profinite cylinder tower of the golden (Fibonacci) subshift, the normalized
shift-invariant trace is FIXED by the finite cylinder frequencies: it is the unique normalized left
Perron eigenvector of the primitive golden transition matrix M = [[1,1],[1,0]] (the "no bb" rule).
That stationary distribution is exactly the golden split (φ⁻¹, φ⁻²) — the same W_ext/W_int of
D0-IM-002. Any alternative trace differing on a finite cylinder must change at least one finite
cylinder frequency: a new "which frequency" catalog not generated by the D0 support/projection chain,
hence inadmissible by M1.

Scope: this closes the D0-INTERNAL admissible cylinder trace only. The external C*-crossed-product
unique-trace theorem for C(X_φ) ⋊ ℤ stays a passport (D0-PHI-CSTAR-PASSPORT-001) — not claimed here
from a bare scalar.
"""
from __future__ import annotations

import sys
from fractions import Fraction as F

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")

PHI = (1.0 + 5.0 ** 0.5) / 2.0


# --- exact ℚ(φ): (a,b) = a + b·φ, with φ² = φ + 1 ---
def mul(x, y):
    a, b = x
    c, d = y
    return (a * c + b * d, a * d + b * c + b * d)


def add(*xs):
    return (sum(x[0] for x in xs), sum(x[1] for x in xs))


def smul(c, x):
    return (c * x[0], c * x[1])


def val(x):
    return float(x[0]) + float(x[1]) * PHI


ONE = (F(1), F(0))
PHIv = (F(0), F(1))
PHI_INV = (F(-1), F(1))     # φ⁻¹ = φ − 1
PHI_INV2 = (F(2), F(-1))    # φ⁻² = 2 − φ


def left_apply(pi, M):
    """(π·M)_j = Σ_i π_i · M_ij, for 2×2 integer M and π a pair of ℚ(φ) values."""
    return tuple(add(*[smul(M[i][j], pi[i]) for i in range(2)]) for j in range(2))


def main() -> int:
    print("=== D0-PHI-CYLINDER-TRACE-UNIQUE-001  unique D0-admissible φ-cylinder trace (Perron–Frobenius + M1) ===")
    print("STRUCTURE_FIXED_BEFORE_NUMBER: golden subshift transition M=[[1,1],[1,0]] (the 'no bb' rule), primitive; "
          "the trace is the normalized shift-invariant state on the finite cylinder tower, fixed before any value")

    M = [[1, 1], [1, 0]]
    M2 = [[sum(M[i][k] * M[k][j] for k in range(2)) for j in range(2)] for i in range(2)]
    assert all(M2[i][j] > 0 for i in range(2) for j in range(2)), "golden transition must be primitive (M^2 > 0)"
    print(f"PASS_PRIMITIVE_TRANSITION  M^2={M2} strictly positive => Perron-Frobenius gives a UNIQUE stationary state")

    # the stationary normalized trace = golden split (φ⁻¹, φ⁻²); satisfies π M = φ π and Σπ = 1
    pi = (PHI_INV, PHI_INV2)
    piM = left_apply(pi, M)
    phi_pi = (mul(PHIv, pi[0]), mul(PHIv, pi[1]))
    assert piM == phi_pi, f"stationary trace must satisfy pi M = phi pi: {piM} vs {phi_pi}"
    assert add(pi[0], pi[1]) == ONE, f"trace must be normalized to 1: {add(pi[0], pi[1])}"
    print(f"PASS_UNIQUE_STATIONARY_TRACE  pi=(phi^-1,phi^-2)=({val(pi[0]):.6f},{val(pi[1]):.6f}); pi M = phi pi; sum=1 "
          "(the golden split W_ext/W_int = the unique cylinder frequencies, ties to D0-IM-002)")

    # embedding compatibility: τ_{N+1} ∘ ι_N = τ_N, i.e. (π M)/φ = π (parent freq = marginal of children)
    refined = left_apply(pi, M)
    consistent = (mul(PHI_INV, refined[0]), mul(PHI_INV, refined[1]))
    assert consistent == pi, "cylinder refinement must be embedding-consistent: (pi M)/phi = pi"
    print("PASS_REFINEMENT_CONSISTENT  (pi M)/phi = pi -- level-N cylinder frequencies are the marginals of level-(N+1) "
          "(the embeddings preserve the normalized trace)")

    # trace property on the commutative diagonal cylinder algebra: τ(ab)=τ(ba)
    a_diag, b_diag = (pi[0], pi[1]), (pi[1], pi[0])
    tau_ab = add(mul(a_diag[0], b_diag[0]), mul(a_diag[1], b_diag[1]))
    tau_ba = add(mul(b_diag[0], a_diag[0]), mul(b_diag[1], a_diag[1]))
    assert tau_ab == tau_ba, "trace property tau(ab)=tau(ba) must hold"
    print("PASS_TRACE_PROPERTY  tau(ab)=tau(ba) on the commutative diagonal cylinder algebra")

    # ---- negative controls (must FAIL the stationary/normalized trace conditions) ----
    uniform = (smul(F(1, 2), ONE), smul(F(1, 2), ONE))   # an external 'uniform' frequency catalog
    assert left_apply(uniform, M) != (mul(PHIv, uniform[0]), mul(PHIv, uniform[1])), \
        "control: a uniform (1/2,1/2) trace must NOT be stationary for the golden transition"
    print("FAIL_UNIFORM_TRACE_REJECTED  uniform (1/2,1/2) fails pi M = phi pi -- it is not the golden cylinder measure")

    reweighted = (PHI_INV, smul(F(2), PHI_INV2))         # reweight a single cylinder
    assert add(reweighted[0], reweighted[1]) != ONE, \
        "control: reweighting one cylinder breaks the normalized-trace condition"
    print("FAIL_REWEIGHTED_CYLINDER_REJECTED  doubling one cylinder weight breaks normalization (a 'which frequency' catalog)")

    print("HONEST_M1_UNIQUENESS  the trace is fixed by the finite cylinder frequencies (Perron-Frobenius); any alternative "
          "differing on a finite cylinder needs an external 'which frequency' catalog -> inadmissible by M1. External "
          "C*-crossed-product unique trace stays the passport D0-PHI-CSTAR-PASSPORT-001, not claimed from a bare scalar.")

    print("PASS_PHI_CYLINDER_TRACE_UNIQUE")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
